TwoWire
uint8_t TwoWire::num
Referenced by begin.
int8_t TwoWire::sda
Referenced by begin, setPins.
int8_t TwoWire::scl
Referenced by begin, setPins.
i2c_t* TwoWire::i2c
Referenced by begin, busy, flush, getClock, readTransmission, setClock, setDebugFlags, setPins, writeTransmission, ~TwoWire.
uint8_t TwoWire::rxBuffer[I2C_BUFFER_LENGTH][I2C_BUFFER_LENGTH]
Referenced by peek, read, requestFrom.
uint16_t TwoWire::rxIndex
Referenced by available, endTransmission, flush, peek, read, requestFrom.
uint16_t TwoWire::rxLength
Referenced by available, endTransmission, flush, peek, read, requestFrom.
uint16_t TwoWire::rxQueued
Referenced by endTransmission, flush, requestFrom.
uint8_t TwoWire::txBuffer[I2C_BUFFER_LENGTH][I2C_BUFFER_LENGTH]
Referenced by endTransmission, write.
uint16_t TwoWire::txIndex
Referenced by beginTransmission, endTransmission, flush, write.
uint16_t TwoWire::txLength
Referenced by beginTransmission, endTransmission, flush, write.
uint16_t TwoWire::txAddress
Referenced by beginTransmission, endTransmission.
uint16_t TwoWire::txQueued
Referenced by beginTransmission, endTransmission, flush, requestFrom.
uint8_t TwoWire::transmitting
Referenced by beginTransmission, endTransmission, write.
i2c_err_t TwoWire::last_error
Referenced by beginTransmission, endTransmission, lastError, readTransmission, requestFrom, write, writeTransmission.
uint16_t TwoWire::_timeOutMillis
Referenced by getTimeOut, readTransmission, setTimeOut, writeTransmission.
TwoWire::TwoWire(uint8_t bus_num)
TwoWire::~TwoWire()
References flush, i2c.
bool TwoWire::setPins(int sda, int scl)
References i2c, scl, sda.
bool TwoWire::begin(int sda=-1, int scl=-1, uint32_t frequency=0)
References flush, i2c, num, scl, sda.
Referenced by MPU::init.
void TwoWire::setClock(uint32_t frequency)
References i2c.
Referenced by MPU::init.
size_t TwoWire::getClock()
References i2c.
void TwoWire::setTimeOut(uint16_t timeOutMillis)
References _timeOutMillis.
uint16_t TwoWire::getTimeOut()
References _timeOutMillis.
uint8_t TwoWire::lastError()
References last_error.
char * TwoWire::getErrorText(uint8_t err)
References ERRORTEXT.
i2c_err_t TwoWire::writeTransmission(uint16_t address, uint8_t *buff, uint16_t size, bool sendStop=true)
References _timeOutMillis, i2c, last_error.
Referenced by endTransmission.
i2c_err_t TwoWire::readTransmission(uint16_t address, uint8_t *buff, uint16_t size, bool sendStop=true, uint32_t *readCount=NULL)
References _timeOutMillis, i2c, last_error.
Referenced by requestFrom.
void TwoWire::beginTransmission(uint16_t address)
References last_error, transmitting, txAddress, txIndex, txLength, txQueued.
Referenced by beginTransmission, I2Cdev::readBytes, I2Cdev::readWords, I2Cdev::writeBytes, I2Cdev::writeWords.
void TwoWire::beginTransmission(uint8_t address)
References beginTransmission.
void TwoWire::beginTransmission(int address)
References beginTransmission.
uint8_t TwoWire::endTransmission(bool sendStop)
References flush, last_error, rxIndex, rxLength, rxQueued, transmitting, txAddress, txBuffer, txIndex, txLength, txQueued, writeTransmission.
Referenced by I2Cdev::readBytes, I2Cdev::readWords, I2Cdev::writeBytes, I2Cdev::writeWords.
uint8_t TwoWire::endTransmission(void)
uint8_t TwoWire::requestFrom(uint16_t address, uint8_t size, bool sendStop)
References flush, I2C_BUFFER_LENGTH, last_error, readTransmission, rxBuffer, rxIndex, rxLength, rxQueued, txQueued.
Referenced by I2Cdev::readBytes, I2Cdev::readWords, requestFrom.
uint8_t TwoWire::requestFrom(uint16_t address, uint8_t size, uint8_t sendStop)
References requestFrom.
uint8_t TwoWire::requestFrom(uint16_t address, uint8_t size)
References requestFrom.
uint8_t TwoWire::requestFrom(uint8_t address, uint8_t size, uint8_t sendStop)
References requestFrom.
uint8_t TwoWire::requestFrom(uint8_t address, uint8_t size)
References requestFrom.
uint8_t TwoWire::requestFrom(int address, int size, int sendStop)
References requestFrom.
uint8_t TwoWire::requestFrom(int address, int size)
References requestFrom.
size_t TwoWire::write(uint8_t)
References I2C_BUFFER_LENGTH, last_error, transmitting, txBuffer, txIndex, txLength.
Referenced by I2Cdev::readBytes, I2Cdev::readWords, write, I2Cdev::writeBytes, I2Cdev::writeWords.
size_t TwoWire::write(const uint8_t *, size_t)
References write.
int TwoWire::available(void)
References rxIndex, rxLength.
Referenced by I2Cdev::readBytes, I2Cdev::readWords.
int TwoWire::read(void)
References rxBuffer, rxIndex, rxLength.
Referenced by I2Cdev::readBytes, I2Cdev::readWords.
int TwoWire::peek(void)
References rxBuffer, rxIndex, rxLength.
void TwoWire::flush(void)
References i2c, rxIndex, rxLength, rxQueued, txIndex, txLength, txQueued.
Referenced by begin, endTransmission, requestFrom, ~TwoWire.
size_t TwoWire::write(const char *s)
References write.
size_t TwoWire::write(unsigned long n)
References write.
size_t TwoWire::write(long n)
References write.
size_t TwoWire::write(unsigned int n)
References write.
size_t TwoWire::write(int n)
References write.
void TwoWire::onReceive(void(*)(int))
void TwoWire::onRequest(void(*)(void))
uint32_t TwoWire::setDebugFlags(uint32_t setBits, uint32_t resetBits)
References i2c.
bool TwoWire::busy()
References i2c.