delegate::detail::MultiDelegatePImpl
Node_t* delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::first
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::add, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::erase, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::MultiDelegatePImpl, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator bool, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator=.
Node_t* delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::last
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::add, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::erase, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::MultiDelegatePImpl, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator=.
Node_t* delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::unused
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::get_node_unsafe, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::MultiDelegatePImpl, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator=, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::recycle_node_unsafe.
size_t delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::nodeCount
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::get_node_unsafe, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::MultiDelegatePImpl, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator=.
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::MultiDelegatePImpl()=default
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::~MultiDelegatePImpl()
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::MultiDelegatePImpl(const MultiDelegatePImpl &)=delete
MultiDelegatePImpl& delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator=(const MultiDelegatePImpl &)=delete
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::MultiDelegatePImpl(MultiDelegatePImpl &&md)
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::MultiDelegatePImpl(const Delegate &del)
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::MultiDelegatePImpl(Delegate &&del)
MultiDelegatePImpl& delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator=(MultiDelegatePImpl &&md)
MultiDelegatePImpl& delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator=(std::nullptr_t)
MultiDelegatePImpl& delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator+=(const Delegate &del)
MultiDelegatePImpl& delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator+=(Delegate &&del)
iterator delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::begin()
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::erase, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator().
iterator delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::end() const
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::erase.
const Delegate* IRAM_ATTR delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::add(const Delegate &del)
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::add, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::MultiDelegatePImpl, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator+=.
const Delegate* IRAM_ATTR delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::add(Delegate &&del)
iterator delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::erase(iterator it)
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::erase, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator().
bool delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::erase(const Delegate *const del)
delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator bool() const
R delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::operator()(P...args)
Node_t* IRAM_ATTR delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::get_node_unsafe()
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::add.
void delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY, P >::recycle_node_unsafe(Node_t *node)
Referenced by delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::erase.