EBYTE
Stream* EBYTE::_s
Referenced by available, ClearBuffer, EBYTE, flush, GetByte, GetStruct, ReadModelData, ReadParameters, Reset, SaveParameters, SendByte, SendStruct.
Stream* EBYTE::_TD
int8_t EBYTE::_M0
Referenced by EBYTE, init, SetMode.
int8_t EBYTE::_M1
Referenced by EBYTE, init, SetMode.
int8_t EBYTE::_AUX
Referenced by CompleteTask, EBYTE, GetAux, init.
uint8_t EBYTE::_Params[6][6]
Referenced by ReadModelData, ReadParameters.
uint8_t EBYTE::_Save
Referenced by PrintParameters, ReadModelData, ReadParameters.
uint8_t EBYTE::_AddressHigh
Referenced by GetAddress, GetAddressH, PrintParameters, ReadParameters, SaveParameters, SetAddress, SetAddressH.
uint8_t EBYTE::_AddressLow
Referenced by GetAddress, GetAddressL, PrintParameters, ReadParameters, SaveParameters, SetAddress, SetAddressL.
uint8_t EBYTE::_Speed
Referenced by BuildSpeedByte, GetSpeed, PrintParameters, ReadParameters, SaveParameters, SetSpeed.
uint8_t EBYTE::_Channel
Referenced by GetChannel, PrintParameters, ReadParameters, SaveParameters, SetChannel.
uint8_t EBYTE::_Options
Referenced by BuildOptionByte, GetOptions, PrintParameters, ReadParameters, SaveParameters, SetOptions.
uint8_t EBYTE::_ParityBit
Referenced by BuildSpeedByte, GetParityBit, PrintParameters, ReadParameters, SetParityBit.
uint8_t EBYTE::_UARTDataRate
Referenced by BuildSpeedByte, GetUARTBaudRate, PrintParameters, ReadParameters, SetUARTBaudRate.
uint8_t EBYTE::_AirDataRate
Referenced by BuildSpeedByte, GetAirDataRate, PrintParameters, ReadParameters, SetAirDataRate.
uint8_t EBYTE::_OptionTrans
Referenced by BuildOptionByte, GetTransmissionMode, PrintParameters, ReadParameters, SetTransmissionMode.
uint8_t EBYTE::_OptionPullup
Referenced by BuildOptionByte, GetPullupMode, PrintParameters, ReadParameters, SetPullupMode.
uint8_t EBYTE::_OptionWakeup
Referenced by BuildOptionByte, GetWORTIming, PrintParameters, ReadParameters, SetWORTIming.
uint8_t EBYTE::_OptionFEC
Referenced by BuildOptionByte, GetFECMode, PrintParameters, ReadParameters, SetFECMode.
uint8_t EBYTE::_OptionPower
Referenced by BuildOptionByte, GetTransmitPower, PrintParameters, ReadParameters, SetTransmitPower.
uint16_t EBYTE::_Address
Referenced by ReadParameters.
uint8_t EBYTE::_Model
Referenced by GetModel, PrintParameters, ReadModelData.
uint8_t EBYTE::_Version
Referenced by GetVersion, PrintParameters, ReadModelData.
uint8_t EBYTE::_Features
Referenced by GetFeatures, PrintParameters, ReadModelData.
uint8_t EBYTE::_buf
Referenced by GetStruct, SendStruct.
EBYTE::EBYTE(Stream *s, uint8_t PIN_M0=4, uint8_t PIN_M1=5, uint8_t PIN_AUX=6)
References _AUX, _M0, _M1, _s.
bool EBYTE::init()
References _AUX, _M0, _M1, MODE_NORMAL, ReadModelData, ReadParameters, SetMode.
Referenced by Lora::Lora.
void EBYTE::SetMode(uint8_t mode=MODE_NORMAL)
References _M0, _M1, ClearBuffer, CompleteTask, MODE_NORMAL, MODE_POWERDOWN, MODE_PROGRAM, MODE_WAKEUP, PIN_RECOVER.
Referenced by init, ReadModelData, ReadParameters, Reset, SaveParameters.
void EBYTE::SetAddress(uint16_t val=0)
References _AddressHigh, _AddressLow.
void EBYTE::SetAddressH(uint8_t val=0)
References _AddressHigh.
Referenced by Lora::Lora.
void EBYTE::SetAddressL(uint8_t val=0)
References _AddressLow.
Referenced by Lora::Lora.
void EBYTE::SetAirDataRate(uint8_t val)
References _AirDataRate, BuildSpeedByte.
Referenced by Lora::Lora.
void EBYTE::SetUARTBaudRate(uint8_t val)
References _UARTDataRate, BuildSpeedByte.
Referenced by Lora::Lora.
void EBYTE::SetSpeed(uint8_t val)
References _Speed.
void EBYTE::SetOptions(uint8_t val)
References _Options.
Referenced by Lora::Lora.
void EBYTE::SetChannel(uint8_t val)
References _Channel.
Referenced by Lora::Lora.
void EBYTE::SetParityBit(uint8_t val)
References _ParityBit, BuildSpeedByte.
Referenced by Lora::Lora.
void EBYTE::SetTransmissionMode(uint8_t val)
References _OptionTrans, BuildOptionByte.
void EBYTE::SetPullupMode(uint8_t val)
References _OptionPullup, BuildOptionByte.
void EBYTE::SetWORTIming(uint8_t val)
References _OptionWakeup, BuildOptionByte.
void EBYTE::SetFECMode(uint8_t val)
References _OptionFEC, BuildOptionByte.
void EBYTE::SetTransmitPower(uint8_t val)
References _OptionPower, BuildOptionByte.
bool EBYTE::GetAux()
References _AUX.
bool EBYTE::available()
References _s.
Referenced by Lora::available.
void EBYTE::flush()
References _s.
Referenced by Lora::flush.
uint16_t EBYTE::GetAddress()
References _AddressHigh, _AddressLow.
Referenced by PrintParameters.
uint8_t EBYTE::GetModel()
References _Model.
uint8_t EBYTE::GetVersion()
References _Version.
uint8_t EBYTE::GetFeatures()
References _Features.
uint8_t EBYTE::GetAddressH()
References _AddressHigh.
uint8_t EBYTE::GetAddressL()
References _AddressLow.
uint8_t EBYTE::GetAirDataRate()
References _AirDataRate.
uint8_t EBYTE::GetUARTBaudRate()
References _UARTDataRate.
Referenced by Lora::Lora.
uint8_t EBYTE::GetChannel()
References _Channel.
uint8_t EBYTE::GetParityBit()
References _ParityBit.
uint8_t EBYTE::GetTransmissionMode()
References _OptionTrans.
uint8_t EBYTE::GetPullupMode()
References _OptionPullup.
uint8_t EBYTE::GetWORTIming()
References _OptionWakeup.
uint8_t EBYTE::GetFECMode()
References _OptionFEC.
uint8_t EBYTE::GetTransmitPower()
References _OptionPower.
uint8_t EBYTE::GetOptions()
References _Options.
uint8_t EBYTE::GetSpeed()
References _Speed.
uint8_t EBYTE::GetByte()
References _s.
bool EBYTE::GetStruct(const void *TheStructure, uint16_t size_)
References _buf, _s, CompleteTask.
Referenced by Lora::GetStruct.
void EBYTE::SendByte(uint8_t TheByte)
References _s.
bool EBYTE::SendStruct(const void *TheStructure, uint16_t size_)
References _buf, _s, CompleteTask.
Referenced by Lora::SendStruct.
void EBYTE::PrintParameters()
References _AddressHigh, _AddressLow, _AirDataRate, _Channel, _Features, _Model, _OptionFEC, _OptionPower, _OptionPullup, _Options, _OptionTrans, _OptionWakeup, _ParityBit, _Save, _Speed, _UARTDataRate, _Version, GetAddress.
Referenced by Lora::Lora.
void EBYTE::SaveParameters(uint8_t val=PERMANENT)
References _AddressHigh, _AddressLow, _Channel, _Options, _s, _Speed, CompleteTask, MODE_NORMAL, MODE_PROGRAM, PIN_RECOVER, SetMode.
Referenced by Lora::Lora.
void EBYTE::Reset()
References _s, CompleteTask, MODE_NORMAL, MODE_PROGRAM, SetMode.
Referenced by Lora::reset.
bool EBYTE::ReadParameters()
References _Address, _AddressHigh, _AddressLow, _AirDataRate, _Channel, _OptionFEC, _OptionPower, _OptionPullup, _Options, _OptionTrans, _OptionWakeup, _Params, _ParityBit, _s, _Save, _Speed, _UARTDataRate, MODE_NORMAL, MODE_PROGRAM, SetMode.
Referenced by init.
void EBYTE::CompleteTask(unsigned long timeout=0)
References _AUX, PIN_RECOVER.
Referenced by GetStruct, ReadModelData, Reset, SaveParameters, SendStruct, SetMode.
void EBYTE::BuildSpeedByte()
References _AirDataRate, _ParityBit, _Speed, _UARTDataRate.
Referenced by SetAirDataRate, SetParityBit, SetUARTBaudRate.
void EBYTE::BuildOptionByte()
References _OptionFEC, _OptionPower, _OptionPullup, _Options, _OptionTrans, _OptionWakeup.
Referenced by SetFECMode, SetPullupMode, SetTransmissionMode, SetTransmitPower, SetWORTIming.
bool EBYTE::ReadModelData()
References _Features, _Model, _Params, _s, _Save, _Version, CompleteTask, MODE_NORMAL, MODE_PROGRAM, SetMode.
Referenced by init.
void EBYTE::ClearBuffer()
References _s.
Referenced by SetMode.