PID
double PID::dispKp
Referenced by GetKp, SetTunings.
double PID::dispKi
Referenced by GetKi, SetTunings.
double PID::dispKd
Referenced by GetKd, SetTunings.
double PID::kp
Referenced by Compute, SetControllerDirection, SetTunings.
double PID::ki
Referenced by Compute, SetControllerDirection, SetSampleTime, SetTunings.
double PID::kd
Referenced by Compute, SetControllerDirection, SetSampleTime, SetTunings.
int PID::controllerDirection
Referenced by GetDirection, SetControllerDirection, SetTunings.
int PID::pOn
Referenced by SetTunings.
double* PID::myInput
Referenced by Compute, Initialize, PID.
double* PID::myOutput
Referenced by Compute, Initialize, PID, SetOutputLimits.
double* PID::mySetpoint
Referenced by Compute, PID.
unsigned long PID::lastTime
Referenced by Compute, PID.
double PID::outputSum
Referenced by Compute, Initialize, SetOutputLimits.
double PID::lastInput
Referenced by Compute, Initialize.
unsigned long PID::SampleTime
Referenced by Compute, PID, SetSampleTime, SetTunings.
double PID::outMin
Referenced by Compute, Initialize, SetOutputLimits.
double PID::outMax
Referenced by Compute, Initialize, SetOutputLimits.
bool PID::inAuto
Referenced by Compute, GetMode, PID, SetControllerDirection, SetMode, SetOutputLimits.
bool PID::pOnE
Referenced by Compute, SetTunings.
PID::PID(double *, double *, double *, double, double, double, int, int)
References inAuto, lastTime, myInput, myOutput, mySetpoint, SampleTime, SetControllerDirection, SetOutputLimits, SetTunings.
PID::PID(double *, double *, double *, double, double, double, int)
void PID::SetMode(int Mode)
References AUTOMATIC, inAuto, Initialize.
bool PID::Compute()
References inAuto, kd, ki, kp, lastInput, lastTime, myInput, myOutput, mySetpoint, outMax, outMin, outputSum, pOnE, SampleTime.
Referenced by YawControl::Compute.
void PID::SetOutputLimits(double, double)
References inAuto, myOutput, outMax, outMin, outputSum.
Referenced by PID.
void PID::SetTunings(double, double, double)
References pOn.
Referenced by PID.
void PID::SetTunings(double, double, double, int)
References controllerDirection, dispKd, dispKi, dispKp, kd, ki, kp, P_ON_E, pOn, pOnE, REVERSE, SampleTime.
void PID::SetControllerDirection(int)
References controllerDirection, inAuto, kd, ki, kp.
Referenced by PID.
void PID::SetSampleTime(int)
References kd, ki, SampleTime.
double PID::GetKp()
References dispKp.
double PID::GetKi()
References dispKi.
double PID::GetKd()
References dispKd.
int PID::GetMode()
References AUTOMATIC, inAuto, MANUAL.
int PID::GetDirection()
References controllerDirection.
void PID::Initialize()
References lastInput, myInput, myOutput, outMax, outMin, outputSum.
Referenced by SetMode.