SoftwareSerial
int8_t SoftwareSerial::m_rxPin
Referenced by begin, enableRx, operator bool, setRxGPIOPullUp, SoftwareSerial.
int8_t SoftwareSerial::m_txPin
Referenced by begin, enableTx, operator bool, SoftwareSerial, writePeriod.
int8_t SoftwareSerial::m_txEnablePin
Referenced by setTransmitEnablePin, write.
uint8_t SoftwareSerial::m_dataBits
Referenced by begin, rxBits, write.
bool SoftwareSerial::m_oneWire
Referenced by begin, enableTx, operator bool.
bool SoftwareSerial::m_rxValid
Referenced by available, begin, enableRx, flush, operator bool, peek, perform_work, read, readBytes, setRxGPIOPullUp, write.
bool SoftwareSerial::m_rxEnabled
Referenced by begin, enableRx, isListening.
bool SoftwareSerial::m_txValid
Referenced by availableForWrite, begin, enableTx, end, operator bool, write.
bool SoftwareSerial::m_txEnableValid
Referenced by setTransmitEnablePin, write.
bool SoftwareSerial::m_invert
Referenced by begin, enableRx, enableTx, rxBits, SoftwareSerial, write, writePeriod.
uint8_t SoftwareSerial::m_pduBits
PDU bits include data, parity and stop bits; the start bit is not counted.
Referenced by begin, enableRx, rxBits, write.
bool SoftwareSerial::m_intTxEnabled
Referenced by begin, enableIntTx, preciseDelay, write.
bool SoftwareSerial::m_rxGPIOPullupEnabled
Referenced by enableRxGPIOPullup, setRxGPIOPullUp, SoftwareSerial.
SoftwareSerialParity SoftwareSerial::m_parityMode
Referenced by begin, rxBits, write.
uint8_t SoftwareSerial::m_stopBits
Referenced by begin, rxBits.
bool SoftwareSerial::m_lastReadParity
Referenced by peek, read, readParity.
bool SoftwareSerial::m_overflow
Referenced by overflow, rxBits.
uint32_t SoftwareSerial::m_bitCycles
Referenced by baudRate, begin, enableRx, rxBits, write.
uint8_t SoftwareSerial::m_parityInPos
Referenced by begin, flush, rxBits.
uint8_t SoftwareSerial::m_parityOutPos
Referenced by begin, flush, peek, read.
int8_t SoftwareSerial::m_rxCurBit
Referenced by enableRx, rxBits.
uint8_t SoftwareSerial::m_rxCurByte
Referenced by rxBits.
std::unique_ptr<circular_queue<uint8_t> > SoftwareSerial::m_buffer
Referenced by available, begin, end, flush, peek, perform_work, read, rxBits.
std::unique_ptr<circular_queue<uint8_t> > SoftwareSerial::m_parityBuffer
Referenced by begin, end, flush, peek, read, rxBits.
uint32_t SoftwareSerial::m_periodStart
Referenced by preciseDelay, write.
uint32_t SoftwareSerial::m_periodDuration
Referenced by preciseDelay, write, writePeriod.
uint32_t SoftwareSerial::m_savedPS
Referenced by preciseDelay, write.
std::unique_ptr<circular_queue<uint32_t, SoftwareSerial*> > SoftwareSerial::m_isrBuffer
Referenced by begin, end, rxBits.
const Delegate<void(uint32_t&&), SoftwareSerial*> SoftwareSerial::m_isrBufferForEachDel
Referenced by rxBits.
std::atomic<bool> SoftwareSerial::m_isrOverflow
Referenced by rxBits, SoftwareSerial.
uint32_t SoftwareSerial::m_isrLastCycle
Referenced by enableRx, rxBits.
bool SoftwareSerial::m_rxCurParity
Referenced by rxBits.
Delegate<void(int available), void*> SoftwareSerial::receiveHandler
Referenced by onReceive, perform_work.
SoftwareSerial::SoftwareSerial()
References m_isrOverflow, m_rxGPIOPullupEnabled.
SoftwareSerial::SoftwareSerial(int8_t rxPin, int8_t txPin=-1, bool invert=false)
Ctor to set defaults for pins. rxPin the GPIO pin used for RX txPin -1 for onewire protocol, GPIO pin used for twowire TX
References m_invert, m_isrOverflow, m_rxGPIOPullupEnabled, m_rxPin, m_txPin.
SoftwareSerial::SoftwareSerial(const SoftwareSerial &)=delete
SoftwareSerial& SoftwareSerial::operator=(const SoftwareSerial &)=delete
SoftwareSerial::~SoftwareSerial()
References end.
void SoftwareSerial::begin(uint32_t baud, SoftwareSerialConfig config, int8_t rxPin, int8_t txPin, bool invert, int bufCapacity=64, int isrBufCapacity=0)
Configure the SoftwareSerial object for use. baud the TX/RX bitrate config sets databits, parity, and stop bit count rxPin -1 or default: either no RX pin, or keeps the rxPin set in the ctor txPin -1 or default: either no TX pin (onewire), or keeps the txPin set in the ctor invert true: uses invert line level logic bufCapacity the capacity for the received bytes buffer isrBufCapacity 0: derived from bufCapacity. The capacity of the internal asynchronous bit receive buffer, a suggested size is bufCapacity times the sum of start, data, parity and stop bit count.
References enableRx, isValidRxGPIOpin, isValidTxGPIOpin, m_bitCycles, m_buffer, m_dataBits, m_intTxEnabled, m_invert, m_isrBuffer, m_oneWire, m_parityBuffer, m_parityInPos, m_parityMode, m_parityOutPos, m_pduBits, m_rxEnabled, m_rxPin, m_rxValid, m_stopBits, m_txPin, m_txValid, setRxGPIOPullUp.
Referenced by begin.
void SoftwareSerial::begin(uint32_t baud, SoftwareSerialConfig config, int8_t rxPin, int8_t txPin)
References begin, m_invert.
void SoftwareSerial::begin(uint32_t baud, SoftwareSerialConfig config, int8_t rxPin)
References begin, m_invert, m_txPin.
void SoftwareSerial::begin(uint32_t baud, SoftwareSerialConfig config=SWSERIAL_8N1)
References begin, m_invert, m_rxPin, m_txPin.
uint32_t SoftwareSerial::baudRate()
References m_bitCycles.
void SoftwareSerial::setTransmitEnablePin(int8_t txEnablePin)
Transmit control pin.
References isValidTxGPIOpin, m_txEnablePin, m_txEnableValid.
void SoftwareSerial::enableIntTx(bool on)
Enable (default) or disable interrupts during tx.
References m_intTxEnabled.
void SoftwareSerial::enableRxGPIOPullup(bool on)
Enable (default) or disable internal rx GPIO pullup.
References m_rxGPIOPullupEnabled, setRxGPIOPullUp.
bool SoftwareSerial::overflow()
References m_overflow.
int SoftwareSerial::available() override
References m_buffer, m_rxValid, rxBits.
int SoftwareSerial::availableForWrite()
References m_txValid.
int SoftwareSerial::peek() override
References m_buffer, m_lastReadParity, m_parityBuffer, m_parityOutPos, m_rxValid, rxBits.
int SoftwareSerial::read() override
References m_buffer, m_lastReadParity, m_parityBuffer, m_parityOutPos, m_rxValid, rxBits.
Referenced by read, readBytes.
bool SoftwareSerial::readParity()
The verbatim parity bit associated with the last successful read() or peek() call
References m_lastReadParity.
int SoftwareSerial::read(uint8_t *buffer, size_t size)
The read(buffer, size) functions are non-blocking, the same as readBytes but without timeout.
References m_buffer, m_parityBuffer, m_parityOutPos, m_rxValid, rxBits.
int SoftwareSerial::read(char *buffer, size_t size)
The read(buffer, size) functions are non-blocking, the same as readBytes but without timeout.
References read.
size_t SoftwareSerial::readBytes(uint8_t *buffer, size_t size) override
The number of bytes read into buffer, up to size. Times out if the limit set through Stream::setTimeout() is reached.
References m_rxValid, read.
Referenced by readBytes.
size_t SoftwareSerial::readBytes(char *buffer, size_t size) override
The number of bytes read into buffer, up to size. Times out if the limit set through Stream::setTimeout() is reached.
References readBytes.
void SoftwareSerial::flush() override
References m_buffer, m_parityBuffer, m_parityInPos, m_parityOutPos, m_rxValid.
size_t SoftwareSerial::write(uint8_t byte) override
Referenced by write.
size_t SoftwareSerial::write(uint8_t byte, SoftwareSerialParity parity)
References write.
size_t SoftwareSerial::write(const uint8_t *buffer, size_t size) override
References m_parityMode, write.
size_t SoftwareSerial::write(const char *buffer, size_t size)
References write.
size_t IRAM_ATTR SoftwareSerial::write(const uint8_t *buffer, size_t size, SoftwareSerialParity parity)
References m_bitCycles, m_dataBits, m_intTxEnabled, m_invert, m_parityMode, m_pduBits, m_periodDuration, m_periodStart, m_rxValid, m_savedPS, m_txEnablePin, m_txEnableValid, m_txValid, rxBits, SWSERIAL_PARITY_EVEN, SWSERIAL_PARITY_MARK, SWSERIAL_PARITY_ODD, SWSERIAL_PARITY_SPACE, writePeriod, xt_rsil, xt_wsr_ps.
size_t SoftwareSerial::write(const char *buffer, size_t size, SoftwareSerialParity parity)
References write.
SoftwareSerial::operator bool() const
References m_oneWire, m_rxPin, m_rxValid, m_txPin, m_txValid.
void SoftwareSerial::enableRx(bool on)
Disable or enable interrupts on the rx pin.
References m_bitCycles, m_invert, m_isrLastCycle, m_pduBits, m_rxCurBit, m_rxEnabled, m_rxPin, m_rxValid, rxBitISR, rxBitSyncISR.
Referenced by begin, enableTx, end, listen, stopListening.
void SoftwareSerial::enableTx(bool on)
One wire control.
References enableRx, m_invert, m_oneWire, m_txPin, m_txValid, setRxGPIOPullUp.
bool SoftwareSerial::listen()
References enableRx.
void SoftwareSerial::end()
References enableRx, m_buffer, m_isrBuffer, m_parityBuffer, m_txValid.
Referenced by ~SoftwareSerial.
bool SoftwareSerial::isListening()
References m_rxEnabled.
bool SoftwareSerial::stopListening()
References enableRx.
void SoftwareSerial::onReceive(Delegate< void(int available), void * > handler)
Set an event handler for received data.
References receiveHandler.
void SoftwareSerial::perform_work()
Run the internal processing and event engine. Can be iteratively called from loop, or otherwise scheduled.
References m_buffer, m_rxValid, receiveHandler, rxBits.
static bool SoftwareSerial::parityEven(uint8_t byte)
The calculated bit for even parity of the parameter byte
static bool SoftwareSerial::parityOdd(uint8_t byte)
The calculated bit for odd parity of the parameter byte
void IRAM_ATTR SoftwareSerial::preciseDelay(bool sync)
References m_intTxEnabled, m_periodDuration, m_periodStart, m_savedPS, xt_rsil, xt_wsr_ps.
Referenced by writePeriod.
void IRAM_ATTR SoftwareSerial::writePeriod(uint32_t dutyCycle, uint32_t offCycle, bool withStopBit)
References m_invert, m_periodDuration, m_txPin, preciseDelay.
Referenced by write.
bool SoftwareSerial::isValidGPIOpin(int8_t pin)
Referenced by isValidRxGPIOpin, isValidTxGPIOpin.
bool SoftwareSerial::isValidRxGPIOpin(int8_t pin)
References isValidGPIOpin.
Referenced by begin.
bool SoftwareSerial::isValidTxGPIOpin(int8_t pin)
References isValidGPIOpin.
Referenced by begin, setTransmitEnablePin.
bool SoftwareSerial::hasRxGPIOPullUp(int8_t pin)
Referenced by setRxGPIOPullUp.
void SoftwareSerial::setRxGPIOPullUp()
References hasRxGPIOPullUp, m_rxGPIOPullupEnabled, m_rxPin, m_rxValid.
Referenced by begin, enableRxGPIOPullup, enableTx.
void SoftwareSerial::rxBits()
References std::atomic< T >::load, m_bitCycles, m_invert, m_isrBuffer, m_isrBufferForEachDel, m_isrLastCycle, m_isrOverflow, m_overflow, m_pduBits, m_rxCurBit, m_stopBits, std::atomic< T >::store.
Referenced by available, peek, perform_work, read, write.
void SoftwareSerial::rxBits(const uint32_t &isrCycle)
References BYTE_ALL_BITS_SET, m_bitCycles, m_buffer, m_dataBits, m_invert, m_isrLastCycle, m_overflow, m_parityBuffer, m_parityInPos, m_parityMode, m_pduBits, m_rxCurBit, m_rxCurByte, m_rxCurParity, m_stopBits.
void IRAM_ATTR SoftwareSerial::rxBitISR(SoftwareSerial *self)
Referenced by enableRx.
void IRAM_ATTR SoftwareSerial::rxBitSyncISR(SoftwareSerial *self)
Referenced by enableRx.