VectorFloat
float VectorFloat::x
Referenced by getMagnitude, getNormalized, getRotated, normalize, rotate, VectorFloat.
float VectorFloat::y
Referenced by getMagnitude, getNormalized, getRotated, normalize, rotate, VectorFloat.
float VectorFloat::z
Referenced by MPU6050_9Axis_MotionApps41::dmpGetYawPitchRoll, getMagnitude, getNormalized, getRotated, normalize, rotate, VectorFloat.
VectorFloat::VectorFloat()
References x, y, z.
VectorFloat::VectorFloat(float nx, float ny, float nz)
References x, y, z.
float VectorFloat::getMagnitude()
References x, y, z.
Referenced by normalize.
void VectorFloat::normalize()
References getMagnitude, x, y, z.
Referenced by getNormalized.
VectorFloat VectorFloat::getNormalized()
References normalize, x, y, z.
void VectorFloat::rotate(Quaternion *q)
References Quaternion::getProduct, Quaternion::x, x, Quaternion::y, y, Quaternion::z, z.
Referenced by getRotated.
VectorFloat VectorFloat::getRotated(Quaternion *q)
References rotate, x, y, z.