VectorInt16
int16_t VectorInt16::x
Referenced by getMagnitude, getNormalized, getRotated, MPU::jsonResult, normalize, rotate, MPU::toString, VectorInt16.
int16_t VectorInt16::y
Referenced by getMagnitude, getNormalized, getRotated, MPU::jsonResult, normalize, rotate, MPU::toString, VectorInt16.
int16_t VectorInt16::z
Referenced by getMagnitude, getNormalized, getRotated, MPU::jsonResult, normalize, rotate, MPU::toString, VectorInt16.
VectorInt16::VectorInt16()
References x, y, z.
VectorInt16::VectorInt16(int16_t nx, int16_t ny, int16_t nz)
References x, y, z.
float VectorInt16::getMagnitude()
References x, y, z.
Referenced by normalize.
void VectorInt16::normalize()
References getMagnitude, x, y, z.
Referenced by getNormalized.
VectorInt16 VectorInt16::getNormalized()
References normalize, x, y, z.
void VectorInt16::rotate(Quaternion *q)
References Quaternion::getProduct, Quaternion::x, x, Quaternion::y, y, Quaternion::z, z.
Referenced by getRotated.
VectorInt16 VectorInt16::getRotated(Quaternion *q)
References rotate, x, y, z.