Servo_ESP32
const int Servo_ESP32::MIN_ANGLE
Referenced by _resetFields.
const int Servo_ESP32::MAX_ANGLE
Referenced by _resetFields.
const int Servo_ESP32::MIN_PULSE_WIDTH
Referenced by _resetFields.
const int Servo_ESP32::MAX_PULSE_WIDTH
Referenced by _resetFields.
const int Servo_ESP32::MAX_COMPARE
Referenced by _dutyToUs, _usToDuty.
const int Servo_ESP32::TAU_MSEC
const int Servo_ESP32::TAU_USEC
Referenced by _dutyToUs, _usToDuty.
const int Servo_ESP32::CHANNEL_MAX_NUM
Referenced by attach.
int Servo_ESP32::channel_next_free
Referenced by attach, detach.
const int Servo_ESP32::CHANNEL_NOT_ATTACHED
Referenced by _resetFields, attach.
const int Servo_ESP32::PIN_NOT_ATTACHED
Referenced by _resetFields, attached.
int Servo_ESP32::_pin
Referenced by _resetFields, attach, attached, attachedPin, detach.
int Servo_ESP32::_pulseWidthDuty
Referenced by _resetFields, writeMicroseconds.
int Servo_ESP32::_channel
Referenced by _resetFields, attach, detach, readMicroseconds, writeMicroseconds.
int Servo_ESP32::_min
int Servo_ESP32::_max
int Servo_ESP32::_minPulseWidth
Referenced by _angleToUs, _resetFields, _usToAngle, attach, writeMicroseconds.
int Servo_ESP32::_maxPulseWidth
Referenced by _angleToUs, _resetFields, _usToAngle, attach, writeMicroseconds.
int Servo_ESP32::_minAngle
Referenced by _angleToUs, _resetFields, _usToAngle, attach, write.
int Servo_ESP32::_maxAngle
Referenced by _angleToUs, _resetFields, _usToAngle, attach, write.
Servo_ESP32::Servo_ESP32()
Construct a new Servo instance.
The new instance will not be attached to any pin.
References _resetFields.
Servo_ESP32::~Servo_ESP32()
Destruct a Servo instance.
Call _() and detach().
References detach.
bool Servo_ESP32::attach(int pin, int channel=CHANNEL_NOT_ATTACHED, int minAngle=MIN_ANGLE, int maxAngle=MAX_ANGLE, int minPulseWidth=MIN_PULSE_WIDTH, int maxPulseWidth=MAX_PULSE_WIDTH)
Associate this instance with a servomotor whose input is connected to pin.
pin Pin connected to the servo pulse wave input. This pin must be capable of PWM output (all ESP32 pins). channel Channel which is set to ESP32 Arduino function ledcSetup(). Channel must be number between 0 - 15. It is possible to use automatic channel setup with constant Servo::CHANNEL_NOT_ATTACHED. minAngle Target angle (in degrees) associated with minPulseWidth. Defaults to MIN_ANGLE = 0. maxAngle Target angle (in degrees) associated with maxPulseWidth. Defaults to MAX_ANGLE = 180. minPulseWidth Minimum pulse width to write to pin, in microseconds. This will be associated with a minAngle degree angle. Defaults to MIN_PULSE_WIDTH = 544. maxPulseWidth Maximum pulse width to write to pin, in microseconds. This will be associated with a maxAngle degree angle. Defaults to MAX_PULSE_WIDTH = 2400. May set pinMode(pin, PWM).true if successful, false when pin doesn't support PWM.
References _channel, _maxAngle, _maxPulseWidth, _minAngle, _minPulseWidth, _pin, CHANNEL_MAX_NUM, channel_next_free, CHANNEL_NOT_ATTACHED.
Referenced by ServoMotor::init.
bool Servo_ESP32::detach()
Stop driving the servo pulse train.
If not currently attached to a motor, this function has no effect.true if this call did anything, false otherwise.
References _channel, _pin, attached, channel_next_free.
Referenced by ~Servo_ESP32.
void Servo_ESP32::write(int degrees)
Set the servomotor target angle.
angle Target angle, in degrees. If the target angle is outside the range specified at attach() time, it will be clamped to lie in that range. Servo::attach()
References _angleToUs, _maxAngle, _minAngle, writeMicroseconds.
Referenced by ServoMotor::move.
void Servo_ESP32::writeMicroseconds(int pulseUs)
Set the pulse width, in microseconds.
pulseWidth Pulse width to send to the servomotor, in microseconds. If outside of the range specified at attach() time, it is clamped to lie in that range. Servo::attach()
References _channel, _maxPulseWidth, _minPulseWidth, _pulseWidthDuty, _usToDuty, attached.
Referenced by write.
int Servo_ESP32::read()
Get the servomotor's target angle, in degrees. This will lie inside the range specified at attach() time.Servo::attach()
References _usToAngle, readMicroseconds.
Referenced by ServoMotor::get_currentPosition.
int Servo_ESP32::readMicroseconds()
Get the current pulse width, in microseconds. This will lie within the range specified at attach() time.Servo::attach()
References _channel, _dutyToUs, attached.
Referenced by read.
bool Servo_ESP32::attached() const
Check if this instance is attached to a servo.
true if this instance is attached to a servo, false otherwise. Servo::attachedPin()
References _pin, PIN_NOT_ATTACHED.
Referenced by detach, readMicroseconds, writeMicroseconds.
int Servo_ESP32::attachedPin() const
Get the pin this instance is attached to.
Pin number if currently attached to a pin, PIN_NOT_ATTACHED otherwise. Servo::attach()
References _pin.
void Servo_ESP32::_resetFields(void)
References _channel, _maxAngle, _maxPulseWidth, _minAngle, _minPulseWidth, _pin, _pulseWidthDuty, CHANNEL_NOT_ATTACHED, MAX_ANGLE, MAX_PULSE_WIDTH, MIN_ANGLE, MIN_PULSE_WIDTH, PIN_NOT_ATTACHED.
Referenced by Servo_ESP32.
int Servo_ESP32::_usToDuty(int us)
References MAX_COMPARE, TAU_USEC.
Referenced by writeMicroseconds.
int Servo_ESP32::_dutyToUs(int duty)
References MAX_COMPARE, TAU_USEC.
Referenced by readMicroseconds.
int Servo_ESP32::_usToAngle(int us)
References _maxAngle, _maxPulseWidth, _minAngle, _minPulseWidth.
Referenced by read.
int Servo_ESP32::_angleToUs(int angle)
References _maxAngle, _maxPulseWidth, _minAngle, _minPulseWidth.
Referenced by write.