MiniJoystick
size_t MiniJoystick::button
Referenced by asciiResult, getButton, MiniJoystick, toString.
Axis MiniJoystick::x
Referenced by getX, init, MiniJoystick.
Axis MiniJoystick::y
Referenced by getY, init, MiniJoystick.
bool MiniJoystick::buttonUnpushState
MiniJoystick::MiniJoystick(char *name, size_t x, size_t y, size_t button)
References button, MiniJoystick::Axis::leg, MiniJoystick::Axis::max, MiniJoystick::Axis::mid, MiniJoystick::Axis::min, Sensor::name, x, y.
bool MiniJoystick::init()
References MiniJoystick::Axis::leg, MiniJoystick::Axis::mid, updateRange, x, y.
String MiniJoystick::asciiResult()
References button, getX, getY.
String MiniJoystick::toString()
References button, getX, getY.
DynamicJsonDocument MiniJoystick::jsonResult()
References getX, getY.
int MiniJoystick::getX()
References axisValue, x.
Referenced by asciiResult, jsonResult, toString.
int MiniJoystick::getY()
References axisValue, y.
Referenced by asciiResult, jsonResult, toString.
bool MiniJoystick::getButton()
References button.
int MiniJoystick::axisValue(Axis *axis)
References MiniJoystick::Axis::leg, MiniJoystick::Axis::max, MiniJoystick::Axis::mid, MiniJoystick::Axis::min, normalize, updateRange.
Referenced by getX, getY.
void MiniJoystick::updateRange(Axis *axis, int input)
References MiniJoystick::Axis::max, MiniJoystick::Axis::min.
Referenced by axisValue, init.