MPU6050_9Axis_MotionApps41
uint8_t* MPU6050_9Axis_MotionApps41::dmpPacketBuffer
Referenced by dmpGetAccel, dmpGetGyro, dmpGetMag, dmpGetQuaternion.
uint16_t MPU6050_9Axis_MotionApps41::dmpPacketSize
Referenced by dmpGetFIFOPacketSize, dmpInitialize, dmpReadAndProcessFIFOPacket.
MPU6050_9Axis_MotionApps41::MPU6050_9Axis_MotionApps41(uint8_t address=MPU6050_DEFAULT_ADDRESS, void *wireObj=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpInitialize()
References MPU6050_Base::buffer, DEBUG_PRINT, DEBUG_PRINTF, DEBUG_PRINTLN, DEBUG_PRINTLNF, MPU6050_Base::devAddr, dmpPacketSize, MPU6050_Base::getFIFOBytes, MPU6050_Base::getFIFOCount, MPU6050_Base::getIntStatus, MPU6050_Base::getOTPBankValid, MPU6050_Base::getXGyroOffset, MPU6050_Base::getYGyroOffset, MPU6050_Base::getZGyroOffset, MPU6050_CLOCK_PLL_ZGYRO, MPU6050_DLPF_BW_42, MPU6050_DMP_CODE_SIZE, MPU6050_DMP_CONFIG_SIZE, MPU6050_EXT_SYNC_TEMP_OUT_L, MPU6050_GYRO_FS_2000, MPU6050_INTERRUPT_DMP_INT_BIT, MPU6050_INTERRUPT_FIFO_OFLOW_BIT, MPU6050_RA_ACCEL_CONFIG, MPU6050_RA_I2C_MST_DELAY_CTRL, MPU6050_RA_I2C_SLV0_ADDR, MPU6050_RA_I2C_SLV0_CTRL, MPU6050_RA_I2C_SLV0_REG, MPU6050_RA_I2C_SLV2_ADDR, MPU6050_RA_I2C_SLV2_CTRL, MPU6050_RA_I2C_SLV2_DO, MPU6050_RA_I2C_SLV2_REG, MPU6050_RA_I2C_SLV4_CTRL, MPU6050_RA_INT_PIN_CFG, MPU6050_RA_PWR_MGMT_2, MPU6050_RA_USER_CTRL, I2Cdev::readByte, I2Cdev::readBytes, MPU6050_Base::readMemoryBlock, MPU6050_Base::readMemoryByte, I2Cdev::readTimeout, MPU6050_Base::reset, MPU6050_Base::resetFIFO, MPU6050_Base::setClockSource, MPU6050_Base::setDLPFMode, MPU6050_Base::setDMPConfig1, MPU6050_Base::setDMPConfig2, MPU6050_Base::setDMPEnabled, MPU6050_Base::setExternalFrameSync, MPU6050_Base::setFullScaleGyroRange, MPU6050_Base::setIntEnabled, MPU6050_Base::setMemoryBank, MPU6050_Base::setMemoryStartAddress, MPU6050_Base::setMotionDetectionDuration, MPU6050_Base::setMotionDetectionThreshold, MPU6050_Base::setOTPBankValid, MPU6050_Base::setRate, MPU6050_Base::setSleepEnabled, MPU6050_Base::setXGyroOffsetTC, MPU6050_Base::setYGyroOffsetTC, MPU6050_Base::setZeroMotionDetectionDuration, MPU6050_Base::setZeroMotionDetectionThreshold, MPU6050_Base::setZGyroOffsetTC, MPU6050_Base::wireObj, I2Cdev::writeByte, MPU6050_Base::writeMemoryBlock, MPU6050_Base::writeProgDMPConfigurationSet, MPU6050_Base::writeProgMemoryBlock.
bool MPU6050_9Axis_MotionApps41::dmpPacketAvailable()
References dmpGetFIFOPacketSize, MPU6050_Base::getFIFOCount.
uint8_t MPU6050_9Axis_MotionApps41::dmpSetFIFORate(uint8_t fifoRate)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetFIFORate()
uint8_t MPU6050_9Axis_MotionApps41::dmpGetSampleStepSizeMS()
uint8_t MPU6050_9Axis_MotionApps41::dmpGetSampleFrequency()
int32_t MPU6050_9Axis_MotionApps41::dmpDecodeTemperature(int8_t tempReg)
uint8_t MPU6050_9Axis_MotionApps41::dmpRunFIFORateProcesses()
uint8_t MPU6050_9Axis_MotionApps41::dmpSendQuaternion(uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendGyro(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendAccel(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendLinearAccel(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendLinearAccelInWorld(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendControlData(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendSensorData(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendExternalSensorData(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendGravity(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendPacketNumber(uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendQuantizedAccel(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpSendEIS(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetAccel(int32_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetAccel(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetAccel(VectorInt16 *v, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuaternion(int32_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
Referenced by dmpGetGravity, dmpGetQuaternion.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuaternion(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuaternion(Quaternion *q, const uint8_t *packet=0)
References dmpGetQuaternion.
uint8_t MPU6050_9Axis_MotionApps41::dmpGet6AxisQuaternion(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGet6AxisQuaternion(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGet6AxisQuaternion(Quaternion *q, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetRelativeQuaternion(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetRelativeQuaternion(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetRelativeQuaternion(Quaternion *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyro(int32_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyro(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyro(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetMag(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_9Axis_MotionApps41::dmpSetLinearAccelFilterCoefficient(float coef)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccel(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccel(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccel(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccel(VectorInt16 *v, VectorInt16 *vRaw, VectorFloat *gravity)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccelInWorld(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccelInWorld(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccelInWorld(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetLinearAccelInWorld(VectorInt16 *v, VectorInt16 *vReal, Quaternion *q)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyroAndAccelSensor(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyroAndAccelSensor(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyroAndAccelSensor(VectorInt16 *g, VectorInt16 *a, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyroSensor(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyroSensor(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGyroSensor(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetControlData(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetTemperature(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGravity(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGravity(int16_t *data, const uint8_t *packet=0)
References dmpGetQuaternion.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGravity(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetGravity(VectorFloat *v, Quaternion *q)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetUnquantizedAccel(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetUnquantizedAccel(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetUnquantizedAccel(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuantizedAccel(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuantizedAccel(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuantizedAccel(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetExternalSensorData(int32_t *data, uint16_t size, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetEIS(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetEuler(float *data, Quaternion *q)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetYawPitchRoll(float *data, Quaternion *q, VectorFloat *gravity)
References VectorFloat::z.
uint8_t MPU6050_9Axis_MotionApps41::dmpGetAccelFloat(float *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpGetQuaternionFloat(float *data, const uint8_t *packet=0)
uint8_t MPU6050_9Axis_MotionApps41::dmpProcessFIFOPacket(const unsigned char *dmpData)
Referenced by dmpReadAndProcessFIFOPacket.
uint8_t MPU6050_9Axis_MotionApps41::dmpReadAndProcessFIFOPacket(uint8_t numPackets, uint8_t *processed=NULL)
References dmpPacketSize, dmpProcessFIFOPacket, MPU6050_Base::getFIFOBytes.
uint8_t MPU6050_9Axis_MotionApps41::dmpSetFIFOProcessedCallback(void(*func)(void))
uint8_t MPU6050_9Axis_MotionApps41::dmpInitFIFOParam()
uint8_t MPU6050_9Axis_MotionApps41::dmpCloseFIFO()
uint8_t MPU6050_9Axis_MotionApps41::dmpSetGyroDataSource(uint8_t source)
uint8_t MPU6050_9Axis_MotionApps41::dmpDecodeQuantizedAccel()
uint32_t MPU6050_9Axis_MotionApps41::dmpGetGyroSumOfSquare()
uint32_t MPU6050_9Axis_MotionApps41::dmpGetAccelSumOfSquare()
void MPU6050_9Axis_MotionApps41::dmpOverrideQuaternion(long *q)
uint16_t MPU6050_9Axis_MotionApps41::dmpGetFIFOPacketSize()
References dmpPacketSize.
Referenced by dmpPacketAvailable.