MPU6050_6Axis_MotionApps20
uint8_t* MPU6050_6Axis_MotionApps20::dmpPacketBuffer
Referenced by dmpGetAccel, dmpGetGyro, dmpGetQuaternion.
uint16_t MPU6050_6Axis_MotionApps20::dmpPacketSize
Referenced by dmpGetCurrentFIFOPacket, dmpGetFIFOPacketSize, dmpInitialize, dmpReadAndProcessFIFOPacket.
MPU6050_6Axis_MotionApps20::MPU6050_6Axis_MotionApps20(uint8_t address=MPU6050_DEFAULT_ADDRESS, void *wireObj=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpInitialize()
References DEBUG_PRINT, DEBUG_PRINTLN, dmpPacketSize, MPU6050_Base::getIntStatus, MPU6050_Base::getOTPBankValid, MPU6050_CLOCK_PLL_ZGYRO, MPU6050_DLPF_BW_42, MPU6050_DMP_CODE_SIZE, MPU6050_DMP_FIFO_RATE_DIVISOR, MPU6050_EXT_SYNC_TEMP_OUT_L, MPU6050_GYRO_FS_2000, MPU6050_INTERRUPT_DMP_INT_BIT, MPU6050_INTERRUPT_FIFO_OFLOW_BIT, MPU6050_Base::readMemoryByte, MPU6050_Base::reset, MPU6050_Base::resetDMP, MPU6050_Base::resetFIFO, MPU6050_Base::resetI2CMaster, MPU6050_Base::setClockSource, MPU6050_Base::setDLPFMode, MPU6050_Base::setDMPConfig1, MPU6050_Base::setDMPConfig2, MPU6050_Base::setDMPEnabled, MPU6050_Base::setExternalFrameSync, MPU6050_Base::setFIFOEnabled, MPU6050_Base::setFullScaleGyroRange, MPU6050_Base::setI2CMasterModeEnabled, MPU6050_Base::setIntEnabled, MPU6050_Base::setMemoryBank, MPU6050_Base::setMemoryStartAddress, MPU6050_Base::setMotionDetectionDuration, MPU6050_Base::setMotionDetectionThreshold, MPU6050_Base::setOTPBankValid, MPU6050_Base::setRate, MPU6050_Base::setSlaveAddress, MPU6050_Base::setSleepEnabled, MPU6050_Base::setZeroMotionDetectionDuration, MPU6050_Base::setZeroMotionDetectionThreshold, MPU6050_Base::writeMemoryBlock, MPU6050_Base::writeProgMemoryBlock.
bool MPU6050_6Axis_MotionApps20::dmpPacketAvailable()
References dmpGetFIFOPacketSize, MPU6050_Base::getFIFOCount.
uint8_t MPU6050_6Axis_MotionApps20::dmpSetFIFORate(uint8_t fifoRate)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetFIFORate()
uint8_t MPU6050_6Axis_MotionApps20::dmpGetSampleStepSizeMS()
uint8_t MPU6050_6Axis_MotionApps20::dmpGetSampleFrequency()
int32_t MPU6050_6Axis_MotionApps20::dmpDecodeTemperature(int8_t tempReg)
uint8_t MPU6050_6Axis_MotionApps20::dmpRunFIFORateProcesses()
uint8_t MPU6050_6Axis_MotionApps20::dmpSendQuaternion(uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendGyro(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendAccel(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendLinearAccel(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendLinearAccelInWorld(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendControlData(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendSensorData(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendExternalSensorData(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendGravity(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendPacketNumber(uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendQuantizedAccel(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpSendEIS(uint_fast16_t elements, uint_fast16_t accuracy)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetAccel(int32_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetAccel(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetAccel(VectorInt16 *v, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuaternion(int32_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
Referenced by dmpGetGravity, dmpGetQuaternion.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuaternion(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuaternion(Quaternion *q, const uint8_t *packet=0)
References dmpGetQuaternion.
uint8_t MPU6050_6Axis_MotionApps20::dmpGet6AxisQuaternion(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGet6AxisQuaternion(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGet6AxisQuaternion(Quaternion *q, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetRelativeQuaternion(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetRelativeQuaternion(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetRelativeQuaternion(Quaternion *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyro(int32_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyro(int16_t *data, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyro(VectorInt16 *v, const uint8_t *packet=0)
References dmpPacketBuffer.
uint8_t MPU6050_6Axis_MotionApps20::dmpSetLinearAccelFilterCoefficient(float coef)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccel(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccel(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccel(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccel(VectorInt16 *v, VectorInt16 *vRaw, VectorFloat *gravity)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccelInWorld(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccelInWorld(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccelInWorld(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetLinearAccelInWorld(VectorInt16 *v, VectorInt16 *vReal, Quaternion *q)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyroAndAccelSensor(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyroAndAccelSensor(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyroAndAccelSensor(VectorInt16 *g, VectorInt16 *a, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyroSensor(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyroSensor(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGyroSensor(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetControlData(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetTemperature(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGravity(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGravity(int16_t *data, const uint8_t *packet=0)
References dmpGetQuaternion.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGravity(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetGravity(VectorFloat *v, Quaternion *q)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetUnquantizedAccel(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetUnquantizedAccel(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetUnquantizedAccel(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuantizedAccel(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuantizedAccel(int16_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuantizedAccel(VectorInt16 *v, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetExternalSensorData(int32_t *data, uint16_t size, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetEIS(int32_t *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetEuler(float *data, Quaternion *q)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetYawPitchRoll(float *data, Quaternion *q, VectorFloat *gravity)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetAccelFloat(float *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpGetQuaternionFloat(float *data, const uint8_t *packet=0)
uint8_t MPU6050_6Axis_MotionApps20::dmpProcessFIFOPacket(const unsigned char *dmpData)
Referenced by dmpReadAndProcessFIFOPacket.
uint8_t MPU6050_6Axis_MotionApps20::dmpReadAndProcessFIFOPacket(uint8_t numPackets, uint8_t *processed=NULL)
References dmpPacketSize, dmpProcessFIFOPacket, MPU6050_Base::getFIFOBytes.
uint8_t MPU6050_6Axis_MotionApps20::dmpSetFIFOProcessedCallback(void(*func)(void))
uint8_t MPU6050_6Axis_MotionApps20::dmpInitFIFOParam()
uint8_t MPU6050_6Axis_MotionApps20::dmpCloseFIFO()
uint8_t MPU6050_6Axis_MotionApps20::dmpSetGyroDataSource(uint8_t source)
uint8_t MPU6050_6Axis_MotionApps20::dmpDecodeQuantizedAccel()
uint32_t MPU6050_6Axis_MotionApps20::dmpGetGyroSumOfSquare()
uint32_t MPU6050_6Axis_MotionApps20::dmpGetAccelSumOfSquare()
void MPU6050_6Axis_MotionApps20::dmpOverrideQuaternion(long *q)
uint16_t MPU6050_6Axis_MotionApps20::dmpGetFIFOPacketSize()
References dmpPacketSize.
Referenced by dmpPacketAvailable.
uint8_t MPU6050_6Axis_MotionApps20::dmpGetCurrentFIFOPacket(uint8_t *data)
References dmpPacketSize, MPU6050_Base::GetCurrentFIFOPacket.