std::atomic
T std::atomic< T >::value
Referenced by std::atomic< bool >::atomic, std::atomic< bool >::load, std::atomic< bool >::store.
std::atomic< T >::atomic()
std::atomic< T >::atomic(T desired)
void std::atomic< T >::store(T desired, std::memory_order=std::memory_order_seq_cst) volatilenoexcept
Referenced by circular_queue< uint32_t, SoftwareSerial * >::circular_queue, circular_queue< uint32_t, SoftwareSerial * >::flush, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator(), delegate::detail::MultiDelegateImpl< Delegate, void, ISQUEUE, QUEUE_CAPACITY >::operator(), delegate::detail::MultiDelegate< Delegate, void(P...), ISQUEUE, QUEUE_CAPACITY >::operator(), delegate::detail::MultiDelegate< Delegate, void(), ISQUEUE, QUEUE_CAPACITY >::operator(), circular_queue< uint32_t, SoftwareSerial * >::operator=, circular_queue< uint32_t, SoftwareSerial * >::push, SoftwareSerial::rxBits.
T std::atomic< T >::load(std::memory_order=std::memory_order_seq_cst) const volatilenoexcept
Referenced by circular_queue< uint32_t, SoftwareSerial * >::available, circular_queue< uint32_t, SoftwareSerial * >::available_for_push, circular_queue< uint32_t, SoftwareSerial * >::flush, delegate::detail::MultiDelegatePImpl< Delegate, R, ISQUEUE, QUEUE_CAPACITY >::operator(), delegate::detail::MultiDelegateImpl< Delegate, void, ISQUEUE, QUEUE_CAPACITY >::operator(), delegate::detail::MultiDelegate< Delegate, void(P...), ISQUEUE, QUEUE_CAPACITY >::operator(), delegate::detail::MultiDelegate< Delegate, void(), ISQUEUE, QUEUE_CAPACITY >::operator(), circular_queue< uint32_t, SoftwareSerial * >::peek, circular_queue< uint32_t, SoftwareSerial * >::push, circular_queue< uint32_t, SoftwareSerial * >::pushpeek, SoftwareSerial::rxBits.