MPU6050_Base
uint8_t MPU6050_Base::devAddr
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, getAcceleration, getAccelerationX, getAccelerationY, getAccelerationZ, getAccelerometerPowerOnDelay, getAccelFIFOEnabled, getAccelXSelfTest, getAccelXSelfTestFactoryTrim, getAccelYSelfTest, getAccelYSelfTestFactoryTrim, getAccelZSelfTest, getAccelZSelfTestFactoryTrim, getAuxVDDIOLevel, getClockOutputEnabled, getClockSource, getDeviceID, getDHPFMode, getDLPFMode, getDMPConfig1, getDMPConfig2, getDMPEnabled, getDMPInt0Status, getDMPInt1Status, getDMPInt2Status, getDMPInt3Status, getDMPInt4Status, getDMPInt5Status, getExternalFrameSync, getExternalSensorByte, getExternalSensorDWord, getExternalSensorWord, getExternalShadowDelayEnabled, getFIFOByte, getFIFOBytes, getFIFOCount, getFIFOEnabled, getFreefallDetectionCounterDecrement, getFreefallDetectionDuration, getFreefallDetectionThreshold, getFSyncInterruptEnabled, getFSyncInterruptLevel, getFullScaleAccelRange, getFullScaleGyroRange, getGyroXSelfTestFactoryTrim, getGyroYSelfTestFactoryTrim, getGyroZSelfTestFactoryTrim, getI2CBypassEnabled, getI2CMasterModeEnabled, getIntDataReadyEnabled, getIntDataReadyStatus, getIntDMPEnabled, getIntDMPStatus, getIntEnabled, getInterruptDrive, getInterruptLatch, getInterruptLatchClear, getInterruptMode, getIntFIFOBufferOverflowEnabled, getIntFIFOBufferOverflowStatus, getIntFreefallEnabled, getIntFreefallStatus, getIntI2CMasterEnabled, getIntI2CMasterStatus, getIntMotionEnabled, getIntMotionStatus, getIntPLLReadyEnabled, getIntPLLReadyStatus, getIntStatus, getIntZeroMotionEnabled, getIntZeroMotionStatus, getLostArbitration, getMasterClockSpeed, getMotion6, getMotionDetectionCounterDecrement, getMotionDetectionDuration, getMotionDetectionThreshold, getMotionStatus, getMultiMasterEnabled, getOTPBankValid, getPassthroughStatus, getRate, getRotation, getRotationX, getRotationY, getRotationZ, getSlate4InputByte, getSlave0FIFOEnabled, getSlave0Nack, getSlave1FIFOEnabled, getSlave1Nack, getSlave2FIFOEnabled, getSlave2Nack, getSlave3FIFOEnabled, getSlave3Nack, getSlave4Address, getSlave4Enabled, getSlave4InterruptEnabled, getSlave4IsDone, getSlave4MasterDelay, getSlave4Nack, getSlave4Register, getSlave4WriteMode, getSlaveAddress, getSlaveDataLength, getSlaveDelayEnabled, getSlaveEnabled, getSlaveReadWriteTransitionEnabled, getSlaveRegister, getSlaveWordByteSwap, getSlaveWordGroupOffset, getSlaveWriteMode, getSleepEnabled, getStandbyXAccelEnabled, getStandbyXGyroEnabled, getStandbyYAccelEnabled, getStandbyYGyroEnabled, getStandbyZAccelEnabled, getStandbyZGyroEnabled, getTemperature, getTempFIFOEnabled, getTempSensorEnabled, getWaitForExternalSensorEnabled, getWakeCycleEnabled, getWakeFrequency, getXAccelOffset, getXFineGain, getXGyroFIFOEnabled, getXGyroOffset, getXGyroOffsetTC, getXNegMotionDetected, getXPosMotionDetected, getYAccelOffset, getYFineGain, getYGyroFIFOEnabled, getYGyroOffset, getYGyroOffsetTC, getYNegMotionDetected, getYPosMotionDetected, getZAccelOffset, getZeroMotionDetected, getZeroMotionDetectionDuration, getZeroMotionDetectionThreshold, getZFineGain, getZGyroFIFOEnabled, getZGyroOffset, getZGyroOffsetTC, getZNegMotionDetected, getZPosMotionDetected, PID, PrintActiveOffsets, readMemoryBlock, readMemoryByte, reset, resetAccelerometerPath, resetDMP, resetFIFO, resetGyroscopePath, resetI2CMaster, resetSensors, resetTemperaturePath, setAccelerometerPowerOnDelay, setAccelFIFOEnabled, setAccelXSelfTest, setAccelYSelfTest, setAccelZSelfTest, setAuxVDDIOLevel, setClockOutputEnabled, setClockSource, setDeviceID, setDHPFMode, setDLPFMode, setDMPConfig1, setDMPConfig2, setDMPEnabled, setExternalFrameSync, setExternalShadowDelayEnabled, setFIFOByte, setFIFOEnabled, setFreefallDetectionCounterDecrement, setFreefallDetectionDuration, setFreefallDetectionThreshold, setFSyncInterruptEnabled, setFSyncInterruptLevel, setFullScaleAccelRange, setFullScaleGyroRange, setI2CBypassEnabled, setI2CMasterModeEnabled, setIntDataReadyEnabled, setIntDMPEnabled, setIntEnabled, setInterruptDrive, setInterruptLatch, setInterruptLatchClear, setInterruptMode, setIntFIFOBufferOverflowEnabled, setIntFreefallEnabled, setIntI2CMasterEnabled, setIntMotionEnabled, setIntPLLReadyEnabled, setIntZeroMotionEnabled, setMasterClockSpeed, setMemoryBank, setMemoryStartAddress, setMotionDetectionCounterDecrement, setMotionDetectionDuration, setMotionDetectionThreshold, setMultiMasterEnabled, setOTPBankValid, setRate, setSlave0FIFOEnabled, setSlave1FIFOEnabled, setSlave2FIFOEnabled, setSlave3FIFOEnabled, setSlave4Address, setSlave4Enabled, setSlave4InterruptEnabled, setSlave4MasterDelay, setSlave4OutputByte, setSlave4Register, setSlave4WriteMode, setSlaveAddress, setSlaveDataLength, setSlaveDelayEnabled, setSlaveEnabled, setSlaveOutputByte, setSlaveReadWriteTransitionEnabled, setSlaveRegister, setSlaveWordByteSwap, setSlaveWordGroupOffset, setSlaveWriteMode, setSleepEnabled, setStandbyXAccelEnabled, setStandbyXGyroEnabled, setStandbyYAccelEnabled, setStandbyYGyroEnabled, setStandbyZAccelEnabled, setStandbyZGyroEnabled, setTempFIFOEnabled, setTempSensorEnabled, setWaitForExternalSensorEnabled, setWakeCycleEnabled, setWakeFrequency, setXAccelOffset, setXFineGain, setXGyroFIFOEnabled, setXGyroOffset, setXGyroOffsetTC, setYAccelOffset, setYFineGain, setYGyroFIFOEnabled, setYGyroOffset, setYGyroOffsetTC, setZAccelOffset, setZeroMotionDetectionDuration, setZeroMotionDetectionThreshold, setZFineGain, setZGyroFIFOEnabled, setZGyroOffset, setZGyroOffsetTC, switchSPIEnabled, writeDMPConfigurationSet, writeMemoryBlock, writeMemoryByte.
void* MPU6050_Base::wireObj
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, getAcceleration, getAccelerationX, getAccelerationY, getAccelerationZ, getAccelerometerPowerOnDelay, getAccelFIFOEnabled, getAccelXSelfTest, getAccelXSelfTestFactoryTrim, getAccelYSelfTest, getAccelYSelfTestFactoryTrim, getAccelZSelfTest, getAccelZSelfTestFactoryTrim, getAuxVDDIOLevel, getClockOutputEnabled, getClockSource, getDeviceID, getDHPFMode, getDLPFMode, getDMPConfig1, getDMPConfig2, getDMPEnabled, getDMPInt0Status, getDMPInt1Status, getDMPInt2Status, getDMPInt3Status, getDMPInt4Status, getDMPInt5Status, getExternalFrameSync, getExternalSensorByte, getExternalSensorDWord, getExternalSensorWord, getExternalShadowDelayEnabled, getFIFOByte, getFIFOBytes, getFIFOCount, getFIFOEnabled, getFreefallDetectionCounterDecrement, getFreefallDetectionDuration, getFreefallDetectionThreshold, getFSyncInterruptEnabled, getFSyncInterruptLevel, getFullScaleAccelRange, getFullScaleGyroRange, getGyroXSelfTestFactoryTrim, getGyroYSelfTestFactoryTrim, getGyroZSelfTestFactoryTrim, getI2CBypassEnabled, getI2CMasterModeEnabled, getIntDataReadyEnabled, getIntDataReadyStatus, getIntDMPEnabled, getIntDMPStatus, getIntEnabled, getInterruptDrive, getInterruptLatch, getInterruptLatchClear, getInterruptMode, getIntFIFOBufferOverflowEnabled, getIntFIFOBufferOverflowStatus, getIntFreefallEnabled, getIntFreefallStatus, getIntI2CMasterEnabled, getIntI2CMasterStatus, getIntMotionEnabled, getIntMotionStatus, getIntPLLReadyEnabled, getIntPLLReadyStatus, getIntStatus, getIntZeroMotionEnabled, getIntZeroMotionStatus, getLostArbitration, getMasterClockSpeed, getMotion6, getMotionDetectionCounterDecrement, getMotionDetectionDuration, getMotionDetectionThreshold, getMotionStatus, getMultiMasterEnabled, getOTPBankValid, getPassthroughStatus, getRate, getRotation, getRotationX, getRotationY, getRotationZ, getSlate4InputByte, getSlave0FIFOEnabled, getSlave0Nack, getSlave1FIFOEnabled, getSlave1Nack, getSlave2FIFOEnabled, getSlave2Nack, getSlave3FIFOEnabled, getSlave3Nack, getSlave4Address, getSlave4Enabled, getSlave4InterruptEnabled, getSlave4IsDone, getSlave4MasterDelay, getSlave4Nack, getSlave4Register, getSlave4WriteMode, getSlaveAddress, getSlaveDataLength, getSlaveDelayEnabled, getSlaveEnabled, getSlaveReadWriteTransitionEnabled, getSlaveRegister, getSlaveWordByteSwap, getSlaveWordGroupOffset, getSlaveWriteMode, getSleepEnabled, getStandbyXAccelEnabled, getStandbyXGyroEnabled, getStandbyYAccelEnabled, getStandbyYGyroEnabled, getStandbyZAccelEnabled, getStandbyZGyroEnabled, getTemperature, getTempFIFOEnabled, getTempSensorEnabled, getWaitForExternalSensorEnabled, getWakeCycleEnabled, getWakeFrequency, getXAccelOffset, getXFineGain, getXGyroFIFOEnabled, getXGyroOffset, getXGyroOffsetTC, getXNegMotionDetected, getXPosMotionDetected, getYAccelOffset, getYFineGain, getYGyroFIFOEnabled, getYGyroOffset, getYGyroOffsetTC, getYNegMotionDetected, getYPosMotionDetected, getZAccelOffset, getZeroMotionDetected, getZeroMotionDetectionDuration, getZeroMotionDetectionThreshold, getZFineGain, getZGyroFIFOEnabled, getZGyroOffset, getZGyroOffsetTC, getZNegMotionDetected, getZPosMotionDetected, PID, PrintActiveOffsets, readMemoryBlock, readMemoryByte, reset, resetAccelerometerPath, resetDMP, resetFIFO, resetGyroscopePath, resetI2CMaster, resetSensors, resetTemperaturePath, setAccelerometerPowerOnDelay, setAccelFIFOEnabled, setAccelXSelfTest, setAccelYSelfTest, setAccelZSelfTest, setAuxVDDIOLevel, setClockOutputEnabled, setClockSource, setDeviceID, setDHPFMode, setDLPFMode, setDMPConfig1, setDMPConfig2, setDMPEnabled, setExternalFrameSync, setExternalShadowDelayEnabled, setFIFOByte, setFIFOEnabled, setFreefallDetectionCounterDecrement, setFreefallDetectionDuration, setFreefallDetectionThreshold, setFSyncInterruptEnabled, setFSyncInterruptLevel, setFullScaleAccelRange, setFullScaleGyroRange, setI2CBypassEnabled, setI2CMasterModeEnabled, setIntDataReadyEnabled, setIntDMPEnabled, setIntEnabled, setInterruptDrive, setInterruptLatch, setInterruptLatchClear, setInterruptMode, setIntFIFOBufferOverflowEnabled, setIntFreefallEnabled, setIntI2CMasterEnabled, setIntMotionEnabled, setIntPLLReadyEnabled, setIntZeroMotionEnabled, setMasterClockSpeed, setMemoryBank, setMemoryStartAddress, setMotionDetectionCounterDecrement, setMotionDetectionDuration, setMotionDetectionThreshold, setMultiMasterEnabled, setOTPBankValid, setRate, setSlave0FIFOEnabled, setSlave1FIFOEnabled, setSlave2FIFOEnabled, setSlave3FIFOEnabled, setSlave4Address, setSlave4Enabled, setSlave4InterruptEnabled, setSlave4MasterDelay, setSlave4OutputByte, setSlave4Register, setSlave4WriteMode, setSlaveAddress, setSlaveDataLength, setSlaveDelayEnabled, setSlaveEnabled, setSlaveOutputByte, setSlaveReadWriteTransitionEnabled, setSlaveRegister, setSlaveWordByteSwap, setSlaveWordGroupOffset, setSlaveWriteMode, setSleepEnabled, setStandbyXAccelEnabled, setStandbyXGyroEnabled, setStandbyYAccelEnabled, setStandbyYGyroEnabled, setStandbyZAccelEnabled, setStandbyZGyroEnabled, setTempFIFOEnabled, setTempSensorEnabled, setWaitForExternalSensorEnabled, setWakeCycleEnabled, setWakeFrequency, setXAccelOffset, setXFineGain, setXGyroFIFOEnabled, setXGyroOffset, setXGyroOffsetTC, setYAccelOffset, setYFineGain, setYGyroFIFOEnabled, setYGyroOffset, setYGyroOffsetTC, setZAccelOffset, setZeroMotionDetectionDuration, setZeroMotionDetectionThreshold, setZFineGain, setZGyroFIFOEnabled, setZGyroOffset, setZGyroOffsetTC, switchSPIEnabled, writeDMPConfigurationSet, writeMemoryBlock, writeMemoryByte.
uint8_t MPU6050_Base::buffer[14][14]
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, getAcceleration, getAccelerationX, getAccelerationY, getAccelerationZ, getAccelerometerPowerOnDelay, getAccelFIFOEnabled, getAccelXSelfTest, getAccelXSelfTestFactoryTrim, getAccelYSelfTest, getAccelYSelfTestFactoryTrim, getAccelZSelfTest, getAccelZSelfTestFactoryTrim, getAuxVDDIOLevel, getClockOutputEnabled, getClockSource, getDeviceID, getDHPFMode, getDLPFMode, getDMPConfig1, getDMPConfig2, getDMPEnabled, getDMPInt0Status, getDMPInt1Status, getDMPInt2Status, getDMPInt3Status, getDMPInt4Status, getDMPInt5Status, getExternalFrameSync, getExternalSensorByte, getExternalSensorDWord, getExternalSensorWord, getExternalShadowDelayEnabled, getFIFOByte, getFIFOCount, getFIFOEnabled, getFreefallDetectionCounterDecrement, getFreefallDetectionDuration, getFreefallDetectionThreshold, getFSyncInterruptEnabled, getFSyncInterruptLevel, getFullScaleAccelRange, getFullScaleGyroRange, getGyroXSelfTestFactoryTrim, getGyroYSelfTestFactoryTrim, getGyroZSelfTestFactoryTrim, getI2CBypassEnabled, getI2CMasterModeEnabled, getIntDataReadyEnabled, getIntDataReadyStatus, getIntDMPEnabled, getIntDMPStatus, getIntEnabled, getInterruptDrive, getInterruptLatch, getInterruptLatchClear, getInterruptMode, getIntFIFOBufferOverflowEnabled, getIntFIFOBufferOverflowStatus, getIntFreefallEnabled, getIntFreefallStatus, getIntI2CMasterEnabled, getIntI2CMasterStatus, getIntMotionEnabled, getIntMotionStatus, getIntPLLReadyEnabled, getIntPLLReadyStatus, getIntStatus, getIntZeroMotionEnabled, getIntZeroMotionStatus, getLostArbitration, getMasterClockSpeed, getMotion6, getMotionDetectionCounterDecrement, getMotionDetectionDuration, getMotionDetectionThreshold, getMotionStatus, getMultiMasterEnabled, getOTPBankValid, getPassthroughStatus, getRate, getRotation, getRotationX, getRotationY, getRotationZ, getSlate4InputByte, getSlave0FIFOEnabled, getSlave0Nack, getSlave1FIFOEnabled, getSlave1Nack, getSlave2FIFOEnabled, getSlave2Nack, getSlave3FIFOEnabled, getSlave3Nack, getSlave4Address, getSlave4Enabled, getSlave4InterruptEnabled, getSlave4IsDone, getSlave4MasterDelay, getSlave4Nack, getSlave4Register, getSlave4WriteMode, getSlaveAddress, getSlaveDataLength, getSlaveDelayEnabled, getSlaveEnabled, getSlaveReadWriteTransitionEnabled, getSlaveRegister, getSlaveWordByteSwap, getSlaveWordGroupOffset, getSlaveWriteMode, getSleepEnabled, getStandbyXAccelEnabled, getStandbyXGyroEnabled, getStandbyYAccelEnabled, getStandbyYGyroEnabled, getStandbyZAccelEnabled, getStandbyZGyroEnabled, getTemperature, getTempFIFOEnabled, getTempSensorEnabled, getWaitForExternalSensorEnabled, getWakeCycleEnabled, getWakeFrequency, getXAccelOffset, getXFineGain, getXGyroFIFOEnabled, getXGyroOffset, getXGyroOffsetTC, getXNegMotionDetected, getXPosMotionDetected, getYAccelOffset, getYFineGain, getYGyroFIFOEnabled, getYGyroOffset, getYGyroOffsetTC, getYNegMotionDetected, getYPosMotionDetected, getZAccelOffset, getZeroMotionDetected, getZeroMotionDetectionDuration, getZeroMotionDetectionThreshold, getZFineGain, getZGyroFIFOEnabled, getZGyroOffset, getZGyroOffsetTC, getZNegMotionDetected, getZPosMotionDetected, readMemoryByte.
uint32_t MPU6050_Base::fifoTimeout
Referenced by getFIFOTimeout, setFIFOTimeout.
MPU6050_Base::MPU6050_Base(uint8_t address=MPU6050_DEFAULT_ADDRESS, void *wireObj=0)
Specific address constructor. address I2C address, uses default I2C address if none is specified MPU6050_DEFAULT_ADDRESS MPU6050_ADDRESS_AD0_LOW MPU6050_ADDRESS_AD0_HIGH
void MPU6050_Base::initialize()
Power on and prepare for general usage. This will activate the device and take it out of sleep mode (which must be done after start-up). This function also sets both the accelerometer and the gyroscope to their most sensitive settings, namely +/- 2g and +/- 250 degrees/sec, and sets the clock source to use the X Gyro for reference, which is slightly better than the default internal clock source.
References MPU6050_ACCEL_FS_2, MPU6050_CLOCK_PLL_XGYRO, MPU6050_GYRO_FS_250, setClockSource, setFullScaleAccelRange, setFullScaleGyroRange, setSleepEnabled.
Referenced by MPU::init.
bool MPU6050_Base::testConnection()
Verify the I2C connection. Make sure the device is connected and responds as expected. True if connection is valid, false otherwise
References getDeviceID.
Referenced by MPU::init.
uint8_t MPU6050_Base::getAuxVDDIOLevel()
Get the auxiliary I2C supply voltage level. When set to 1, the auxiliary I2C bus high logic level is VDD. When cleared to 0, the auxiliary I2C bus high logic level is VLOGIC. This does not apply to the MPU-6000, which does not have a VLOGIC pin. I2C supply voltage level (0=VLOGIC, 1=VDD)
References buffer, devAddr, MPU6050_RA_YG_OFFS_TC, MPU6050_TC_PWR_MODE_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setAuxVDDIOLevel(uint8_t level)
Set the auxiliary I2C supply voltage level. When set to 1, the auxiliary I2C bus high logic level is VDD. When cleared to 0, the auxiliary I2C bus high logic level is VLOGIC. This does not apply to the MPU-6000, which does not have a VLOGIC pin. level I2C supply voltage level (0=VLOGIC, 1=VDD)
References devAddr, MPU6050_RA_YG_OFFS_TC, MPU6050_TC_PWR_MODE_BIT, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getRate()
Get gyroscope output rate divider. The sensor register output, FIFO output, DMP sampling, Motion detection, Zero Motion detection, and Free Fall detection are all based on the Sample Rate. The Sample Rate is generated by dividing the gyroscope output rate by SMPLRT_DIV:Sample Rate = Gyroscope Output Rate / (1 + SMPLRT_DIV)where Gyroscope Output Rate = 8kHz when the DLPF is disabled (DLPF_CFG = 0 or 7), and 1kHz when the DLPF is enabled (see Register 26).Note: The accelerometer output rate is 1kHz. This means that for a Sample Rate greater than 1kHz, the same accelerometer sample may be output to the FIFO, DMP, and sensor registers more than once.For a diagram of the gyroscope and accelerometer signal paths, see Section 8 of the MPU-6000/MPU-6050 Product Specification document.Current sample rate MPU6050_RA_SMPLRT_DIV
References buffer, devAddr, MPU6050_RA_SMPLRT_DIV, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setRate(uint8_t rate)
Set gyroscope sample rate divider. rate New sample rate divider getRate() MPU6050_RA_SMPLRT_DIV
References devAddr, MPU6050_RA_SMPLRT_DIV, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getExternalFrameSync()
Get external FSYNC configuration. Configures the external Frame Synchronization (FSYNC) pin sampling. An external signal connected to the FSYNC pin can be sampled by configuring EXT_SYNC_SET. Signal changes to the FSYNC pin are latched so that short strobes may be captured. The latched FSYNC signal will be sampled at the Sampling Rate, as defined in register 25. After sampling, the latch will reset to the current FSYNC signal state.The sampled value will be reported in place of the least significant bit in a sensor data register determined by the value of EXT_SYNC_SET according to the following table. EXT_SYNC_SET | FSYNC Bit Location -------------+------------------- 0 | Input disabled 1 | TEMP_OUT_L[0] 2 | GYRO_XOUT_L[0] 3 | GYRO_YOUT_L[0] 4 | GYRO_ZOUT_L[0] 5 | ACCEL_XOUT_L[0] 6 | ACCEL_YOUT_L[0] 7 | ACCEL_ZOUT_L[0] FSYNC configuration value
References buffer, devAddr, MPU6050_CFG_EXT_SYNC_SET_BIT, MPU6050_CFG_EXT_SYNC_SET_LENGTH, MPU6050_RA_CONFIG, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setExternalFrameSync(uint8_t sync)
Set external FSYNC configuration. getExternalFrameSync() MPU6050_RA_CONFIG sync New FSYNC configuration value
References devAddr, MPU6050_CFG_EXT_SYNC_SET_BIT, MPU6050_CFG_EXT_SYNC_SET_LENGTH, MPU6050_RA_CONFIG, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getDLPFMode()
Get digital low-pass filter configuration. The DLPF_CFG parameter sets the digital low pass filter configuration. It also determines the internal sampling rate used by the device as shown in the table below.Note: The accelerometer output rate is 1kHz. This means that for a Sample Rate greater than 1kHz, the same accelerometer sample may be output to the FIFO, DMP, and sensor registers more than once. | ACCELEROMETER | GYROSCOPE DLPF_CFG | Bandwidth | Delay | Bandwidth | Delay | Sample Rate ---------+-----------+--------+-----------+--------+------------- 0 | 260Hz | 0ms | 256Hz | 0.98ms | 8kHz 1 | 184Hz | 2.0ms | 188Hz | 1.9ms | 1kHz 2 | 94Hz | 3.0ms | 98Hz | 2.8ms | 1kHz 3 | 44Hz | 4.9ms | 42Hz | 4.8ms | 1kHz 4 | 21Hz | 8.5ms | 20Hz | 8.3ms | 1kHz 5 | 10Hz | 13.8ms | 10Hz | 13.4ms | 1kHz 6 | 5Hz | 19.0ms | 5Hz | 18.6ms | 1kHz 7 | -- Reserved -- | -- Reserved -- | Reserved DLFP configuration MPU6050_RA_CONFIG MPU6050_CFG_DLPF_CFG_BIT MPU6050_CFG_DLPF_CFG_LENGTH
References buffer, devAddr, MPU6050_CFG_DLPF_CFG_BIT, MPU6050_CFG_DLPF_CFG_LENGTH, MPU6050_RA_CONFIG, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setDLPFMode(uint8_t bandwidth)
Set digital low-pass filter configuration. mode New DLFP configuration setting getDLPFBandwidth() MPU6050_DLPF_BW_256 MPU6050_RA_CONFIG MPU6050_CFG_DLPF_CFG_BIT MPU6050_CFG_DLPF_CFG_LENGTH
References devAddr, MPU6050_CFG_DLPF_CFG_BIT, MPU6050_CFG_DLPF_CFG_LENGTH, MPU6050_RA_CONFIG, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getFullScaleGyroRange()
Get full-scale gyroscope range. The FS_SEL parameter allows setting the full-scale range of the gyro sensors, as described in the table below. 0 = +/- 250 degrees/sec 1 = +/- 500 degrees/sec 2 = +/- 1000 degrees/sec 3 = +/- 2000 degrees/sec Current full-scale gyroscope range setting MPU6050_GYRO_FS_250 MPU6050_RA_GYRO_CONFIG MPU6050_GCONFIG_FS_SEL_BIT MPU6050_GCONFIG_FS_SEL_LENGTH
References buffer, devAddr, MPU6050_GCONFIG_FS_SEL_BIT, MPU6050_GCONFIG_FS_SEL_LENGTH, MPU6050_RA_GYRO_CONFIG, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFullScaleGyroRange(uint8_t range)
Set full-scale gyroscope range. range New full-scale gyroscope range value getFullScaleRange() MPU6050_GYRO_FS_250 MPU6050_RA_GYRO_CONFIG MPU6050_GCONFIG_FS_SEL_BIT MPU6050_GCONFIG_FS_SEL_LENGTH
References devAddr, MPU6050_GCONFIG_FS_SEL_BIT, MPU6050_GCONFIG_FS_SEL_LENGTH, MPU6050_RA_GYRO_CONFIG, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, initialize.
uint8_t MPU6050_Base::getAccelXSelfTestFactoryTrim()
Get self-test factory trim value for accelerometer X axis. factory trim value MPU6050_RA_SELF_TEST_X
References buffer, devAddr, MPU6050_RA_SELF_TEST_A, MPU6050_RA_SELF_TEST_X, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getAccelYSelfTestFactoryTrim()
Get self-test factory trim value for accelerometer Y axis. factory trim value MPU6050_RA_SELF_TEST_Y
References buffer, devAddr, MPU6050_RA_SELF_TEST_A, MPU6050_RA_SELF_TEST_Y, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getAccelZSelfTestFactoryTrim()
Get self-test factory trim value for accelerometer Z axis. factory trim value MPU6050_RA_SELF_TEST_Z
References buffer, devAddr, MPU6050_RA_SELF_TEST_Z, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getGyroXSelfTestFactoryTrim()
Get self-test factory trim value for gyro X axis. factory trim value MPU6050_RA_SELF_TEST_X
References buffer, devAddr, MPU6050_RA_SELF_TEST_X, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getGyroYSelfTestFactoryTrim()
Get self-test factory trim value for gyro Y axis. factory trim value MPU6050_RA_SELF_TEST_Y
References buffer, devAddr, MPU6050_RA_SELF_TEST_Y, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getGyroZSelfTestFactoryTrim()
Get self-test factory trim value for gyro Z axis. factory trim value MPU6050_RA_SELF_TEST_Z
References buffer, devAddr, MPU6050_RA_SELF_TEST_Z, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getAccelXSelfTest()
Get self-test enabled setting for accelerometer X axis. Self-test enabled value MPU6050_RA_ACCEL_CONFIG
References buffer, devAddr, MPU6050_ACONFIG_XA_ST_BIT, MPU6050_RA_ACCEL_CONFIG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setAccelXSelfTest(bool enabled)
Get self-test enabled setting for accelerometer X axis. enabled Self-test enabled value MPU6050_RA_ACCEL_CONFIG
References devAddr, MPU6050_ACONFIG_XA_ST_BIT, MPU6050_RA_ACCEL_CONFIG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getAccelYSelfTest()
Get self-test enabled value for accelerometer Y axis. Self-test enabled value MPU6050_RA_ACCEL_CONFIG
References buffer, devAddr, MPU6050_ACONFIG_YA_ST_BIT, MPU6050_RA_ACCEL_CONFIG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setAccelYSelfTest(bool enabled)
Get self-test enabled value for accelerometer Y axis. enabled Self-test enabled value MPU6050_RA_ACCEL_CONFIG
References devAddr, MPU6050_ACONFIG_YA_ST_BIT, MPU6050_RA_ACCEL_CONFIG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getAccelZSelfTest()
Get self-test enabled value for accelerometer Z axis. Self-test enabled value MPU6050_RA_ACCEL_CONFIG
References buffer, devAddr, MPU6050_ACONFIG_ZA_ST_BIT, MPU6050_RA_ACCEL_CONFIG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setAccelZSelfTest(bool enabled)
Set self-test enabled value for accelerometer Z axis. enabled Self-test enabled value MPU6050_RA_ACCEL_CONFIG
References devAddr, MPU6050_ACONFIG_ZA_ST_BIT, MPU6050_RA_ACCEL_CONFIG, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getFullScaleAccelRange()
Get full-scale accelerometer range. The FS_SEL parameter allows setting the full-scale range of the accelerometer sensors, as described in the table below. 0 = +/- 2g 1 = +/- 4g 2 = +/- 8g 3 = +/- 16g Current full-scale accelerometer range setting MPU6050_ACCEL_FS_2 MPU6050_RA_ACCEL_CONFIG MPU6050_ACONFIG_AFS_SEL_BIT MPU6050_ACONFIG_AFS_SEL_LENGTH
References buffer, devAddr, MPU6050_ACONFIG_AFS_SEL_BIT, MPU6050_ACONFIG_AFS_SEL_LENGTH, MPU6050_RA_ACCEL_CONFIG, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
Referenced by PID.
void MPU6050_Base::setFullScaleAccelRange(uint8_t range)
Set full-scale accelerometer range. range New full-scale accelerometer range setting getFullScaleAccelRange()
References devAddr, MPU6050_ACONFIG_AFS_SEL_BIT, MPU6050_ACONFIG_AFS_SEL_LENGTH, MPU6050_RA_ACCEL_CONFIG, wireObj, I2Cdev::writeBits.
Referenced by initialize.
uint8_t MPU6050_Base::getDHPFMode()
Get the high-pass filter configuration. The DHPF is a filter module in the path leading to motion detectors (Free Fall, Motion threshold, and Zero Motion). The high pass filter output is not available to the data registers (see Figure in Section 8 of the MPU-6000/ MPU-6050 Product Specification document).The high pass filter has three modes: Reset: The filter output settles to zero within one sample. This effectively disables the high pass filter. This mode may be toggled to quickly settle the filter. On: The high pass filter will pass signals above the cut off frequency. Hold: When triggered, the filter holds the present sample. The filter output will be the difference between the input sample and the held sample. ACCEL_HPF | Filter Mode | Cut-off Frequency ----------+-------------+------------------ 0 | Reset | None 1 | On | 5Hz 2 | On | 2.5Hz 3 | On | 1.25Hz 4 | On | 0.63Hz 7 | Hold | None Current high-pass filter configuration MPU6050_DHPF_RESET MPU6050_RA_ACCEL_CONFIG
References buffer, devAddr, MPU6050_ACONFIG_ACCEL_HPF_BIT, MPU6050_ACONFIG_ACCEL_HPF_LENGTH, MPU6050_RA_ACCEL_CONFIG, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setDHPFMode(uint8_t mode)
Set the high-pass filter configuration. bandwidth New high-pass filter configuration setDHPFMode() MPU6050_DHPF_RESET MPU6050_RA_ACCEL_CONFIG
References devAddr, MPU6050_ACONFIG_ACCEL_HPF_BIT, MPU6050_ACONFIG_ACCEL_HPF_LENGTH, MPU6050_RA_ACCEL_CONFIG, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getFreefallDetectionThreshold()
Get free-fall event acceleration threshold. This register configures the detection threshold for Free Fall event detection. The unit of FF_THR is 1LSB = 2mg. Free Fall is detected when the absolute value of the accelerometer measurements for the three axes are each less than the detection threshold. This condition increments the Free Fall duration counter (Register 30). The Free Fall interrupt is triggered when the Free Fall duration counter reaches the time specified in FF_DUR.For more details on the Free Fall detection interrupt, see Section 8.2 of the MPU-6000/MPU-6050 Product Specification document as well as Registers 56 and 58 of this document.Current free-fall acceleration threshold value (LSB = 2mg) MPU6050_RA_FF_THR
References buffer, devAddr, MPU6050_RA_FF_THR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFreefallDetectionThreshold(uint8_t threshold)
Get free-fall event acceleration threshold. threshold New free-fall acceleration threshold value (LSB = 2mg) getFreefallDetectionThreshold() MPU6050_RA_FF_THR
References devAddr, MPU6050_RA_FF_THR, wireObj, I2Cdev::writeByte.
uint8_t MPU6050_Base::getFreefallDetectionDuration()
Get free-fall event duration threshold. This register configures the duration counter threshold for Free Fall event detection. The duration counter ticks at 1kHz, therefore FF_DUR has a unit of 1 LSB = 1 ms.The Free Fall duration counter increments while the absolute value of the accelerometer measurements are each less than the detection threshold (Register 29). The Free Fall interrupt is triggered when the Free Fall duration counter reaches the time specified in this register.For more details on the Free Fall detection interrupt, see Section 8.2 of the MPU-6000/MPU-6050 Product Specification document as well as Registers 56 and 58 of this document.Current free-fall duration threshold value (LSB = 1ms) MPU6050_RA_FF_DUR
References buffer, devAddr, MPU6050_RA_FF_DUR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFreefallDetectionDuration(uint8_t duration)
Get free-fall event duration threshold. duration New free-fall duration threshold value (LSB = 1ms) getFreefallDetectionDuration() MPU6050_RA_FF_DUR
References devAddr, MPU6050_RA_FF_DUR, wireObj, I2Cdev::writeByte.
uint8_t MPU6050_Base::getMotionDetectionThreshold()
Get motion detection event acceleration threshold. This register configures the detection threshold for Motion interrupt generation. The unit of MOT_THR is 1LSB = 2mg. Motion is detected when the absolute value of any of the accelerometer measurements exceeds this Motion detection threshold. This condition increments the Motion detection duration counter (Register 32). The Motion detection interrupt is triggered when the Motion Detection counter reaches the time count specified in MOT_DUR (Register 32).The Motion interrupt will indicate the axis and polarity of detected motion in MOT_DETECT_STATUS (Register 97).For more details on the Motion detection interrupt, see Section 8.3 of the MPU-6000/MPU-6050 Product Specification document as well as Registers 56 and 58 of this document.Current motion detection acceleration threshold value (LSB = 2mg) MPU6050_RA_MOT_THR
References buffer, devAddr, MPU6050_RA_MOT_THR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setMotionDetectionThreshold(uint8_t threshold)
Set motion detection event acceleration threshold. threshold New motion detection acceleration threshold value (LSB = 2mg) getMotionDetectionThreshold() MPU6050_RA_MOT_THR
References devAddr, MPU6050_RA_MOT_THR, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getMotionDetectionDuration()
Get motion detection event duration threshold. This register configures the duration counter threshold for Motion interrupt generation. The duration counter ticks at 1 kHz, therefore MOT_DUR has a unit of 1LSB = 1ms. The Motion detection duration counter increments when the absolute value of any of the accelerometer measurements exceeds the Motion detection threshold (Register 31). The Motion detection interrupt is triggered when the Motion detection counter reaches the time count specified in this register.For more details on the Motion detection interrupt, see Section 8.3 of the MPU-6000/MPU-6050 Product Specification document.Current motion detection duration threshold value (LSB = 1ms) MPU6050_RA_MOT_DUR
References buffer, devAddr, MPU6050_RA_MOT_DUR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setMotionDetectionDuration(uint8_t duration)
Set motion detection event duration threshold. duration New motion detection duration threshold value (LSB = 1ms) getMotionDetectionDuration() MPU6050_RA_MOT_DUR
References devAddr, MPU6050_RA_MOT_DUR, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getZeroMotionDetectionThreshold()
Get zero motion detection event acceleration threshold. This register configures the detection threshold for Zero Motion interrupt generation. The unit of ZRMOT_THR is 1LSB = 2mg. Zero Motion is detected when the absolute value of the accelerometer measurements for the 3 axes are each less than the detection threshold. This condition increments the Zero Motion duration counter (Register 34). The Zero Motion interrupt is triggered when the Zero Motion duration counter reaches the time count specified in ZRMOT_DUR (Register 34).Unlike Free Fall or Motion detection, Zero Motion detection triggers an interrupt both when Zero Motion is first detected and when Zero Motion is no longer detected.When a zero motion event is detected, a Zero Motion Status will be indicated in the MOT_DETECT_STATUS register (Register 97). When a motion-to-zero-motion condition is detected, the status bit is set to 1. When a zero-motion-to- motion condition is detected, the status bit is set to 0.For more details on the Zero Motion detection interrupt, see Section 8.4 of the MPU-6000/MPU-6050 Product Specification document as well as Registers 56 and 58 of this document.Current zero motion detection acceleration threshold value (LSB = 2mg) MPU6050_RA_ZRMOT_THR
References buffer, devAddr, MPU6050_RA_ZRMOT_THR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setZeroMotionDetectionThreshold(uint8_t threshold)
Set zero motion detection event acceleration threshold. threshold New zero motion detection acceleration threshold value (LSB = 2mg) getZeroMotionDetectionThreshold() MPU6050_RA_ZRMOT_THR
References devAddr, MPU6050_RA_ZRMOT_THR, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getZeroMotionDetectionDuration()
Get zero motion detection event duration threshold. This register configures the duration counter threshold for Zero Motion interrupt generation. The duration counter ticks at 16 Hz, therefore ZRMOT_DUR has a unit of 1 LSB = 64 ms. The Zero Motion duration counter increments while the absolute value of the accelerometer measurements are each less than the detection threshold (Register 33). The Zero Motion interrupt is triggered when the Zero Motion duration counter reaches the time count specified in this register.For more details on the Zero Motion detection interrupt, see Section 8.4 of the MPU-6000/MPU-6050 Product Specification document, as well as Registers 56 and 58 of this document.Current zero motion detection duration threshold value (LSB = 64ms) MPU6050_RA_ZRMOT_DUR
References buffer, devAddr, MPU6050_RA_ZRMOT_DUR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setZeroMotionDetectionDuration(uint8_t duration)
Set zero motion detection event duration threshold. duration New zero motion detection duration threshold value (LSB = 1ms) getZeroMotionDetectionDuration() MPU6050_RA_ZRMOT_DUR
References devAddr, MPU6050_RA_ZRMOT_DUR, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
bool MPU6050_Base::getTempFIFOEnabled()
Get temperature FIFO enabled value. When set to 1, this bit enables TEMP_OUT_H and TEMP_OUT_L (Registers 65 and 66) to be written into the FIFO buffer. Current temperature FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_TEMP_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setTempFIFOEnabled(bool enabled)
Set temperature FIFO enabled value. enabled New temperature FIFO enabled value getTempFIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_TEMP_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getXGyroFIFOEnabled()
Get gyroscope X-axis FIFO enabled value. When set to 1, this bit enables GYRO_XOUT_H and GYRO_XOUT_L (Registers 67 and 68) to be written into the FIFO buffer. Current gyroscope X-axis FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_XG_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setXGyroFIFOEnabled(bool enabled)
Set gyroscope X-axis FIFO enabled value. enabled New gyroscope X-axis FIFO enabled value getXGyroFIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_XG_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getYGyroFIFOEnabled()
Get gyroscope Y-axis FIFO enabled value. When set to 1, this bit enables GYRO_YOUT_H and GYRO_YOUT_L (Registers 69 and 70) to be written into the FIFO buffer. Current gyroscope Y-axis FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_YG_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setYGyroFIFOEnabled(bool enabled)
Set gyroscope Y-axis FIFO enabled value. enabled New gyroscope Y-axis FIFO enabled value getYGyroFIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_YG_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getZGyroFIFOEnabled()
Get gyroscope Z-axis FIFO enabled value. When set to 1, this bit enables GYRO_ZOUT_H and GYRO_ZOUT_L (Registers 71 and 72) to be written into the FIFO buffer. Current gyroscope Z-axis FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_ZG_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setZGyroFIFOEnabled(bool enabled)
Set gyroscope Z-axis FIFO enabled value. enabled New gyroscope Z-axis FIFO enabled value getZGyroFIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_ZG_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getAccelFIFOEnabled()
Get accelerometer FIFO enabled value. When set to 1, this bit enables ACCEL_XOUT_H, ACCEL_XOUT_L, ACCEL_YOUT_H, ACCEL_YOUT_L, ACCEL_ZOUT_H, and ACCEL_ZOUT_L (Registers 59 to 64) to be written into the FIFO buffer. Current accelerometer FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_ACCEL_FIFO_EN_BIT, MPU6050_RA_FIFO_EN, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setAccelFIFOEnabled(bool enabled)
Set accelerometer FIFO enabled value. enabled New accelerometer FIFO enabled value getAccelFIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_ACCEL_FIFO_EN_BIT, MPU6050_RA_FIFO_EN, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlave2FIFOEnabled()
Get Slave 2 FIFO enabled value. When set to 1, this bit enables EXT_SENS_DATA registers (Registers 73 to 96) associated with Slave 2 to be written into the FIFO buffer. Current Slave 2 FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_SLV2_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave2FIFOEnabled(bool enabled)
Set Slave 2 FIFO enabled value. enabled New Slave 2 FIFO enabled value getSlave2FIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_SLV2_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlave1FIFOEnabled()
Get Slave 1 FIFO enabled value. When set to 1, this bit enables EXT_SENS_DATA registers (Registers 73 to 96) associated with Slave 1 to be written into the FIFO buffer. Current Slave 1 FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_SLV1_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave1FIFOEnabled(bool enabled)
Set Slave 1 FIFO enabled value. enabled New Slave 1 FIFO enabled value getSlave1FIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_SLV1_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlave0FIFOEnabled()
Get Slave 0 FIFO enabled value. When set to 1, this bit enables EXT_SENS_DATA registers (Registers 73 to 96) associated with Slave 0 to be written into the FIFO buffer. Current Slave 0 FIFO enabled value MPU6050_RA_FIFO_EN
References buffer, devAddr, MPU6050_RA_FIFO_EN, MPU6050_SLV0_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave0FIFOEnabled(bool enabled)
Set Slave 0 FIFO enabled value. enabled New Slave 0 FIFO enabled value getSlave0FIFOEnabled() MPU6050_RA_FIFO_EN
References devAddr, MPU6050_RA_FIFO_EN, MPU6050_SLV0_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getMultiMasterEnabled()
Get multi-master enabled value. Multi-master capability allows multiple I2C masters to operate on the same bus. In circuits where multi-master capability is required, set MULT_MST_EN to 1. This will increase current drawn by approximately 30uA.In circuits where multi-master capability is required, the state of the I2C bus must always be monitored by each separate I2C Master. Before an I2C Master can assume arbitration of the bus, it must first confirm that no other I2C Master has arbitration of the bus. When MULT_MST_EN is set to 1, the MPU-60X0's bus arbitration detection logic is turned on, enabling it to detect when the bus is available.Current multi-master enabled value MPU6050_RA_I2C_MST_CTRL
References buffer, devAddr, MPU6050_MULT_MST_EN_BIT, MPU6050_RA_I2C_MST_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setMultiMasterEnabled(bool enabled)
Set multi-master enabled value. enabled New multi-master enabled value getMultiMasterEnabled() MPU6050_RA_I2C_MST_CTRL
References devAddr, MPU6050_MULT_MST_EN_BIT, MPU6050_RA_I2C_MST_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getWaitForExternalSensorEnabled()
Get wait-for-external-sensor-data enabled value. When the WAIT_FOR_ES bit is set to 1, the Data Ready interrupt will be delayed until External Sensor data from the Slave Devices are loaded into the EXT_SENS_DATA registers. This is used to ensure that both the internal sensor data (i.e. from gyro and accel) and external sensor data have been loaded to their respective data registers (i.e. the data is synced) when the Data Ready interrupt is triggered.Current wait-for-external-sensor-data enabled value MPU6050_RA_I2C_MST_CTRL
References buffer, devAddr, MPU6050_RA_I2C_MST_CTRL, MPU6050_WAIT_FOR_ES_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setWaitForExternalSensorEnabled(bool enabled)
Set wait-for-external-sensor-data enabled value. enabled New wait-for-external-sensor-data enabled value getWaitForExternalSensorEnabled() MPU6050_RA_I2C_MST_CTRL
References devAddr, MPU6050_RA_I2C_MST_CTRL, MPU6050_WAIT_FOR_ES_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlave3FIFOEnabled()
Get Slave 3 FIFO enabled value. When set to 1, this bit enables EXT_SENS_DATA registers (Registers 73 to 96) associated with Slave 3 to be written into the FIFO buffer. Current Slave 3 FIFO enabled value MPU6050_RA_MST_CTRL
References buffer, devAddr, MPU6050_RA_I2C_MST_CTRL, MPU6050_SLV_3_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave3FIFOEnabled(bool enabled)
Set Slave 3 FIFO enabled value. enabled New Slave 3 FIFO enabled value getSlave3FIFOEnabled() MPU6050_RA_MST_CTRL
References devAddr, MPU6050_RA_I2C_MST_CTRL, MPU6050_SLV_3_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlaveReadWriteTransitionEnabled()
Get slave read/write transition enabled value. The I2C_MST_P_NSR bit configures the I2C Master's transition from one slave read to the next slave read. If the bit equals 0, there will be a restart between reads. If the bit equals 1, there will be a stop followed by a start of the following read. When a write transaction follows a read transaction, the stop followed by a start of the successive write will be always used.Current slave read/write transition enabled value MPU6050_RA_I2C_MST_CTRL
References buffer, devAddr, MPU6050_I2C_MST_P_NSR_BIT, MPU6050_RA_I2C_MST_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveReadWriteTransitionEnabled(bool enabled)
Set slave read/write transition enabled value. enabled New slave read/write transition enabled value getSlaveReadWriteTransitionEnabled() MPU6050_RA_I2C_MST_CTRL
References devAddr, MPU6050_I2C_MST_P_NSR_BIT, MPU6050_RA_I2C_MST_CTRL, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getMasterClockSpeed()
Get I2C master clock speed. I2C_MST_CLK is a 4 bit unsigned value which configures a divider on the MPU-60X0 internal 8MHz clock. It sets the I2C master clock speed according to the following table: I2C_MST_CLK | I2C Master Clock Speed | 8MHz Clock Divider ------------+------------------------+------------------- 0 | 348kHz | 23 1 | 333kHz | 24 2 | 320kHz | 25 3 | 308kHz | 26 4 | 296kHz | 27 5 | 286kHz | 28 6 | 276kHz | 29 7 | 267kHz | 30 8 | 258kHz | 31 9 | 500kHz | 16 10 | 471kHz | 17 11 | 444kHz | 18 12 | 421kHz | 19 13 | 400kHz | 20 14 | 381kHz | 21 15 | 364kHz | 22 Current I2C master clock speed MPU6050_RA_I2C_MST_CTRL
References buffer, devAddr, MPU6050_I2C_MST_CLK_BIT, MPU6050_I2C_MST_CLK_LENGTH, MPU6050_RA_I2C_MST_CTRL, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setMasterClockSpeed(uint8_t speed)
Set I2C master clock speed. speed Current I2C master clock speed MPU6050_RA_I2C_MST_CTRL
References devAddr, MPU6050_I2C_MST_CLK_BIT, MPU6050_I2C_MST_CLK_LENGTH, MPU6050_RA_I2C_MST_CTRL, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getSlaveAddress(uint8_t num)
Get the I2C address of the specified slave (0-3). Note that Bit 7 (MSB) controls read/write mode. If Bit 7 is set, it's a read operation, and if it is cleared, then it's a write operation. The remaining bits (6-0) are the 7-bit device address of the slave device.In read mode, the result of the read is placed in the lowest available EXT_SENS_DATA register. For further information regarding the allocation of read results, please refer to the EXT_SENS_DATA register description (Registers 73 - 96).The MPU-6050 supports a total of five slaves, but Slave 4 has unique characteristics, and so it has its own functions (getSlave4* and setSlave4*).I2C data transactions are performed at the Sample Rate, as defined in Register 25. The user is responsible for ensuring that I2C data transactions to and from each enabled Slave can be completed within a single period of the Sample Rate.The I2C slave access rate can be reduced relative to the Sample Rate. This reduced access rate is determined by I2C_MST_DLY (Register 52). Whether a slave's access rate is reduced relative to the Sample Rate is determined by I2C_MST_DELAY_CTRL (Register 103).The processing order for the slaves is fixed. The sequence followed for processing the slaves is Slave 0, Slave 1, Slave 2, Slave 3 and Slave 4. If a particular Slave is disabled it will be skipped.Each slave can either be accessed at the sample rate or at a reduced sample rate. In a case where some slaves are accessed at the Sample Rate and some slaves are accessed at the reduced rate, the sequence of accessing the slaves (Slave 0 to Slave 4) is still followed. However, the reduced rate slaves will be skipped if their access rate dictates that they should not be accessed during that particular cycle. For further information regarding the reduced access rate, please refer to Register 52. Whether a slave is accessed at the Sample Rate or at the reduced rate is determined by the Delay Enable bits in Register 103. num Slave number (0-3) Current address for specified slave MPU6050_RA_I2C_SLV0_ADDR
References buffer, devAddr, MPU6050_RA_I2C_SLV0_ADDR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveAddress(uint8_t num, uint8_t address)
Set the I2C address of the specified slave (0-3). num Slave number (0-3) address New address for specified slave getSlaveAddress() MPU6050_RA_I2C_SLV0_ADDR
References devAddr, MPU6050_RA_I2C_SLV0_ADDR, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize.
uint8_t MPU6050_Base::getSlaveRegister(uint8_t num)
Get the active internal register for the specified slave (0-3). Read/write operations for this slave will be done to whatever internal register address is stored in this MPU register.The MPU-6050 supports a total of five slaves, but Slave 4 has unique characteristics, and so it has its own functions. num Slave number (0-3) Current active register for specified slave MPU6050_RA_I2C_SLV0_REG
References buffer, devAddr, MPU6050_RA_I2C_SLV0_REG, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveRegister(uint8_t num, uint8_t reg)
Set the active internal register for the specified slave (0-3). num Slave number (0-3) reg New active register for specified slave getSlaveRegister() MPU6050_RA_I2C_SLV0_REG
References devAddr, MPU6050_RA_I2C_SLV0_REG, wireObj, I2Cdev::writeByte.
bool MPU6050_Base::getSlaveEnabled(uint8_t num)
Get the enabled value for the specified slave (0-3). When set to 1, this bit enables Slave 0 for data transfer operations. When cleared to 0, this bit disables Slave 0 from data transfer operations. num Slave number (0-3) Current enabled value for specified slave MPU6050_RA_I2C_SLV0_CTRL
References buffer, devAddr, MPU6050_I2C_SLV_EN_BIT, MPU6050_RA_I2C_SLV0_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveEnabled(uint8_t num, bool enabled)
Set the enabled value for the specified slave (0-3). num Slave number (0-3) enabled New enabled value for specified slave getSlaveEnabled() MPU6050_RA_I2C_SLV0_CTRL
References devAddr, MPU6050_I2C_SLV_EN_BIT, MPU6050_RA_I2C_SLV0_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlaveWordByteSwap(uint8_t num)
Get word pair byte-swapping enabled for the specified slave (0-3). When set to 1, this bit enables byte swapping. When byte swapping is enabled, the high and low bytes of a word pair are swapped. Please refer to I2C_SLV0_GRP for the pairing convention of the word pairs. When cleared to 0, bytes transferred to and from Slave 0 will be written to EXT_SENS_DATA registers in the order they were transferred. num Slave number (0-3) Current word pair byte-swapping enabled value for specified slave MPU6050_RA_I2C_SLV0_CTRL
References buffer, devAddr, MPU6050_I2C_SLV_BYTE_SW_BIT, MPU6050_RA_I2C_SLV0_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveWordByteSwap(uint8_t num, bool enabled)
Set word pair byte-swapping enabled for the specified slave (0-3). num Slave number (0-3) enabled New word pair byte-swapping enabled value for specified slave getSlaveWordByteSwap() MPU6050_RA_I2C_SLV0_CTRL
References devAddr, MPU6050_I2C_SLV_BYTE_SW_BIT, MPU6050_RA_I2C_SLV0_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlaveWriteMode(uint8_t num)
Get write mode for the specified slave (0-3). When set to 1, the transaction will read or write data only. When cleared to 0, the transaction will write a register address prior to reading or writing data. This should equal 0 when specifying the register address within the Slave device to/from which the ensuing data transaction will take place. num Slave number (0-3) Current write mode for specified slave (0 = register address + data, 1 = data only) MPU6050_RA_I2C_SLV0_CTRL
References buffer, devAddr, MPU6050_I2C_SLV_REG_DIS_BIT, MPU6050_RA_I2C_SLV0_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveWriteMode(uint8_t num, bool mode)
Set write mode for the specified slave (0-3). num Slave number (0-3) mode New write mode for specified slave (0 = register address + data, 1 = data only) getSlaveWriteMode() MPU6050_RA_I2C_SLV0_CTRL
References devAddr, MPU6050_I2C_SLV_REG_DIS_BIT, MPU6050_RA_I2C_SLV0_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlaveWordGroupOffset(uint8_t num)
Get word pair grouping order offset for the specified slave (0-3). This sets specifies the grouping order of word pairs received from registers. When cleared to 0, bytes from register addresses 0 and 1, 2 and 3, etc (even, then odd register addresses) are paired to form a word. When set to 1, bytes from register addresses are paired 1 and 2, 3 and 4, etc. (odd, then even register addresses) are paired to form a word. num Slave number (0-3) Current word pair grouping order offset for specified slave MPU6050_RA_I2C_SLV0_CTRL
References buffer, devAddr, MPU6050_I2C_SLV_GRP_BIT, MPU6050_RA_I2C_SLV0_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveWordGroupOffset(uint8_t num, bool enabled)
Set word pair grouping order offset for the specified slave (0-3). num Slave number (0-3) enabled New word pair grouping order offset for specified slave getSlaveWordGroupOffset() MPU6050_RA_I2C_SLV0_CTRL
References devAddr, MPU6050_I2C_SLV_GRP_BIT, MPU6050_RA_I2C_SLV0_CTRL, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getSlaveDataLength(uint8_t num)
Get number of bytes to read for the specified slave (0-3). Specifies the number of bytes transferred to and from Slave 0. Clearing this bit to 0 is equivalent to disabling the register by writing 0 to I2C_SLV0_EN. num Slave number (0-3) Number of bytes to read for specified slave MPU6050_RA_I2C_SLV0_CTRL
References buffer, devAddr, MPU6050_I2C_SLV_LEN_BIT, MPU6050_I2C_SLV_LEN_LENGTH, MPU6050_RA_I2C_SLV0_CTRL, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveDataLength(uint8_t num, uint8_t length)
Set number of bytes to read for the specified slave (0-3). num Slave number (0-3) length Number of bytes to read for specified slave getSlaveDataLength() MPU6050_RA_I2C_SLV0_CTRL
References devAddr, MPU6050_I2C_SLV_LEN_BIT, MPU6050_I2C_SLV_LEN_LENGTH, MPU6050_RA_I2C_SLV0_CTRL, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getSlave4Address()
Get the I2C address of Slave 4. Note that Bit 7 (MSB) controls read/write mode. If Bit 7 is set, it's a read operation, and if it is cleared, then it's a write operation. The remaining bits (6-0) are the 7-bit device address of the slave device.Current address for Slave 4 getSlaveAddress() MPU6050_RA_I2C_SLV4_ADDR
References buffer, devAddr, MPU6050_RA_I2C_SLV4_ADDR, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave4Address(uint8_t address)
Set the I2C address of Slave 4. address New address for Slave 4 getSlave4Address() MPU6050_RA_I2C_SLV4_ADDR
References devAddr, MPU6050_RA_I2C_SLV4_ADDR, wireObj, I2Cdev::writeByte.
uint8_t MPU6050_Base::getSlave4Register()
Get the active internal register for the Slave 4. Read/write operations for this slave will be done to whatever internal register address is stored in this MPU register.Current active register for Slave 4 MPU6050_RA_I2C_SLV4_REG
References buffer, devAddr, MPU6050_RA_I2C_SLV4_REG, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave4Register(uint8_t reg)
Set the active internal register for Slave 4. reg New active register for Slave 4 getSlave4Register() MPU6050_RA_I2C_SLV4_REG
References devAddr, MPU6050_RA_I2C_SLV4_REG, wireObj, I2Cdev::writeByte.
void MPU6050_Base::setSlave4OutputByte(uint8_t data)
Set new byte to write to Slave 4. This register stores the data to be written into the Slave 4. If I2C_SLV4_RW is set 1 (set to read), this register has no effect. data New byte to write to Slave 4 MPU6050_RA_I2C_SLV4_DO
References devAddr, MPU6050_RA_I2C_SLV4_DO, wireObj, I2Cdev::writeByte.
bool MPU6050_Base::getSlave4Enabled()
Get the enabled value for the Slave 4. When set to 1, this bit enables Slave 4 for data transfer operations. When cleared to 0, this bit disables Slave 4 from data transfer operations. Current enabled value for Slave 4 MPU6050_RA_I2C_SLV4_CTRL
References buffer, devAddr, MPU6050_I2C_SLV4_EN_BIT, MPU6050_RA_I2C_SLV4_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave4Enabled(bool enabled)
Set the enabled value for Slave 4. enabled New enabled value for Slave 4 getSlave4Enabled() MPU6050_RA_I2C_SLV4_CTRL
References devAddr, MPU6050_I2C_SLV4_EN_BIT, MPU6050_RA_I2C_SLV4_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlave4InterruptEnabled()
Get the enabled value for Slave 4 transaction interrupts. When set to 1, this bit enables the generation of an interrupt signal upon completion of a Slave 4 transaction. When cleared to 0, this bit disables the generation of an interrupt signal upon completion of a Slave 4 transaction. The interrupt status can be observed in Register 54.Current enabled value for Slave 4 transaction interrupts. MPU6050_RA_I2C_SLV4_CTRL
References buffer, devAddr, MPU6050_I2C_SLV4_INT_EN_BIT, MPU6050_RA_I2C_SLV4_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave4InterruptEnabled(bool enabled)
Set the enabled value for Slave 4 transaction interrupts. enabled New enabled value for Slave 4 transaction interrupts. getSlave4InterruptEnabled() MPU6050_RA_I2C_SLV4_CTRL
References devAddr, MPU6050_I2C_SLV4_INT_EN_BIT, MPU6050_RA_I2C_SLV4_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlave4WriteMode()
Get write mode for Slave 4. When set to 1, the transaction will read or write data only. When cleared to 0, the transaction will write a register address prior to reading or writing data. This should equal 0 when specifying the register address within the Slave device to/from which the ensuing data transaction will take place.Current write mode for Slave 4 (0 = register address + data, 1 = data only) MPU6050_RA_I2C_SLV4_CTRL
References buffer, devAddr, MPU6050_I2C_SLV4_REG_DIS_BIT, MPU6050_RA_I2C_SLV4_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave4WriteMode(bool mode)
Set write mode for the Slave 4. mode New write mode for Slave 4 (0 = register address + data, 1 = data only) getSlave4WriteMode() MPU6050_RA_I2C_SLV4_CTRL
References devAddr, MPU6050_I2C_SLV4_REG_DIS_BIT, MPU6050_RA_I2C_SLV4_CTRL, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getSlave4MasterDelay()
Get Slave 4 master delay value. This configures the reduced access rate of I2C slaves relative to the Sample Rate. When a slave's access rate is decreased relative to the Sample Rate, the slave is accessed every: 1 / (1 + I2C_MST_DLY) samples This base Sample Rate in turn is determined by SMPLRT_DIV (register 25) and DLPF_CFG (register 26). Whether a slave's access rate is reduced relative to the Sample Rate is determined by I2C_MST_DELAY_CTRL (register 103). For further information regarding the Sample Rate, please refer to register 25.Current Slave 4 master delay value MPU6050_RA_I2C_SLV4_CTRL
References buffer, devAddr, MPU6050_I2C_SLV4_MST_DLY_BIT, MPU6050_I2C_SLV4_MST_DLY_LENGTH, MPU6050_RA_I2C_SLV4_CTRL, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlave4MasterDelay(uint8_t delay)
Set Slave 4 master delay value. delay New Slave 4 master delay value getSlave4MasterDelay() MPU6050_RA_I2C_SLV4_CTRL
References devAddr, MPU6050_I2C_SLV4_MST_DLY_BIT, MPU6050_I2C_SLV4_MST_DLY_LENGTH, MPU6050_RA_I2C_SLV4_CTRL, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getSlate4InputByte()
Get last available byte read from Slave 4. This register stores the data read from Slave 4. This field is populated after a read transaction. Last available byte read from to Slave 4 MPU6050_RA_I2C_SLV4_DI
References buffer, devAddr, MPU6050_RA_I2C_SLV4_DI, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getPassthroughStatus()
Get FSYNC interrupt status. This bit reflects the status of the FSYNC interrupt from an external device into the MPU-60X0. This is used as a way to pass an external interrupt through the MPU-60X0 to the host application processor. When set to 1, this bit will cause an interrupt if FSYNC_INT_EN is asserted in INT_PIN_CFG (Register 55). FSYNC interrupt status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_PASS_THROUGH_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getSlave4IsDone()
Get Slave 4 transaction done status. Automatically sets to 1 when a Slave 4 transaction has completed. This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted and if the SLV_4_DONE_INT bit is asserted in the I2C_SLV4_CTRL register (Register 52). Slave 4 transaction done status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_SLV4_DONE_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getLostArbitration()
Get master arbitration lost status. This bit automatically sets to 1 when the I2C Master has lost arbitration of the auxiliary I2C bus (an error condition). This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted. Master arbitration lost status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_LOST_ARB_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getSlave4Nack()
Get Slave 4 NACK status. This bit automatically sets to 1 when the I2C Master receives a NACK in a transaction with Slave 4. This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted. Slave 4 NACK interrupt status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_SLV4_NACK_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getSlave3Nack()
Get Slave 3 NACK status. This bit automatically sets to 1 when the I2C Master receives a NACK in a transaction with Slave 3. This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted. Slave 3 NACK interrupt status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_SLV3_NACK_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getSlave2Nack()
Get Slave 2 NACK status. This bit automatically sets to 1 when the I2C Master receives a NACK in a transaction with Slave 2. This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted. Slave 2 NACK interrupt status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_SLV2_NACK_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getSlave1Nack()
Get Slave 1 NACK status. This bit automatically sets to 1 when the I2C Master receives a NACK in a transaction with Slave 1. This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted. Slave 1 NACK interrupt status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_SLV1_NACK_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getSlave0Nack()
Get Slave 0 NACK status. This bit automatically sets to 1 when the I2C Master receives a NACK in a transaction with Slave 0. This triggers an interrupt if the I2C_MST_INT_EN bit in the INT_ENABLE register (Register 56) is asserted. Slave 0 NACK interrupt status MPU6050_RA_I2C_MST_STATUS
References buffer, devAddr, MPU6050_MST_I2C_SLV0_NACK_BIT, MPU6050_RA_I2C_MST_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getInterruptMode()
Get interrupt logic level mode. Will be set 0 for active-high, 1 for active-low. Current interrupt mode (0=active-high, 1=active-low) MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_INT_LEVEL_BIT
References buffer, devAddr, MPU6050_INTCFG_INT_LEVEL_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setInterruptMode(bool mode)
Set interrupt logic level mode. mode New interrupt mode (0=active-high, 1=active-low) getInterruptMode() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_INT_LEVEL_BIT
References devAddr, MPU6050_INTCFG_INT_LEVEL_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getInterruptDrive()
Get interrupt drive mode. Will be set 0 for push-pull, 1 for open-drain. Current interrupt drive mode (0=push-pull, 1=open-drain) MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_INT_OPEN_BIT
References buffer, devAddr, MPU6050_INTCFG_INT_OPEN_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setInterruptDrive(bool drive)
Set interrupt drive mode. drive New interrupt drive mode (0=push-pull, 1=open-drain) getInterruptDrive() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_INT_OPEN_BIT
References devAddr, MPU6050_INTCFG_INT_OPEN_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getInterruptLatch()
Get interrupt latch mode. Will be set 0 for 50us-pulse, 1 for latch-until-int-cleared. Current latch mode (0=50us-pulse, 1=latch-until-int-cleared) MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_LATCH_INT_EN_BIT
References buffer, devAddr, MPU6050_INTCFG_LATCH_INT_EN_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setInterruptLatch(bool latch)
Set interrupt latch mode. latch New latch mode (0=50us-pulse, 1=latch-until-int-cleared) getInterruptLatch() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_LATCH_INT_EN_BIT
References devAddr, MPU6050_INTCFG_LATCH_INT_EN_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getInterruptLatchClear()
Get interrupt latch clear mode. Will be set 0 for status-read-only, 1 for any-register-read. Current latch clear mode (0=status-read-only, 1=any-register-read) MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_INT_RD_CLEAR_BIT
References buffer, devAddr, MPU6050_INTCFG_INT_RD_CLEAR_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setInterruptLatchClear(bool clear)
Set interrupt latch clear mode. clear New latch clear mode (0=status-read-only, 1=any-register-read) getInterruptLatchClear() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_INT_RD_CLEAR_BIT
References devAddr, MPU6050_INTCFG_INT_RD_CLEAR_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getFSyncInterruptLevel()
Get FSYNC interrupt logic level mode. Current FSYNC interrupt mode (0=active-high, 1=active-low) getFSyncInterruptMode() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_FSYNC_INT_LEVEL_BIT
References buffer, devAddr, MPU6050_INTCFG_FSYNC_INT_LEVEL_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFSyncInterruptLevel(bool level)
Set FSYNC interrupt logic level mode. mode New FSYNC interrupt mode (0=active-high, 1=active-low) getFSyncInterruptMode() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_FSYNC_INT_LEVEL_BIT
References devAddr, MPU6050_INTCFG_FSYNC_INT_LEVEL_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getFSyncInterruptEnabled()
Get FSYNC pin interrupt enabled setting. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled setting MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_FSYNC_INT_EN_BIT
References buffer, devAddr, MPU6050_INTCFG_FSYNC_INT_EN_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFSyncInterruptEnabled(bool enabled)
Set FSYNC pin interrupt enabled setting. enabled New FSYNC pin interrupt enabled setting getFSyncInterruptEnabled() MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_FSYNC_INT_EN_BIT
References devAddr, MPU6050_INTCFG_FSYNC_INT_EN_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getI2CBypassEnabled()
Get I2C bypass enabled status. When this bit is equal to 1 and I2C_MST_EN (Register 106 bit[5]) is equal to 0, the host application processor will be able to directly access the auxiliary I2C bus of the MPU-60X0. When this bit is equal to 0, the host application processor will not be able to directly access the auxiliary I2C bus of the MPU-60X0 regardless of the state of I2C_MST_EN (Register 106 bit[5]). Current I2C bypass enabled status MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_I2C_BYPASS_EN_BIT
References buffer, devAddr, MPU6050_INTCFG_I2C_BYPASS_EN_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setI2CBypassEnabled(bool enabled)
Set I2C bypass enabled status. When this bit is equal to 1 and I2C_MST_EN (Register 106 bit[5]) is equal to 0, the host application processor will be able to directly access the auxiliary I2C bus of the MPU-60X0. When this bit is equal to 0, the host application processor will not be able to directly access the auxiliary I2C bus of the MPU-60X0 regardless of the state of I2C_MST_EN (Register 106 bit[5]). enabled New I2C bypass enabled status MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_I2C_BYPASS_EN_BIT
References devAddr, MPU6050_INTCFG_I2C_BYPASS_EN_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getClockOutputEnabled()
Get reference clock output enabled status. When this bit is equal to 1, a reference clock output is provided at the CLKOUT pin. When this bit is equal to 0, the clock output is disabled. For further information regarding CLKOUT, please refer to the MPU-60X0 Product Specification document. Current reference clock output enabled status MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_CLKOUT_EN_BIT
References buffer, devAddr, MPU6050_INTCFG_CLKOUT_EN_BIT, MPU6050_RA_INT_PIN_CFG, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setClockOutputEnabled(bool enabled)
Set reference clock output enabled status. When this bit is equal to 1, a reference clock output is provided at the CLKOUT pin. When this bit is equal to 0, the clock output is disabled. For further information regarding CLKOUT, please refer to the MPU-60X0 Product Specification document. enabled New reference clock output enabled status MPU6050_RA_INT_PIN_CFG MPU6050_INTCFG_CLKOUT_EN_BIT
References devAddr, MPU6050_INTCFG_CLKOUT_EN_BIT, MPU6050_RA_INT_PIN_CFG, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getIntEnabled()
Get full interrupt enabled status. Full register byte for all interrupts, for quick reading. Each bit will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_FF_BIT
References buffer, devAddr, MPU6050_RA_INT_ENABLE, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntEnabled(uint8_t enabled)
Set full interrupt enabled status. Full register byte for all interrupts, for quick reading. Each bit should be set 0 for disabled, 1 for enabled. enabled New interrupt enabled status getIntFreefallEnabled() MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_FF_BIT
References devAddr, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
bool MPU6050_Base::getIntFreefallEnabled()
Get Free Fall interrupt enabled status. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_FF_BIT
References buffer, devAddr, MPU6050_INTERRUPT_FF_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntFreefallEnabled(bool enabled)
Set Free Fall interrupt enabled status. enabled New interrupt enabled status getIntFreefallEnabled() MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_FF_BIT
References devAddr, MPU6050_INTERRUPT_FF_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getIntMotionEnabled()
Get Motion Detection interrupt enabled status. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_MOT_BIT
References buffer, devAddr, MPU6050_INTERRUPT_MOT_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntMotionEnabled(bool enabled)
Set Motion Detection interrupt enabled status. enabled New interrupt enabled status getIntMotionEnabled() MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_MOT_BIT
References devAddr, MPU6050_INTERRUPT_MOT_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getIntZeroMotionEnabled()
Get Zero Motion Detection interrupt enabled status. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_ZMOT_BIT
References buffer, devAddr, MPU6050_INTERRUPT_ZMOT_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntZeroMotionEnabled(bool enabled)
Set Zero Motion Detection interrupt enabled status. enabled New interrupt enabled status getIntZeroMotionEnabled() MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_ZMOT_BIT
References devAddr, MPU6050_INTERRUPT_ZMOT_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getIntFIFOBufferOverflowEnabled()
Get FIFO Buffer Overflow interrupt enabled status. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_FIFO_OFLOW_BIT
References buffer, devAddr, MPU6050_INTERRUPT_FIFO_OFLOW_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntFIFOBufferOverflowEnabled(bool enabled)
Set FIFO Buffer Overflow interrupt enabled status. enabled New interrupt enabled status getIntFIFOBufferOverflowEnabled() MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_FIFO_OFLOW_BIT
References devAddr, MPU6050_INTERRUPT_FIFO_OFLOW_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getIntI2CMasterEnabled()
Get I2C Master interrupt enabled status. This enables any of the I2C Master interrupt sources to generate an interrupt. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_I2C_MST_INT_BIT
References buffer, devAddr, MPU6050_INTERRUPT_I2C_MST_INT_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntI2CMasterEnabled(bool enabled)
Set I2C Master interrupt enabled status. enabled New interrupt enabled status getIntI2CMasterEnabled() MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_I2C_MST_INT_BIT
References devAddr, MPU6050_INTERRUPT_I2C_MST_INT_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getIntDataReadyEnabled()
Get Data Ready interrupt enabled setting. This event occurs each time a write operation to all of the sensor registers has been completed. Will be set 0 for disabled, 1 for enabled. Current interrupt enabled status MPU6050_RA_INT_ENABLE MPU6050_INTERRUPT_DATA_RDY_BIT
References buffer, devAddr, MPU6050_INTERRUPT_DATA_RDY_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntDataReadyEnabled(bool enabled)
Set Data Ready interrupt enabled status. enabled New interrupt enabled status getIntDataReadyEnabled() MPU6050_RA_INT_CFG MPU6050_INTERRUPT_DATA_RDY_BIT
References devAddr, MPU6050_INTERRUPT_DATA_RDY_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getIntStatus()
Get full set of interrupt status bits. These bits clear to 0 after the register has been read. Very useful for getting multiple INT statuses, since each single bit read clears all of them because it has to read the whole byte. Current interrupt status MPU6050_RA_INT_STATUS
References buffer, devAddr, MPU6050_RA_INT_STATUS, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
bool MPU6050_Base::getIntFreefallStatus()
Get Free Fall interrupt status. This bit automatically sets to 1 when a Free Fall interrupt has been generated. The bit clears to 0 after the register has been read. Current interrupt status MPU6050_RA_INT_STATUS MPU6050_INTERRUPT_FF_BIT
References buffer, devAddr, MPU6050_INTERRUPT_FF_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntMotionStatus()
Get Motion Detection interrupt status. This bit automatically sets to 1 when a Motion Detection interrupt has been generated. The bit clears to 0 after the register has been read. Current interrupt status MPU6050_RA_INT_STATUS MPU6050_INTERRUPT_MOT_BIT
References buffer, devAddr, MPU6050_INTERRUPT_MOT_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntZeroMotionStatus()
Get Zero Motion Detection interrupt status. This bit automatically sets to 1 when a Zero Motion Detection interrupt has been generated. The bit clears to 0 after the register has been read. Current interrupt status MPU6050_RA_INT_STATUS MPU6050_INTERRUPT_ZMOT_BIT
References buffer, devAddr, MPU6050_INTERRUPT_ZMOT_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntFIFOBufferOverflowStatus()
Get FIFO Buffer Overflow interrupt status. This bit automatically sets to 1 when a Free Fall interrupt has been generated. The bit clears to 0 after the register has been read. Current interrupt status MPU6050_RA_INT_STATUS MPU6050_INTERRUPT_FIFO_OFLOW_BIT
References buffer, devAddr, MPU6050_INTERRUPT_FIFO_OFLOW_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntI2CMasterStatus()
Get I2C Master interrupt status. This bit automatically sets to 1 when an I2C Master interrupt has been generated. For a list of I2C Master interrupts, please refer to Register 54. The bit clears to 0 after the register has been read. Current interrupt status MPU6050_RA_INT_STATUS MPU6050_INTERRUPT_I2C_MST_INT_BIT
References buffer, devAddr, MPU6050_INTERRUPT_I2C_MST_INT_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntDataReadyStatus()
Get Data Ready interrupt status. This bit automatically sets to 1 when a Data Ready interrupt has been generated. The bit clears to 0 after the register has been read. Current interrupt status MPU6050_RA_INT_STATUS MPU6050_INTERRUPT_DATA_RDY_BIT
References buffer, devAddr, MPU6050_INTERRUPT_DATA_RDY_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::getMotion9(int16_t *ax, int16_t *ay, int16_t *az, int16_t *gx, int16_t *gy, int16_t *gz, int16_t *mx, int16_t *my, int16_t *mz)
Get raw 9-axis motion sensor readings (accel/gyro/compass). FUNCTION NOT FULLY IMPLEMENTED YET. ax 16-bit signed integer container for accelerometer X-axis value ay 16-bit signed integer container for accelerometer Y-axis value az 16-bit signed integer container for accelerometer Z-axis value gx 16-bit signed integer container for gyroscope X-axis value gy 16-bit signed integer container for gyroscope Y-axis value gz 16-bit signed integer container for gyroscope Z-axis value mx 16-bit signed integer container for magnetometer X-axis value my 16-bit signed integer container for magnetometer Y-axis value mz 16-bit signed integer container for magnetometer Z-axis value getMotion6() getAcceleration() getRotation() MPU6050_RA_ACCEL_XOUT_H
References getMotion6.
void MPU6050_Base::getMotion6(int16_t *ax, int16_t *ay, int16_t *az, int16_t *gx, int16_t *gy, int16_t *gz)
Get raw 6-axis motion sensor readings (accel/gyro). Retrieves all currently available motion sensor values. ax 16-bit signed integer container for accelerometer X-axis value ay 16-bit signed integer container for accelerometer Y-axis value az 16-bit signed integer container for accelerometer Z-axis value gx 16-bit signed integer container for gyroscope X-axis value gy 16-bit signed integer container for gyroscope Y-axis value gz 16-bit signed integer container for gyroscope Z-axis value getAcceleration() getRotation() MPU6050_RA_ACCEL_XOUT_H
References buffer, devAddr, MPU6050_RA_ACCEL_XOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by getMotion9.
void MPU6050_Base::getAcceleration(int16_t *x, int16_t *y, int16_t *z)
Get 3-axis accelerometer readings. These registers store the most recent accelerometer measurements. Accelerometer measurements are written to these registers at the Sample Rate as defined in Register 25.The accelerometer measurement registers, along with the temperature measurement registers, gyroscope measurement registers, and external sensor data registers, are composed of two sets of registers: an internal register set and a user-facing read register set.The data within the accelerometer sensors' internal register set is always updated at the Sample Rate. Meanwhile, the user-facing read register set duplicates the internal register set's data values whenever the serial interface is idle. This guarantees that a burst read of sensor registers will read measurements from the same sampling instant. Note that if burst reads are not used, the user is responsible for ensuring a set of single byte reads correspond to a single sampling instant by checking the Data Ready interrupt.Each 16-bit accelerometer measurement has a full scale defined in ACCEL_FS (Register 28). For each full scale setting, the accelerometers' sensitivity per LSB in ACCEL_xOUT is shown in the table below: AFS_SEL | Full Scale Range | LSB Sensitivity --------+------------------+---------------- 0 | +/- 2g | 16384 LSB/mg 1 | +/- 4g | 8192 LSB/mg 2 | +/- 8g | 4096 LSB/mg 3 | +/- 16g | 2048 LSB/mg x 16-bit signed integer container for X-axis acceleration y 16-bit signed integer container for Y-axis acceleration z 16-bit signed integer container for Z-axis acceleration MPU6050_RA_GYRO_XOUT_H
References buffer, devAddr, MPU6050_RA_ACCEL_XOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getAccelerationX()
Get X-axis accelerometer reading. X-axis acceleration measurement in 16-bit 2's complement format getMotion6() MPU6050_RA_ACCEL_XOUT_H
References buffer, devAddr, MPU6050_RA_ACCEL_XOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getAccelerationY()
Get Y-axis accelerometer reading. Y-axis acceleration measurement in 16-bit 2's complement format getMotion6() MPU6050_RA_ACCEL_YOUT_H
References buffer, devAddr, MPU6050_RA_ACCEL_YOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getAccelerationZ()
Get Z-axis accelerometer reading. Z-axis acceleration measurement in 16-bit 2's complement format getMotion6() MPU6050_RA_ACCEL_ZOUT_H
References buffer, devAddr, MPU6050_RA_ACCEL_ZOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getTemperature()
Get current internal temperature. Temperature reading in 16-bit 2's complement format MPU6050_RA_TEMP_OUT_H
References buffer, devAddr, MPU6050_RA_TEMP_OUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by MPU::get_temp, MPU::jsonResult, MPU::toString.
void MPU6050_Base::getRotation(int16_t *x, int16_t *y, int16_t *z)
Get 3-axis gyroscope readings. These gyroscope measurement registers, along with the accelerometer measurement registers, temperature measurement registers, and external sensor data registers, are composed of two sets of registers: an internal register set and a user-facing read register set. The data within the gyroscope sensors' internal register set is always updated at the Sample Rate. Meanwhile, the user-facing read register set duplicates the internal register set's data values whenever the serial interface is idle. This guarantees that a burst read of sensor registers will read measurements from the same sampling instant. Note that if burst reads are not used, the user is responsible for ensuring a set of single byte reads correspond to a single sampling instant by checking the Data Ready interrupt.Each 16-bit gyroscope measurement has a full scale defined in FS_SEL (Register 27). For each full scale setting, the gyroscopes' sensitivity per LSB in GYRO_xOUT is shown in the table below: FS_SEL | Full Scale Range | LSB Sensitivity -------+--------------------+---------------- 0 | +/- 250 degrees/s | 131 LSB/deg/s 1 | +/- 500 degrees/s | 65.5 LSB/deg/s 2 | +/- 1000 degrees/s | 32.8 LSB/deg/s 3 | +/- 2000 degrees/s | 16.4 LSB/deg/s x 16-bit signed integer container for X-axis rotation y 16-bit signed integer container for Y-axis rotation z 16-bit signed integer container for Z-axis rotation getMotion6() MPU6050_RA_GYRO_XOUT_H
References buffer, devAddr, MPU6050_RA_GYRO_XOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getRotationX()
Get X-axis gyroscope reading. X-axis rotation measurement in 16-bit 2's complement format getMotion6() MPU6050_RA_GYRO_XOUT_H
References buffer, devAddr, MPU6050_RA_GYRO_XOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getRotationY()
Get Y-axis gyroscope reading. Y-axis rotation measurement in 16-bit 2's complement format getMotion6() MPU6050_RA_GYRO_YOUT_H
References buffer, devAddr, MPU6050_RA_GYRO_YOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
int16_t MPU6050_Base::getRotationZ()
Get Z-axis gyroscope reading. Z-axis rotation measurement in 16-bit 2's complement format getMotion6() MPU6050_RA_GYRO_ZOUT_H
References buffer, devAddr, MPU6050_RA_GYRO_ZOUT_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getExternalSensorByte(int position)
Read single byte from external sensor data register. These registers store data read from external sensors by the Slave 0, 1, 2, and 3 on the auxiliary I2C interface. Data read by Slave 4 is stored in I2C_SLV4_DI (Register 53).External sensor data is written to these registers at the Sample Rate as defined in Register 25. This access rate can be reduced by using the Slave Delay Enable registers (Register 103).External sensor data registers, along with the gyroscope measurement registers, accelerometer measurement registers, and temperature measurement registers, are composed of two sets of registers: an internal register set and a user-facing read register set.The data within the external sensors' internal register set is always updated at the Sample Rate (or the reduced access rate) whenever the serial interface is idle. This guarantees that a burst read of sensor registers will read measurements from the same sampling instant. Note that if burst reads are not used, the user is responsible for ensuring a set of single byte reads correspond to a single sampling instant by checking the Data Ready interrupt.Data is placed in these external sensor data registers according to I2C_SLV0_CTRL, I2C_SLV1_CTRL, I2C_SLV2_CTRL, and I2C_SLV3_CTRL (Registers 39, 42, 45, and 48). When more than zero bytes are read (I2C_SLVx_LEN > 0) from an enabled slave (I2C_SLVx_EN = 1), the slave is read at the Sample Rate (as defined in Register 25) or delayed rate (if specified in Register 52 and 103). During each Sample cycle, slave reads are performed in order of Slave number. If all slaves are enabled with more than zero bytes to be read, the order will be Slave 0, followed by Slave 1, Slave 2, and Slave 3.Each enabled slave will have EXT_SENS_DATA registers associated with it by number of bytes read (I2C_SLVx_LEN) in order of slave number, starting from EXT_SENS_DATA_00. Note that this means enabling or disabling a slave may change the higher numbered slaves' associated registers. Furthermore, if fewer total bytes are being read from the external sensors as a result of such a change, then the data remaining in the registers which no longer have an associated slave device (i.e. high numbered registers) will remain in these previously allocated registers unless reset.If the sum of the read lengths of all SLVx transactions exceed the number of available EXT_SENS_DATA registers, the excess bytes will be dropped. There are 24 EXT_SENS_DATA registers and hence the total read lengths between all the slaves cannot be greater than 24 or some bytes will be lost.Note: Slave 4's behavior is distinct from that of Slaves 0-3. For further information regarding the characteristics of Slave 4, please refer to Registers 49 to 53.EXAMPLE: Suppose that Slave 0 is enabled with 4 bytes to be read (I2C_SLV0_EN = 1 and I2C_SLV0_LEN = 4) while Slave 1 is enabled with 2 bytes to be read so that I2C_SLV1_EN = 1 and I2C_SLV1_LEN = 2. In such a situation, EXT_SENS_DATA _00 through _03 will be associated with Slave 0, while EXT_SENS_DATA _04 and 05 will be associated with Slave 1. If Slave 2 is enabled as well, registers starting from EXT_SENS_DATA_06 will be allocated to Slave 2.If Slave 2 is disabled while Slave 3 is enabled in this same situation, then registers starting from EXT_SENS_DATA_06 will be allocated to Slave 3 instead.REGISTER ALLOCATION FOR DYNAMIC DISABLE VS. NORMAL DISABLE: If a slave is disabled at any time, the space initially allocated to the slave in the EXT_SENS_DATA register, will remain associated with that slave. This is to avoid dynamic adjustment of the register allocation.The allocation of the EXT_SENS_DATA registers is recomputed only when (1) all slaves are disabled, or (2) the I2C_MST_RST bit is set (Register 106).This above is also true if one of the slaves gets NACKed and stops functioning. position Starting position (0-23) Byte read from register
References buffer, devAddr, MPU6050_RA_EXT_SENS_DATA_00, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
uint16_t MPU6050_Base::getExternalSensorWord(int position)
Read word (2 bytes) from external sensor data registers. position Starting position (0-21) Word read from register getExternalSensorByte()
References buffer, devAddr, MPU6050_RA_EXT_SENS_DATA_00, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
uint32_t MPU6050_Base::getExternalSensorDWord(int position)
Read double word (4 bytes) from external sensor data registers. position Starting position (0-20) Double word read from registers getExternalSensorByte()
References buffer, devAddr, MPU6050_RA_EXT_SENS_DATA_00, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
uint8_t MPU6050_Base::getMotionStatus()
Get full motion detection status register content (all bits). Motion detection status byte MPU6050_RA_MOT_DETECT_STATUS
References buffer, devAddr, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getXNegMotionDetected()
Get X-axis negative motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_XNEG_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_XNEG_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getXPosMotionDetected()
Get X-axis positive motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_XPOS_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_XPOS_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getYNegMotionDetected()
Get Y-axis negative motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_YNEG_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_YNEG_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getYPosMotionDetected()
Get Y-axis positive motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_YPOS_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_YPOS_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getZNegMotionDetected()
Get Z-axis negative motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_ZNEG_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_ZNEG_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getZPosMotionDetected()
Get Z-axis positive motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_ZPOS_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_ZPOS_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getZeroMotionDetected()
Get zero motion detection interrupt status. Motion detection status MPU6050_RA_MOT_DETECT_STATUS MPU6050_MOTION_MOT_ZRMOT_BIT
References buffer, devAddr, MPU6050_MOTION_MOT_ZRMOT_BIT, MPU6050_RA_MOT_DETECT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveOutputByte(uint8_t num, uint8_t data)
Write byte to Data Output container for specified slave. This register holds the output data written into Slave when Slave is set to write mode. For further information regarding Slave control, please refer to Registers 37 to 39 and immediately following. num Slave number (0-3) data Byte to write MPU6050_RA_I2C_SLV0_DO
References devAddr, MPU6050_RA_I2C_SLV0_DO, wireObj, I2Cdev::writeByte.
bool MPU6050_Base::getExternalShadowDelayEnabled()
Get external data shadow delay enabled status. This register is used to specify the timing of external sensor data shadowing. When DELAY_ES_SHADOW is set to 1, shadowing of external sensor data is delayed until all data has been received. Current external data shadow delay enabled status. MPU6050_RA_I2C_MST_DELAY_CTRL MPU6050_DELAYCTRL_DELAY_ES_SHADOW_BIT
References buffer, devAddr, MPU6050_DELAYCTRL_DELAY_ES_SHADOW_BIT, MPU6050_RA_I2C_MST_DELAY_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setExternalShadowDelayEnabled(bool enabled)
Set external data shadow delay enabled status. enabled New external data shadow delay enabled status. getExternalShadowDelayEnabled() MPU6050_RA_I2C_MST_DELAY_CTRL MPU6050_DELAYCTRL_DELAY_ES_SHADOW_BIT
References devAddr, MPU6050_DELAYCTRL_DELAY_ES_SHADOW_BIT, MPU6050_RA_I2C_MST_DELAY_CTRL, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getSlaveDelayEnabled(uint8_t num)
Get slave delay enabled status. When a particular slave delay is enabled, the rate of access for the that slave device is reduced. When a slave's access rate is decreased relative to the Sample Rate, the slave is accessed every: 1 / (1 + I2C_MST_DLY) Samples This base Sample Rate in turn is determined by SMPLRT_DIV (register * 25) and DLPF_CFG (register 26).For further information regarding I2C_MST_DLY, please refer to register 52. For further information regarding the Sample Rate, please refer to register 25. num Slave number (0-4) Current slave delay enabled status. MPU6050_RA_I2C_MST_DELAY_CTRL MPU6050_DELAYCTRL_I2C_SLV0_DLY_EN_BIT
References buffer, devAddr, MPU6050_RA_I2C_MST_DELAY_CTRL, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSlaveDelayEnabled(uint8_t num, bool enabled)
Set slave delay enabled status. num Slave number (0-4) enabled New slave delay enabled status. MPU6050_RA_I2C_MST_DELAY_CTRL MPU6050_DELAYCTRL_I2C_SLV0_DLY_EN_BIT
References devAddr, MPU6050_RA_I2C_MST_DELAY_CTRL, wireObj, I2Cdev::writeBit.
void MPU6050_Base::resetGyroscopePath()
Reset gyroscope signal path. The reset will revert the signal path analog to digital converters and filters to their power up configurations. MPU6050_RA_SIGNAL_PATH_RESET MPU6050_PATHRESET_GYRO_RESET_BIT
References devAddr, MPU6050_PATHRESET_GYRO_RESET_BIT, MPU6050_RA_SIGNAL_PATH_RESET, wireObj, I2Cdev::writeBit.
void MPU6050_Base::resetAccelerometerPath()
Reset accelerometer signal path. The reset will revert the signal path analog to digital converters and filters to their power up configurations. MPU6050_RA_SIGNAL_PATH_RESET MPU6050_PATHRESET_ACCEL_RESET_BIT
References devAddr, MPU6050_PATHRESET_ACCEL_RESET_BIT, MPU6050_RA_SIGNAL_PATH_RESET, wireObj, I2Cdev::writeBit.
void MPU6050_Base::resetTemperaturePath()
Reset temperature sensor signal path. The reset will revert the signal path analog to digital converters and filters to their power up configurations. MPU6050_RA_SIGNAL_PATH_RESET MPU6050_PATHRESET_TEMP_RESET_BIT
References devAddr, MPU6050_PATHRESET_TEMP_RESET_BIT, MPU6050_RA_SIGNAL_PATH_RESET, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getAccelerometerPowerOnDelay()
Get accelerometer power-on delay. The accelerometer data path provides samples to the sensor registers, Motion detection, Zero Motion detection, and Free Fall detection modules. The signal path contains filters which must be flushed on wake-up with new samples before the detection modules begin operations. The default wake-up delay, of 4ms can be lengthened by up to 3ms. This additional delay is specified in ACCEL_ON_DELAY in units of 1 LSB = 1 ms. The user may select any value above zero unless instructed otherwise by InvenSense. Please refer to Section 8 of the MPU-6000/MPU-6050 Product Specification document for further information regarding the detection modules. Current accelerometer power-on delay MPU6050_RA_MOT_DETECT_CTRL MPU6050_DETECT_ACCEL_ON_DELAY_BIT
References buffer, devAddr, MPU6050_DETECT_ACCEL_ON_DELAY_BIT, MPU6050_DETECT_ACCEL_ON_DELAY_LENGTH, MPU6050_RA_MOT_DETECT_CTRL, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setAccelerometerPowerOnDelay(uint8_t delay)
Set accelerometer power-on delay. delay New accelerometer power-on delay (0-3) getAccelerometerPowerOnDelay() MPU6050_RA_MOT_DETECT_CTRL MPU6050_DETECT_ACCEL_ON_DELAY_BIT
References devAddr, MPU6050_DETECT_ACCEL_ON_DELAY_BIT, MPU6050_DETECT_ACCEL_ON_DELAY_LENGTH, MPU6050_RA_MOT_DETECT_CTRL, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getFreefallDetectionCounterDecrement()
Get Free Fall detection counter decrement configuration. Detection is registered by the Free Fall detection module after accelerometer measurements meet their respective threshold conditions over a specified number of samples. When the threshold conditions are met, the corresponding detection counter increments by 1. The user may control the rate at which the detection counter decrements when the threshold condition is not met by configuring FF_COUNT. The decrement rate can be set according to the following table: FF_COUNT | Counter Decrement ---------+------------------ 0 | Reset 1 | 1 2 | 2 3 | 4 When FF_COUNT is configured to 0 (reset), any non-qualifying sample will reset the counter to 0. For further information on Free Fall detection, please refer to Registers 29 to 32.Current decrement configuration MPU6050_RA_MOT_DETECT_CTRL MPU6050_DETECT_FF_COUNT_BIT
References buffer, devAddr, MPU6050_DETECT_FF_COUNT_BIT, MPU6050_DETECT_FF_COUNT_LENGTH, MPU6050_RA_MOT_DETECT_CTRL, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFreefallDetectionCounterDecrement(uint8_t decrement)
Set Free Fall detection counter decrement configuration. decrement New decrement configuration value getFreefallDetectionCounterDecrement() MPU6050_RA_MOT_DETECT_CTRL MPU6050_DETECT_FF_COUNT_BIT
References devAddr, MPU6050_DETECT_FF_COUNT_BIT, MPU6050_DETECT_FF_COUNT_LENGTH, MPU6050_RA_MOT_DETECT_CTRL, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getMotionDetectionCounterDecrement()
Get Motion detection counter decrement configuration. Detection is registered by the Motion detection module after accelerometer measurements meet their respective threshold conditions over a specified number of samples. When the threshold conditions are met, the corresponding detection counter increments by 1. The user may control the rate at which the detection counter decrements when the threshold condition is not met by configuring MOT_COUNT. The decrement rate can be set according to the following table: MOT_COUNT | Counter Decrement ----------+------------------ 0 | Reset 1 | 1 2 | 2 3 | 4 When MOT_COUNT is configured to 0 (reset), any non-qualifying sample will reset the counter to 0. For further information on Motion detection, please refer to Registers 29 to 32.
References buffer, devAddr, MPU6050_DETECT_MOT_COUNT_BIT, MPU6050_DETECT_MOT_COUNT_LENGTH, MPU6050_RA_MOT_DETECT_CTRL, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setMotionDetectionCounterDecrement(uint8_t decrement)
Set Motion detection counter decrement configuration. decrement New decrement configuration value getMotionDetectionCounterDecrement() MPU6050_RA_MOT_DETECT_CTRL MPU6050_DETECT_MOT_COUNT_BIT
References devAddr, MPU6050_DETECT_MOT_COUNT_BIT, MPU6050_DETECT_MOT_COUNT_LENGTH, MPU6050_RA_MOT_DETECT_CTRL, wireObj, I2Cdev::writeBits.
bool MPU6050_Base::getFIFOEnabled()
Get FIFO enabled status. When this bit is set to 0, the FIFO buffer is disabled. The FIFO buffer cannot be written to or read from while disabled. The FIFO buffer's state does not change unless the MPU-60X0 is power cycled. Current FIFO enabled status MPU6050_RA_USER_CTRL MPU6050_USERCTRL_FIFO_EN_BIT
References buffer, devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_FIFO_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setFIFOEnabled(bool enabled)
Set FIFO enabled status. enabled New FIFO enabled status getFIFOEnabled() MPU6050_RA_USER_CTRL MPU6050_USERCTRL_FIFO_EN_BIT
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_FIFO_EN_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize.
bool MPU6050_Base::getI2CMasterModeEnabled()
Get I2C Master Mode enabled status. When this mode is enabled, the MPU-60X0 acts as the I2C Master to the external sensor slave devices on the auxiliary I2C bus. When this bit is cleared to 0, the auxiliary I2C bus lines (AUX_DA and AUX_CL) are logically driven by the primary I2C bus (SDA and SCL). This is a precondition to enabling Bypass Mode. For further information regarding Bypass Mode, please refer to Register 55. Current I2C Master Mode enabled status MPU6050_RA_USER_CTRL MPU6050_USERCTRL_I2C_MST_EN_BIT
References buffer, devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_I2C_MST_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setI2CMasterModeEnabled(bool enabled)
Set I2C Master Mode enabled status. enabled New I2C Master Mode enabled status getI2CMasterModeEnabled() MPU6050_RA_USER_CTRL MPU6050_USERCTRL_I2C_MST_EN_BIT
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_I2C_MST_EN_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize.
void MPU6050_Base::switchSPIEnabled(bool enabled)
Switch from I2C to SPI mode (MPU-6000 only) If this is set, the primary SPI interface will be enabled in place of the disabled primary I2C interface.
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_I2C_IF_DIS_BIT, wireObj, I2Cdev::writeBit.
void MPU6050_Base::resetFIFO()
Reset the FIFO. This bit resets the FIFO buffer when set to 1 while FIFO_EN equals 0. This bit automatically clears to 0 after the reset has been triggered. MPU6050_RA_USER_CTRL MPU6050_USERCTRL_FIFO_RESET_BIT
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_FIFO_RESET_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, GetCurrentFIFOPacket, PID.
void MPU6050_Base::resetI2CMaster()
Reset the I2C Master. This bit resets the I2C Master when set to 1 while I2C_MST_EN equals 0. This bit automatically clears to 0 after the reset has been triggered. MPU6050_RA_USER_CTRL MPU6050_USERCTRL_I2C_MST_RESET_BIT
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_I2C_MST_RESET_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize.
void MPU6050_Base::resetSensors()
Reset all sensor registers and signal paths. When set to 1, this bit resets the signal paths for all sensors (gyroscopes, accelerometers, and temperature sensor). This operation will also clear the sensor registers. This bit automatically clears to 0 after the reset has been triggered.When resetting only the signal path (and not the sensor registers), please use Register 104, SIGNAL_PATH_RESET.MPU6050_RA_USER_CTRL MPU6050_USERCTRL_SIG_COND_RESET_BIT
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_SIG_COND_RESET_BIT, wireObj, I2Cdev::writeBit.
void MPU6050_Base::reset()
Trigger a full device reset. A small delay of ~50ms may be desirable after triggering a reset. MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_DEVICE_RESET_BIT
References devAddr, MPU6050_PWR1_DEVICE_RESET_BIT, MPU6050_RA_PWR_MGMT_1, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
bool MPU6050_Base::getSleepEnabled()
Get sleep mode status. Setting the SLEEP bit in the register puts the device into very low power sleep mode. In this mode, only the serial interface and internal registers remain active, allowing for a very low standby current. Clearing this bit puts the device back into normal mode. To save power, the individual standby selections for each of the gyros should be used if any gyro axis is not used by the application. Current sleep mode enabled status MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_SLEEP_BIT
References buffer, devAddr, MPU6050_PWR1_SLEEP_BIT, MPU6050_RA_PWR_MGMT_1, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setSleepEnabled(bool enabled)
Set sleep mode status. enabled New sleep mode enabled status getSleepEnabled() MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_SLEEP_BIT
References devAddr, MPU6050_PWR1_SLEEP_BIT, MPU6050_RA_PWR_MGMT_1, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, initialize.
bool MPU6050_Base::getWakeCycleEnabled()
Get wake cycle enabled status. When this bit is set to 1 and SLEEP is disabled, the MPU-60X0 will cycle between sleep mode and waking up to take a single sample of data from active sensors at a rate determined by LP_WAKE_CTRL (register 108). Current sleep mode enabled status MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_CYCLE_BIT
References buffer, devAddr, MPU6050_PWR1_CYCLE_BIT, MPU6050_RA_PWR_MGMT_1, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setWakeCycleEnabled(bool enabled)
Set wake cycle enabled status. enabled New sleep mode enabled status getWakeCycleEnabled() MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_CYCLE_BIT
References devAddr, MPU6050_PWR1_CYCLE_BIT, MPU6050_RA_PWR_MGMT_1, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getTempSensorEnabled()
Get temperature sensor enabled status. Control the usage of the internal temperature sensor.Note: this register stores the disabled value, but for consistency with the rest of the code, the function is named and used with standard true/false values to indicate whether the sensor is enabled or disabled, respectively.Current temperature sensor enabled status MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_TEMP_DIS_BIT
References buffer, devAddr, MPU6050_PWR1_TEMP_DIS_BIT, MPU6050_RA_PWR_MGMT_1, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setTempSensorEnabled(bool enabled)
Set temperature sensor enabled status. Note: this register stores the disabled value, but for consistency with the rest of the code, the function is named and used with standard true/false values to indicate whether the sensor is enabled or disabled, respectively. enabled New temperature sensor enabled status getTempSensorEnabled() MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_TEMP_DIS_BIT
References devAddr, MPU6050_PWR1_TEMP_DIS_BIT, MPU6050_RA_PWR_MGMT_1, wireObj, I2Cdev::writeBit.
uint8_t MPU6050_Base::getClockSource()
Get clock source setting. Current clock source setting MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_CLKSEL_BIT MPU6050_PWR1_CLKSEL_LENGTH
References buffer, devAddr, MPU6050_PWR1_CLKSEL_BIT, MPU6050_PWR1_CLKSEL_LENGTH, MPU6050_RA_PWR_MGMT_1, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setClockSource(uint8_t source)
Set clock source setting. An internal 8MHz oscillator, gyroscope based clock, or external sources can be selected as the MPU-60X0 clock source. When the internal 8 MHz oscillator or an external source is chosen as the clock source, the MPU-60X0 can operate in low power modes with the gyroscopes disabled.Upon power up, the MPU-60X0 clock source defaults to the internal oscillator. However, it is highly recommended that the device be configured to use one of the gyroscopes (or an external clock source) as the clock reference for improved stability. The clock source can be selected according to the following table: CLK_SEL | Clock Source --------+-------------------------------------- 0 | Internal oscillator 1 | PLL with X Gyro reference 2 | PLL with Y Gyro reference 3 | PLL with Z Gyro reference 4 | PLL with external 32.768kHz reference 5 | PLL with external 19.2MHz reference 6 | Reserved 7 | Stops the clock and keeps the timing generator in reset source New clock source setting getClockSource() MPU6050_RA_PWR_MGMT_1 MPU6050_PWR1_CLKSEL_BIT MPU6050_PWR1_CLKSEL_LENGTH
References devAddr, MPU6050_PWR1_CLKSEL_BIT, MPU6050_PWR1_CLKSEL_LENGTH, MPU6050_RA_PWR_MGMT_1, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, initialize.
uint8_t MPU6050_Base::getWakeFrequency()
Get wake frequency in Accel-Only Low Power Mode. The MPU-60X0 can be put into Accerlerometer Only Low Power Mode by setting PWRSEL to 1 in the Power Management 1 register (Register 107). In this mode, the device will power off all devices except for the primary I2C interface, waking only the accelerometer at fixed intervals to take a single measurement. The frequency of wake-ups can be configured with LP_WAKE_CTRL as shown below: LP_WAKE_CTRL | Wake-up Frequency -------------+------------------ 0 | 1.25 Hz 1 | 2.5 Hz 2 | 20 Hz 3 | 40 Hz For further information regarding the MPU-60X0's power modes, please refer to Register 107.Current wake frequency MPU6050_RA_PWR_MGMT_2
References buffer, devAddr, MPU6050_PWR2_LP_WAKE_CTRL_BIT, MPU6050_PWR2_LP_WAKE_CTRL_LENGTH, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setWakeFrequency(uint8_t frequency)
Set wake frequency in Accel-Only Low Power Mode. frequency New wake frequency MPU6050_RA_PWR_MGMT_2
References devAddr, MPU6050_PWR2_LP_WAKE_CTRL_BIT, MPU6050_PWR2_LP_WAKE_CTRL_LENGTH, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBits.
bool MPU6050_Base::getStandbyXAccelEnabled()
Get X-axis accelerometer standby enabled status. If enabled, the X-axis will not gather or report data (or use power). Current X-axis standby enabled status MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_XA_BIT
References buffer, devAddr, MPU6050_PWR2_STBY_XA_BIT, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setStandbyXAccelEnabled(bool enabled)
Set X-axis accelerometer standby enabled status. New X-axis standby enabled status getStandbyXAccelEnabled() MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_XA_BIT
References devAddr, MPU6050_PWR2_STBY_XA_BIT, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getStandbyYAccelEnabled()
Get Y-axis accelerometer standby enabled status. If enabled, the Y-axis will not gather or report data (or use power). Current Y-axis standby enabled status MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_YA_BIT
References buffer, devAddr, MPU6050_PWR2_STBY_YA_BIT, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setStandbyYAccelEnabled(bool enabled)
Set Y-axis accelerometer standby enabled status. New Y-axis standby enabled status getStandbyYAccelEnabled() MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_YA_BIT
References devAddr, MPU6050_PWR2_STBY_YA_BIT, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getStandbyZAccelEnabled()
Get Z-axis accelerometer standby enabled status. If enabled, the Z-axis will not gather or report data (or use power). Current Z-axis standby enabled status MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_ZA_BIT
References buffer, devAddr, MPU6050_PWR2_STBY_ZA_BIT, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setStandbyZAccelEnabled(bool enabled)
Set Z-axis accelerometer standby enabled status. New Z-axis standby enabled status getStandbyZAccelEnabled() MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_ZA_BIT
References devAddr, MPU6050_PWR2_STBY_ZA_BIT, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getStandbyXGyroEnabled()
Get X-axis gyroscope standby enabled status. If enabled, the X-axis will not gather or report data (or use power). Current X-axis standby enabled status MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_XG_BIT
References buffer, devAddr, MPU6050_PWR2_STBY_XG_BIT, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setStandbyXGyroEnabled(bool enabled)
Set X-axis gyroscope standby enabled status. New X-axis standby enabled status getStandbyXGyroEnabled() MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_XG_BIT
References devAddr, MPU6050_PWR2_STBY_XG_BIT, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getStandbyYGyroEnabled()
Get Y-axis gyroscope standby enabled status. If enabled, the Y-axis will not gather or report data (or use power). Current Y-axis standby enabled status MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_YG_BIT
References buffer, devAddr, MPU6050_PWR2_STBY_YG_BIT, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setStandbyYGyroEnabled(bool enabled)
Set Y-axis gyroscope standby enabled status. New Y-axis standby enabled status getStandbyYGyroEnabled() MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_YG_BIT
References devAddr, MPU6050_PWR2_STBY_YG_BIT, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getStandbyZGyroEnabled()
Get Z-axis gyroscope standby enabled status. If enabled, the Z-axis will not gather or report data (or use power). Current Z-axis standby enabled status MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_ZG_BIT
References buffer, devAddr, MPU6050_PWR2_STBY_ZG_BIT, MPU6050_RA_PWR_MGMT_2, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setStandbyZGyroEnabled(bool enabled)
Set Z-axis gyroscope standby enabled status. New Z-axis standby enabled status getStandbyZGyroEnabled() MPU6050_RA_PWR_MGMT_2 MPU6050_PWR2_STBY_ZG_BIT
References devAddr, MPU6050_PWR2_STBY_ZG_BIT, MPU6050_RA_PWR_MGMT_2, wireObj, I2Cdev::writeBit.
uint16_t MPU6050_Base::getFIFOCount()
Get current FIFO buffer size. This value indicates the number of bytes stored in the FIFO buffer. This number is in turn the number of bytes that can be read from the FIFO buffer and it is directly proportional to the number of samples available given the set of sensor data bound to be stored in the FIFO (register 35 and 36). Current FIFO buffer size
References buffer, devAddr, MPU6050_RA_FIFO_COUNTH, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpPacketAvailable, MPU6050_6Axis_MotionApps20::dmpPacketAvailable, GetCurrentFIFOPacket.
uint8_t MPU6050_Base::getFIFOByte()
Get byte from FIFO buffer. This register is used to read and write data from the FIFO buffer. Data is written to the FIFO in order of register number (from lowest to highest). If all the FIFO enable flags (see below) are enabled and all External Sensor Data registers (Registers 73 to 96) are associated with a Slave device, the contents of registers 59 through 96 will be written in order at the Sample Rate.The contents of the sensor data registers (Registers 59 to 96) are written into the FIFO buffer when their corresponding FIFO enable flags are set to 1 in FIFO_EN (Register 35). An additional flag for the sensor data registers associated with I2C Slave 3 can be found in I2C_MST_CTRL (Register 36).If the FIFO buffer has overflowed, the status bit FIFO_OFLOW_INT is automatically set to 1. This bit is located in INT_STATUS (Register 58). When the FIFO buffer has overflowed, the oldest data will be lost and new data will be written to the FIFO.If the FIFO buffer is empty, reading this register will return the last byte that was previously read from the FIFO until new data is available. The user should check FIFO_COUNT to ensure that the FIFO buffer is not read when empty.Byte from FIFO buffer
References buffer, devAddr, MPU6050_RA_FIFO_R_W, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
int8_t MPU6050_Base::GetCurrentFIFOPacket(uint8_t *data, uint8_t length)
Get latest byte from FIFO buffer no matter how much time has passed. === GetCurrentFIFOPacket === Returns 1) when nothing special was done 2) when recovering from overflow 0) when no valid data is available
References getFIFOBytes, getFIFOCount, getFIFOTimeout, I2CDEVLIB_WIRE_BUFFER_LENGTH, resetFIFO.
Referenced by MPU6050_6Axis_MotionApps20::dmpGetCurrentFIFOPacket.
void MPU6050_Base::setFIFOByte(uint8_t data)
Write byte to FIFO buffer. getFIFOByte() MPU6050_RA_FIFO_R_W
References devAddr, MPU6050_RA_FIFO_R_W, wireObj, I2Cdev::writeByte.
void MPU6050_Base::getFIFOBytes(uint8_t *data, uint8_t length)
References devAddr, MPU6050_RA_FIFO_R_W, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, MPU6050_6Axis_MotionApps20::dmpReadAndProcessFIFOPacket, MPU6050_9Axis_MotionApps41::dmpReadAndProcessFIFOPacket, GetCurrentFIFOPacket.
void MPU6050_Base::setFIFOTimeout(uint32_t fifoTimeout)
Set timeout to get a packet from FIFO buffer. New timeout to get a packet from FIFO buffer MPU6050_FIFO_DEFAULT_TIMEOUT
References fifoTimeout.
uint32_t MPU6050_Base::getFIFOTimeout()
Get timeout to get a packet from FIFO buffer. Current timeout to get a packet from FIFO buffer MPU6050_FIFO_DEFAULT_TIMEOUT
References fifoTimeout.
Referenced by GetCurrentFIFOPacket.
uint8_t MPU6050_Base::getDeviceID()
Get Device ID. This register is used to verify the identity of the device (0b110100, 0x34). Device ID (6 bits only! should be 0x34) MPU6050_RA_WHO_AM_I MPU6050_WHO_AM_I_BIT MPU6050_WHO_AM_I_LENGTH
References buffer, devAddr, MPU6050_RA_WHO_AM_I, MPU6050_WHO_AM_I_BIT, MPU6050_WHO_AM_I_LENGTH, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
Referenced by getXAccelOffset, getYAccelOffset, getZAccelOffset, PID, PrintActiveOffsets, setXAccelOffset, setYAccelOffset, setZAccelOffset, testConnection.
void MPU6050_Base::setDeviceID(uint8_t id)
Set Device ID. Write a new ID into the WHO_AM_I register (no idea why this should ever be necessary though). id New device ID to set. getDeviceID() MPU6050_RA_WHO_AM_I MPU6050_WHO_AM_I_BIT MPU6050_WHO_AM_I_LENGTH
References devAddr, MPU6050_RA_WHO_AM_I, MPU6050_WHO_AM_I_BIT, MPU6050_WHO_AM_I_LENGTH, wireObj, I2Cdev::writeBits.
uint8_t MPU6050_Base::getOTPBankValid()
References buffer, devAddr, MPU6050_RA_XG_OFFS_TC, MPU6050_TC_OTP_BNK_VLD_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
void MPU6050_Base::setOTPBankValid(bool enabled)
References devAddr, MPU6050_RA_XG_OFFS_TC, MPU6050_TC_OTP_BNK_VLD_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
int8_t MPU6050_Base::getXGyroOffsetTC()
References buffer, devAddr, MPU6050_RA_XG_OFFS_TC, MPU6050_TC_OFFSET_BIT, MPU6050_TC_OFFSET_LENGTH, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setXGyroOffsetTC(int8_t offset)
References devAddr, MPU6050_RA_XG_OFFS_TC, MPU6050_TC_OFFSET_BIT, MPU6050_TC_OFFSET_LENGTH, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
int8_t MPU6050_Base::getYGyroOffsetTC()
References buffer, devAddr, MPU6050_RA_YG_OFFS_TC, MPU6050_TC_OFFSET_BIT, MPU6050_TC_OFFSET_LENGTH, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setYGyroOffsetTC(int8_t offset)
References devAddr, MPU6050_RA_YG_OFFS_TC, MPU6050_TC_OFFSET_BIT, MPU6050_TC_OFFSET_LENGTH, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
int8_t MPU6050_Base::getZGyroOffsetTC()
References buffer, devAddr, MPU6050_RA_ZG_OFFS_TC, MPU6050_TC_OFFSET_BIT, MPU6050_TC_OFFSET_LENGTH, I2Cdev::readBits, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setZGyroOffsetTC(int8_t offset)
References devAddr, MPU6050_RA_ZG_OFFS_TC, MPU6050_TC_OFFSET_BIT, MPU6050_TC_OFFSET_LENGTH, wireObj, I2Cdev::writeBits.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
int8_t MPU6050_Base::getXFineGain()
References buffer, devAddr, MPU6050_RA_X_FINE_GAIN, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setXFineGain(int8_t gain)
References devAddr, MPU6050_RA_X_FINE_GAIN, wireObj, I2Cdev::writeByte.
int8_t MPU6050_Base::getYFineGain()
References buffer, devAddr, MPU6050_RA_Y_FINE_GAIN, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setYFineGain(int8_t gain)
References devAddr, MPU6050_RA_Y_FINE_GAIN, wireObj, I2Cdev::writeByte.
int8_t MPU6050_Base::getZFineGain()
References buffer, devAddr, MPU6050_RA_Z_FINE_GAIN, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setZFineGain(int8_t gain)
References devAddr, MPU6050_RA_Z_FINE_GAIN, wireObj, I2Cdev::writeByte.
int16_t MPU6050_Base::getXAccelOffset()
References buffer, devAddr, getDeviceID, MPU6050_RA_XA_OFFS_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setXAccelOffset(int16_t offset)
References devAddr, getDeviceID, MPU6050_RA_XA_OFFS_H, wireObj, I2Cdev::writeWord.
Referenced by MPU::init.
int16_t MPU6050_Base::getYAccelOffset()
References buffer, devAddr, getDeviceID, MPU6050_RA_YA_OFFS_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setYAccelOffset(int16_t offset)
References devAddr, getDeviceID, MPU6050_RA_YA_OFFS_H, wireObj, I2Cdev::writeWord.
Referenced by MPU::init.
int16_t MPU6050_Base::getZAccelOffset()
References buffer, devAddr, getDeviceID, MPU6050_RA_ZA_OFFS_H, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setZAccelOffset(int16_t offset)
References devAddr, getDeviceID, MPU6050_RA_ZA_OFFS_H, wireObj, I2Cdev::writeWord.
Referenced by MPU::init.
int16_t MPU6050_Base::getXGyroOffset()
References buffer, devAddr, MPU6050_RA_XG_OFFS_USRH, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
void MPU6050_Base::setXGyroOffset(int16_t offset)
References devAddr, MPU6050_RA_XG_OFFS_USRH, wireObj, I2Cdev::writeWord.
Referenced by MPU::init, MPU::resetAxis.
int16_t MPU6050_Base::getYGyroOffset()
References buffer, devAddr, MPU6050_RA_YG_OFFS_USRH, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
void MPU6050_Base::setYGyroOffset(int16_t offset)
References devAddr, MPU6050_RA_YG_OFFS_USRH, wireObj, I2Cdev::writeWord.
Referenced by MPU::init, MPU::resetAxis.
int16_t MPU6050_Base::getZGyroOffset()
References buffer, devAddr, MPU6050_RA_ZG_OFFS_USRH, I2Cdev::readBytes, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
void MPU6050_Base::setZGyroOffset(int16_t offset)
References devAddr, MPU6050_RA_ZG_OFFS_USRH, wireObj, I2Cdev::writeWord.
Referenced by MPU::init, MPU::resetAxis.
bool MPU6050_Base::getIntPLLReadyEnabled()
References buffer, devAddr, MPU6050_INTERRUPT_PLL_RDY_INT_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntPLLReadyEnabled(bool enabled)
References devAddr, MPU6050_INTERRUPT_PLL_RDY_INT_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getIntDMPEnabled()
References buffer, devAddr, MPU6050_INTERRUPT_DMP_INT_BIT, MPU6050_RA_INT_ENABLE, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setIntDMPEnabled(bool enabled)
References devAddr, MPU6050_INTERRUPT_DMP_INT_BIT, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeBit.
bool MPU6050_Base::getDMPInt5Status()
References buffer, devAddr, MPU6050_DMPINT_5_BIT, MPU6050_RA_DMP_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getDMPInt4Status()
References buffer, devAddr, MPU6050_DMPINT_4_BIT, MPU6050_RA_DMP_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getDMPInt3Status()
References buffer, devAddr, MPU6050_DMPINT_3_BIT, MPU6050_RA_DMP_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getDMPInt2Status()
References buffer, devAddr, MPU6050_DMPINT_2_BIT, MPU6050_RA_DMP_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getDMPInt1Status()
References buffer, devAddr, MPU6050_DMPINT_1_BIT, MPU6050_RA_DMP_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getDMPInt0Status()
References buffer, devAddr, MPU6050_DMPINT_0_BIT, MPU6050_RA_DMP_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntPLLReadyStatus()
References buffer, devAddr, MPU6050_INTERRUPT_PLL_RDY_INT_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getIntDMPStatus()
References buffer, devAddr, MPU6050_INTERRUPT_DMP_INT_BIT, MPU6050_RA_INT_STATUS, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
bool MPU6050_Base::getDMPEnabled()
References buffer, devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_DMP_EN_BIT, I2Cdev::readBit, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setDMPEnabled(bool enabled)
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_DMP_EN_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, MPU::init.
void MPU6050_Base::resetDMP()
References devAddr, MPU6050_RA_USER_CTRL, MPU6050_USERCTRL_DMP_RESET_BIT, wireObj, I2Cdev::writeBit.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, PID.
void MPU6050_Base::setMemoryBank(uint8_t bank, bool prefetchEnabled=false, bool userBank=false)
References devAddr, MPU6050_RA_BANK_SEL, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, readMemoryBlock, writeMemoryBlock.
void MPU6050_Base::setMemoryStartAddress(uint8_t address)
References devAddr, MPU6050_RA_MEM_START_ADDR, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, readMemoryBlock, writeMemoryBlock.
uint8_t MPU6050_Base::readMemoryByte()
References buffer, devAddr, MPU6050_RA_MEM_R_W, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
void MPU6050_Base::writeMemoryByte(uint8_t data)
References devAddr, MPU6050_RA_MEM_R_W, wireObj, I2Cdev::writeByte.
void MPU6050_Base::readMemoryBlock(uint8_t *data, uint16_t dataSize, uint8_t bank=0, uint8_t address=0)
References devAddr, MPU6050_DMP_MEMORY_CHUNK_SIZE, MPU6050_RA_MEM_R_W, I2Cdev::readBytes, I2Cdev::readTimeout, setMemoryBank, setMemoryStartAddress, wireObj.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
bool MPU6050_Base::writeMemoryBlock(const uint8_t *data, uint16_t dataSize, uint8_t bank=0, uint8_t address=0, bool verify=true, bool useProgMem=false)
References devAddr, MPU6050_DMP_MEMORY_CHUNK_SIZE, MPU6050_RA_MEM_R_W, I2Cdev::readBytes, I2Cdev::readTimeout, setMemoryBank, setMemoryStartAddress, wireObj, I2Cdev::writeBytes.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize, writeDMPConfigurationSet, writeProgMemoryBlock.
bool MPU6050_Base::writeProgMemoryBlock(const uint8_t *data, uint16_t dataSize, uint8_t bank=0, uint8_t address=0, bool verify=true)
References writeMemoryBlock.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
bool MPU6050_Base::writeDMPConfigurationSet(const uint8_t *data, uint16_t dataSize, bool useProgMem=false)
References devAddr, MPU6050_RA_INT_ENABLE, wireObj, I2Cdev::writeByte, writeMemoryBlock.
Referenced by writeProgDMPConfigurationSet.
bool MPU6050_Base::writeProgDMPConfigurationSet(const uint8_t *data, uint16_t dataSize)
References writeDMPConfigurationSet.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getDMPConfig1()
References buffer, devAddr, MPU6050_RA_DMP_CFG_1, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setDMPConfig1(uint8_t config)
References devAddr, MPU6050_RA_DMP_CFG_1, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
uint8_t MPU6050_Base::getDMPConfig2()
References buffer, devAddr, MPU6050_RA_DMP_CFG_2, I2Cdev::readByte, I2Cdev::readTimeout, wireObj.
void MPU6050_Base::setDMPConfig2(uint8_t config)
References devAddr, MPU6050_RA_DMP_CFG_2, wireObj, I2Cdev::writeByte.
Referenced by MPU6050_6Axis_MotionApps20::dmpInitialize, MPU6050_9Axis_MotionApps41::dmpInitialize.
void MPU6050_Base::CalibrateGyro(uint8_t Loops=15)
Fully calibrate Gyro from ZERO in about 6-7 Loops 600-700 readings.
References PID.
Referenced by MPU::init.
void MPU6050_Base::CalibrateAccel(uint8_t Loops=15)
Fully calibrate Accel from ZERO in about 6-7 Loops 600-700 readings.
References PID.
Referenced by MPU::init.
void MPU6050_Base::PID(uint8_t ReadAddress, float kP, float kI, uint8_t Loops)
References devAddr, getDeviceID, getFullScaleAccelRange, I2Cdev::readTimeout, I2Cdev::readWords, resetDMP, resetFIFO, wireObj, I2Cdev::writeWords.
Referenced by CalibrateAccel, CalibrateGyro.
void MPU6050_Base::PrintActiveOffsets()
References devAddr, getDeviceID, MPU6050_RA_XA_OFFS_H, I2Cdev::readTimeout, I2Cdev::readWords, wireObj.
Referenced by MPU::init.