I2Cdev
uint16_t I2Cdev::readTimeout
Default timeout value for read operations. Set this to 0 to disable timeout detection.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, MPU6050_Base::getAcceleration, MPU6050_Base::getAccelerationX, MPU6050_Base::getAccelerationY, MPU6050_Base::getAccelerationZ, MPU6050_Base::getAccelerometerPowerOnDelay, MPU6050_Base::getAccelFIFOEnabled, MPU6050_Base::getAccelXSelfTest, MPU6050_Base::getAccelXSelfTestFactoryTrim, MPU6050_Base::getAccelYSelfTest, MPU6050_Base::getAccelYSelfTestFactoryTrim, MPU6050_Base::getAccelZSelfTest, MPU6050_Base::getAccelZSelfTestFactoryTrim, MPU6050_Base::getAuxVDDIOLevel, MPU6050_Base::getClockOutputEnabled, MPU6050_Base::getClockSource, MPU6050_Base::getDeviceID, MPU6050_Base::getDHPFMode, MPU6050_Base::getDLPFMode, MPU6050_Base::getDMPConfig1, MPU6050_Base::getDMPConfig2, MPU6050_Base::getDMPEnabled, MPU6050_Base::getDMPInt0Status, MPU6050_Base::getDMPInt1Status, MPU6050_Base::getDMPInt2Status, MPU6050_Base::getDMPInt3Status, MPU6050_Base::getDMPInt4Status, MPU6050_Base::getDMPInt5Status, MPU6050_Base::getExternalFrameSync, MPU6050_Base::getExternalSensorByte, MPU6050_Base::getExternalSensorDWord, MPU6050_Base::getExternalSensorWord, MPU6050_Base::getExternalShadowDelayEnabled, MPU6050_Base::getFIFOByte, MPU6050_Base::getFIFOBytes, MPU6050_Base::getFIFOCount, MPU6050_Base::getFIFOEnabled, MPU6050_Base::getFreefallDetectionCounterDecrement, MPU6050_Base::getFreefallDetectionDuration, MPU6050_Base::getFreefallDetectionThreshold, MPU6050_Base::getFSyncInterruptEnabled, MPU6050_Base::getFSyncInterruptLevel, MPU6050_Base::getFullScaleAccelRange, MPU6050_Base::getFullScaleGyroRange, MPU6050_Base::getGyroXSelfTestFactoryTrim, MPU6050_Base::getGyroYSelfTestFactoryTrim, MPU6050_Base::getGyroZSelfTestFactoryTrim, MPU6050_Base::getI2CBypassEnabled, MPU6050_Base::getI2CMasterModeEnabled, MPU6050_Base::getIntDataReadyEnabled, MPU6050_Base::getIntDataReadyStatus, MPU6050_Base::getIntDMPEnabled, MPU6050_Base::getIntDMPStatus, MPU6050_Base::getIntEnabled, MPU6050_Base::getInterruptDrive, MPU6050_Base::getInterruptLatch, MPU6050_Base::getInterruptLatchClear, MPU6050_Base::getInterruptMode, MPU6050_Base::getIntFIFOBufferOverflowEnabled, MPU6050_Base::getIntFIFOBufferOverflowStatus, MPU6050_Base::getIntFreefallEnabled, MPU6050_Base::getIntFreefallStatus, MPU6050_Base::getIntI2CMasterEnabled, MPU6050_Base::getIntI2CMasterStatus, MPU6050_Base::getIntMotionEnabled, MPU6050_Base::getIntMotionStatus, MPU6050_Base::getIntPLLReadyEnabled, MPU6050_Base::getIntPLLReadyStatus, MPU6050_Base::getIntStatus, MPU6050_Base::getIntZeroMotionEnabled, MPU6050_Base::getIntZeroMotionStatus, MPU6050_Base::getLostArbitration, MPU6050_Base::getMasterClockSpeed, MPU6050_Base::getMotion6, MPU6050_Base::getMotionDetectionCounterDecrement, MPU6050_Base::getMotionDetectionDuration, MPU6050_Base::getMotionDetectionThreshold, MPU6050_Base::getMotionStatus, MPU6050_Base::getMultiMasterEnabled, MPU6050_Base::getOTPBankValid, MPU6050_Base::getPassthroughStatus, MPU6050_Base::getRate, MPU6050_Base::getRotation, MPU6050_Base::getRotationX, MPU6050_Base::getRotationY, MPU6050_Base::getRotationZ, MPU6050_Base::getSlate4InputByte, MPU6050_Base::getSlave0FIFOEnabled, MPU6050_Base::getSlave0Nack, MPU6050_Base::getSlave1FIFOEnabled, MPU6050_Base::getSlave1Nack, MPU6050_Base::getSlave2FIFOEnabled, MPU6050_Base::getSlave2Nack, MPU6050_Base::getSlave3FIFOEnabled, MPU6050_Base::getSlave3Nack, MPU6050_Base::getSlave4Address, MPU6050_Base::getSlave4Enabled, MPU6050_Base::getSlave4InterruptEnabled, MPU6050_Base::getSlave4IsDone, MPU6050_Base::getSlave4MasterDelay, MPU6050_Base::getSlave4Nack, MPU6050_Base::getSlave4Register, MPU6050_Base::getSlave4WriteMode, MPU6050_Base::getSlaveAddress, MPU6050_Base::getSlaveDataLength, MPU6050_Base::getSlaveDelayEnabled, MPU6050_Base::getSlaveEnabled, MPU6050_Base::getSlaveReadWriteTransitionEnabled, MPU6050_Base::getSlaveRegister, MPU6050_Base::getSlaveWordByteSwap, MPU6050_Base::getSlaveWordGroupOffset, MPU6050_Base::getSlaveWriteMode, MPU6050_Base::getSleepEnabled, MPU6050_Base::getStandbyXAccelEnabled, MPU6050_Base::getStandbyXGyroEnabled, MPU6050_Base::getStandbyYAccelEnabled, MPU6050_Base::getStandbyYGyroEnabled, MPU6050_Base::getStandbyZAccelEnabled, MPU6050_Base::getStandbyZGyroEnabled, MPU6050_Base::getTemperature, MPU6050_Base::getTempFIFOEnabled, MPU6050_Base::getTempSensorEnabled, MPU6050_Base::getWaitForExternalSensorEnabled, MPU6050_Base::getWakeCycleEnabled, MPU6050_Base::getWakeFrequency, MPU6050_Base::getXAccelOffset, MPU6050_Base::getXFineGain, MPU6050_Base::getXGyroFIFOEnabled, MPU6050_Base::getXGyroOffset, MPU6050_Base::getXGyroOffsetTC, MPU6050_Base::getXNegMotionDetected, MPU6050_Base::getXPosMotionDetected, MPU6050_Base::getYAccelOffset, MPU6050_Base::getYFineGain, MPU6050_Base::getYGyroFIFOEnabled, MPU6050_Base::getYGyroOffset, MPU6050_Base::getYGyroOffsetTC, MPU6050_Base::getYNegMotionDetected, MPU6050_Base::getYPosMotionDetected, MPU6050_Base::getZAccelOffset, MPU6050_Base::getZeroMotionDetected, MPU6050_Base::getZeroMotionDetectionDuration, MPU6050_Base::getZeroMotionDetectionThreshold, MPU6050_Base::getZFineGain, MPU6050_Base::getZGyroFIFOEnabled, MPU6050_Base::getZGyroOffset, MPU6050_Base::getZGyroOffsetTC, MPU6050_Base::getZNegMotionDetected, MPU6050_Base::getZPosMotionDetected, MPU6050_Base::PID, MPU6050_Base::PrintActiveOffsets, MPU6050_Base::readMemoryBlock, MPU6050_Base::readMemoryByte, writeBit, writeBits, writeBitsW, writeBitW, MPU6050_Base::writeMemoryBlock.
I2Cdev::I2Cdev()
Default constructor.
int8_t I2Cdev::readBit(uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint8_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read a single bit from an 8-bit device register. devAddr I2C slave device address regAddr Register regAddr to read from bitNum Bit position to read (0-7) data Container for single bit value timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Status of read operation (true = success)
References readByte.
Referenced by MPU6050_Base::getAccelFIFOEnabled, MPU6050_Base::getAccelXSelfTest, MPU6050_Base::getAccelYSelfTest, MPU6050_Base::getAccelZSelfTest, MPU6050_Base::getAuxVDDIOLevel, MPU6050_Base::getClockOutputEnabled, MPU6050_Base::getDMPEnabled, MPU6050_Base::getDMPInt0Status, MPU6050_Base::getDMPInt1Status, MPU6050_Base::getDMPInt2Status, MPU6050_Base::getDMPInt3Status, MPU6050_Base::getDMPInt4Status, MPU6050_Base::getDMPInt5Status, MPU6050_Base::getExternalShadowDelayEnabled, MPU6050_Base::getFIFOEnabled, MPU6050_Base::getFSyncInterruptEnabled, MPU6050_Base::getFSyncInterruptLevel, MPU6050_Base::getI2CBypassEnabled, MPU6050_Base::getI2CMasterModeEnabled, MPU6050_Base::getIntDataReadyEnabled, MPU6050_Base::getIntDataReadyStatus, MPU6050_Base::getIntDMPEnabled, MPU6050_Base::getIntDMPStatus, MPU6050_Base::getInterruptDrive, MPU6050_Base::getInterruptLatch, MPU6050_Base::getInterruptLatchClear, MPU6050_Base::getInterruptMode, MPU6050_Base::getIntFIFOBufferOverflowEnabled, MPU6050_Base::getIntFIFOBufferOverflowStatus, MPU6050_Base::getIntFreefallEnabled, MPU6050_Base::getIntFreefallStatus, MPU6050_Base::getIntI2CMasterEnabled, MPU6050_Base::getIntI2CMasterStatus, MPU6050_Base::getIntMotionEnabled, MPU6050_Base::getIntMotionStatus, MPU6050_Base::getIntPLLReadyEnabled, MPU6050_Base::getIntPLLReadyStatus, MPU6050_Base::getIntZeroMotionEnabled, MPU6050_Base::getIntZeroMotionStatus, MPU6050_Base::getLostArbitration, MPU6050_Base::getMultiMasterEnabled, MPU6050_Base::getOTPBankValid, MPU6050_Base::getPassthroughStatus, MPU6050_Base::getSlave0FIFOEnabled, MPU6050_Base::getSlave0Nack, MPU6050_Base::getSlave1FIFOEnabled, MPU6050_Base::getSlave1Nack, MPU6050_Base::getSlave2FIFOEnabled, MPU6050_Base::getSlave2Nack, MPU6050_Base::getSlave3FIFOEnabled, MPU6050_Base::getSlave3Nack, MPU6050_Base::getSlave4Enabled, MPU6050_Base::getSlave4InterruptEnabled, MPU6050_Base::getSlave4IsDone, MPU6050_Base::getSlave4Nack, MPU6050_Base::getSlave4WriteMode, MPU6050_Base::getSlaveDelayEnabled, MPU6050_Base::getSlaveEnabled, MPU6050_Base::getSlaveReadWriteTransitionEnabled, MPU6050_Base::getSlaveWordByteSwap, MPU6050_Base::getSlaveWordGroupOffset, MPU6050_Base::getSlaveWriteMode, MPU6050_Base::getSleepEnabled, MPU6050_Base::getStandbyXAccelEnabled, MPU6050_Base::getStandbyXGyroEnabled, MPU6050_Base::getStandbyYAccelEnabled, MPU6050_Base::getStandbyYGyroEnabled, MPU6050_Base::getStandbyZAccelEnabled, MPU6050_Base::getStandbyZGyroEnabled, MPU6050_Base::getTempFIFOEnabled, MPU6050_Base::getTempSensorEnabled, MPU6050_Base::getWaitForExternalSensorEnabled, MPU6050_Base::getWakeCycleEnabled, MPU6050_Base::getXGyroFIFOEnabled, MPU6050_Base::getXNegMotionDetected, MPU6050_Base::getXPosMotionDetected, MPU6050_Base::getYGyroFIFOEnabled, MPU6050_Base::getYNegMotionDetected, MPU6050_Base::getYPosMotionDetected, MPU6050_Base::getZeroMotionDetected, MPU6050_Base::getZGyroFIFOEnabled, MPU6050_Base::getZNegMotionDetected, MPU6050_Base::getZPosMotionDetected.
int8_t I2Cdev::readBitW(uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint16_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read a single bit from a 16-bit device register. devAddr I2C slave device address regAddr Register regAddr to read from bitNum Bit position to read (0-15) data Container for single bit value timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Status of read operation (true = success)
References readWord.
int8_t I2Cdev::readBits(uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint8_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read multiple bits from an 8-bit device register. devAddr I2C slave device address regAddr Register regAddr to read from bitStart First bit position to read (0-7) length Number of bits to read (not more than 8) data Container for right-aligned value (i.e. '101' read from any bitStart position will equal 0x05) timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Status of read operation (true = success)
References readByte.
Referenced by MPU6050_Base::getAccelerometerPowerOnDelay, MPU6050_Base::getClockSource, MPU6050_Base::getDeviceID, MPU6050_Base::getDHPFMode, MPU6050_Base::getDLPFMode, MPU6050_Base::getExternalFrameSync, MPU6050_Base::getFreefallDetectionCounterDecrement, MPU6050_Base::getFullScaleAccelRange, MPU6050_Base::getFullScaleGyroRange, MPU6050_Base::getMasterClockSpeed, MPU6050_Base::getMotionDetectionCounterDecrement, MPU6050_Base::getSlave4MasterDelay, MPU6050_Base::getSlaveDataLength, MPU6050_Base::getWakeFrequency, MPU6050_Base::getXGyroOffsetTC, MPU6050_Base::getYGyroOffsetTC, MPU6050_Base::getZGyroOffsetTC.
int8_t I2Cdev::readBitsW(uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint16_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read multiple bits from a 16-bit device register. devAddr I2C slave device address regAddr Register regAddr to read from bitStart First bit position to read (0-15) length Number of bits to read (not more than 16) data Container for right-aligned value (i.e. '101' read from any bitStart position will equal 0x05) timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Status of read operation (1 = success, 0 = failure, -1 = timeout)
References readWord.
int8_t I2Cdev::readByte(uint8_t devAddr, uint8_t regAddr, uint8_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read single byte from an 8-bit device register. devAddr I2C slave device address regAddr Register regAddr to read from data Container for byte value read from device timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Status of read operation (true = success)
References readBytes.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, MPU6050_Base::getAccelXSelfTestFactoryTrim, MPU6050_Base::getAccelYSelfTestFactoryTrim, MPU6050_Base::getDMPConfig1, MPU6050_Base::getDMPConfig2, MPU6050_Base::getExternalSensorByte, MPU6050_Base::getFIFOByte, MPU6050_Base::getFreefallDetectionDuration, MPU6050_Base::getFreefallDetectionThreshold, MPU6050_Base::getGyroXSelfTestFactoryTrim, MPU6050_Base::getGyroYSelfTestFactoryTrim, MPU6050_Base::getGyroZSelfTestFactoryTrim, MPU6050_Base::getIntEnabled, MPU6050_Base::getIntStatus, MPU6050_Base::getMotionDetectionDuration, MPU6050_Base::getMotionDetectionThreshold, MPU6050_Base::getMotionStatus, MPU6050_Base::getRate, MPU6050_Base::getSlate4InputByte, MPU6050_Base::getSlave4Address, MPU6050_Base::getSlave4Register, MPU6050_Base::getSlaveAddress, MPU6050_Base::getSlaveRegister, MPU6050_Base::getXFineGain, MPU6050_Base::getYFineGain, MPU6050_Base::getZeroMotionDetectionDuration, MPU6050_Base::getZeroMotionDetectionThreshold, MPU6050_Base::getZFineGain, readBit, readBits, MPU6050_Base::readMemoryByte, writeBit, writeBits.
int8_t I2Cdev::readWord(uint8_t devAddr, uint8_t regAddr, uint16_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read single word from a 16-bit device register. devAddr I2C slave device address regAddr Register regAddr to read from data Container for word value read from device timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Status of read operation (true = success)
References readWords.
Referenced by readBitsW, readBitW, writeBitsW, writeBitW.
int8_t I2Cdev::readBytes(uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read multiple bytes from an 8-bit device register. devAddr I2C slave device address regAddr First register regAddr to read from length Number of bytes to read data Buffer to store read data in timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Number of bytes read (-1 indicates failure)
References TwoWire::available, TwoWire::beginTransmission, TwoWire::endTransmission, I2CDEVLIB_WIRE_BUFFER_LENGTH, TwoWire::read, TwoWire::requestFrom, Wire, TwoWire::write.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, MPU6050_Base::getAcceleration, MPU6050_Base::getAccelerationX, MPU6050_Base::getAccelerationY, MPU6050_Base::getAccelerationZ, MPU6050_Base::getAccelZSelfTestFactoryTrim, MPU6050_Base::getExternalSensorDWord, MPU6050_Base::getExternalSensorWord, MPU6050_Base::getFIFOBytes, MPU6050_Base::getFIFOCount, MPU6050_Base::getMotion6, MPU6050_Base::getRotation, MPU6050_Base::getRotationX, MPU6050_Base::getRotationY, MPU6050_Base::getRotationZ, MPU6050_Base::getTemperature, MPU6050_Base::getXAccelOffset, MPU6050_Base::getXGyroOffset, MPU6050_Base::getYAccelOffset, MPU6050_Base::getYGyroOffset, MPU6050_Base::getZAccelOffset, MPU6050_Base::getZGyroOffset, readByte, MPU6050_Base::readMemoryBlock, MPU6050_Base::writeMemoryBlock.
int8_t I2Cdev::readWords(uint8_t devAddr, uint8_t regAddr, uint8_t length, uint16_t *data, uint16_t timeout=I2Cdev::readTimeout, void *wireObj=0)
Read multiple words from a 16-bit device register. devAddr I2C slave device address regAddr First register regAddr to read from length Number of words to read data Buffer to store read data in timeout Optional read timeout in milliseconds (0 to disable, leave off to use default class value in I2Cdev::readTimeout) Number of words read (-1 indicates failure)
References TwoWire::available, TwoWire::beginTransmission, TwoWire::endTransmission, I2CDEVLIB_WIRE_BUFFER_LENGTH, TwoWire::read, TwoWire::requestFrom, Wire, TwoWire::write.
Referenced by MPU6050_Base::PID, MPU6050_Base::PrintActiveOffsets, readWord.
bool I2Cdev::writeBit(uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint8_t data, void *wireObj=0)
write a single bit in an 8-bit device register. devAddr I2C slave device address regAddr Register regAddr to write to bitNum Bit position to write (0-7) value New bit value to write Status of operation (true = success)
References readByte, readTimeout, writeByte.
Referenced by MPU6050_Base::reset, MPU6050_Base::resetAccelerometerPath, MPU6050_Base::resetDMP, MPU6050_Base::resetFIFO, MPU6050_Base::resetGyroscopePath, MPU6050_Base::resetI2CMaster, MPU6050_Base::resetSensors, MPU6050_Base::resetTemperaturePath, MPU6050_Base::setAccelFIFOEnabled, MPU6050_Base::setAccelXSelfTest, MPU6050_Base::setAccelYSelfTest, MPU6050_Base::setAccelZSelfTest, MPU6050_Base::setAuxVDDIOLevel, MPU6050_Base::setClockOutputEnabled, MPU6050_Base::setDMPEnabled, MPU6050_Base::setExternalShadowDelayEnabled, MPU6050_Base::setFIFOEnabled, MPU6050_Base::setFSyncInterruptEnabled, MPU6050_Base::setFSyncInterruptLevel, MPU6050_Base::setI2CBypassEnabled, MPU6050_Base::setI2CMasterModeEnabled, MPU6050_Base::setIntDataReadyEnabled, MPU6050_Base::setIntDMPEnabled, MPU6050_Base::setInterruptDrive, MPU6050_Base::setInterruptLatch, MPU6050_Base::setInterruptLatchClear, MPU6050_Base::setInterruptMode, MPU6050_Base::setIntFIFOBufferOverflowEnabled, MPU6050_Base::setIntFreefallEnabled, MPU6050_Base::setIntI2CMasterEnabled, MPU6050_Base::setIntMotionEnabled, MPU6050_Base::setIntPLLReadyEnabled, MPU6050_Base::setIntZeroMotionEnabled, MPU6050_Base::setMultiMasterEnabled, MPU6050_Base::setOTPBankValid, MPU6050_Base::setSlave0FIFOEnabled, MPU6050_Base::setSlave1FIFOEnabled, MPU6050_Base::setSlave2FIFOEnabled, MPU6050_Base::setSlave3FIFOEnabled, MPU6050_Base::setSlave4Enabled, MPU6050_Base::setSlave4InterruptEnabled, MPU6050_Base::setSlave4WriteMode, MPU6050_Base::setSlaveDelayEnabled, MPU6050_Base::setSlaveEnabled, MPU6050_Base::setSlaveReadWriteTransitionEnabled, MPU6050_Base::setSlaveWordByteSwap, MPU6050_Base::setSlaveWordGroupOffset, MPU6050_Base::setSlaveWriteMode, MPU6050_Base::setSleepEnabled, MPU6050_Base::setStandbyXAccelEnabled, MPU6050_Base::setStandbyXGyroEnabled, MPU6050_Base::setStandbyYAccelEnabled, MPU6050_Base::setStandbyYGyroEnabled, MPU6050_Base::setStandbyZAccelEnabled, MPU6050_Base::setStandbyZGyroEnabled, MPU6050_Base::setTempFIFOEnabled, MPU6050_Base::setTempSensorEnabled, MPU6050_Base::setWaitForExternalSensorEnabled, MPU6050_Base::setWakeCycleEnabled, MPU6050_Base::setXGyroFIFOEnabled, MPU6050_Base::setYGyroFIFOEnabled, MPU6050_Base::setZGyroFIFOEnabled, MPU6050_Base::switchSPIEnabled.
bool I2Cdev::writeBitW(uint8_t devAddr, uint8_t regAddr, uint8_t bitNum, uint16_t data, void *wireObj=0)
write a single bit in a 16-bit device register. devAddr I2C slave device address regAddr Register regAddr to write to bitNum Bit position to write (0-15) value New bit value to write Status of operation (true = success)
References readTimeout, readWord, writeWord.
bool I2Cdev::writeBits(uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint8_t data, void *wireObj=0)
Write multiple bits in an 8-bit device register. devAddr I2C slave device address regAddr Register regAddr to write to bitStart First bit position to write (0-7) length Number of bits to write (not more than 8) data Right-aligned value to write Status of operation (true = success)
References readByte, readTimeout, writeByte.
Referenced by MPU6050_Base::setAccelerometerPowerOnDelay, MPU6050_Base::setClockSource, MPU6050_Base::setDeviceID, MPU6050_Base::setDHPFMode, MPU6050_Base::setDLPFMode, MPU6050_Base::setExternalFrameSync, MPU6050_Base::setFreefallDetectionCounterDecrement, MPU6050_Base::setFullScaleAccelRange, MPU6050_Base::setFullScaleGyroRange, MPU6050_Base::setMasterClockSpeed, MPU6050_Base::setMotionDetectionCounterDecrement, MPU6050_Base::setSlave4MasterDelay, MPU6050_Base::setSlaveDataLength, MPU6050_Base::setWakeFrequency, MPU6050_Base::setXGyroOffsetTC, MPU6050_Base::setYGyroOffsetTC, MPU6050_Base::setZGyroOffsetTC.
bool I2Cdev::writeBitsW(uint8_t devAddr, uint8_t regAddr, uint8_t bitStart, uint8_t length, uint16_t data, void *wireObj=0)
Write multiple bits in a 16-bit device register. devAddr I2C slave device address regAddr Register regAddr to write to bitStart First bit position to write (0-15) length Number of bits to write (not more than 16) data Right-aligned value to write Status of operation (true = success)
References readTimeout, readWord, writeWord.
bool I2Cdev::writeByte(uint8_t devAddr, uint8_t regAddr, uint8_t data, void *wireObj=0)
Write single byte to an 8-bit device register. devAddr I2C slave device address regAddr Register address to write to data New byte value to write Status of operation (true = success)
References writeBytes.
Referenced by MPU6050_9Axis_MotionApps41::dmpInitialize, MPU6050_Base::setDMPConfig1, MPU6050_Base::setDMPConfig2, MPU6050_Base::setFIFOByte, MPU6050_Base::setFreefallDetectionDuration, MPU6050_Base::setFreefallDetectionThreshold, MPU6050_Base::setIntEnabled, MPU6050_Base::setMemoryBank, MPU6050_Base::setMemoryStartAddress, MPU6050_Base::setMotionDetectionDuration, MPU6050_Base::setMotionDetectionThreshold, MPU6050_Base::setRate, MPU6050_Base::setSlave4Address, MPU6050_Base::setSlave4OutputByte, MPU6050_Base::setSlave4Register, MPU6050_Base::setSlaveAddress, MPU6050_Base::setSlaveOutputByte, MPU6050_Base::setSlaveRegister, MPU6050_Base::setXFineGain, MPU6050_Base::setYFineGain, MPU6050_Base::setZeroMotionDetectionDuration, MPU6050_Base::setZeroMotionDetectionThreshold, MPU6050_Base::setZFineGain, writeBit, writeBits, MPU6050_Base::writeDMPConfigurationSet, MPU6050_Base::writeMemoryByte.
bool I2Cdev::writeWord(uint8_t devAddr, uint8_t regAddr, uint16_t data, void *wireObj=0)
Write single word to a 16-bit device register. devAddr I2C slave device address regAddr Register address to write to data New word value to write Status of operation (true = success)
References writeWords.
Referenced by MPU6050_Base::setXAccelOffset, MPU6050_Base::setXGyroOffset, MPU6050_Base::setYAccelOffset, MPU6050_Base::setYGyroOffset, MPU6050_Base::setZAccelOffset, MPU6050_Base::setZGyroOffset, writeBitsW, writeBitW.
bool I2Cdev::writeBytes(uint8_t devAddr, uint8_t regAddr, uint8_t length, uint8_t *data, void *wireObj=0)
Write multiple bytes to an 8-bit device register. devAddr I2C slave device address regAddr First register address to write to length Number of bytes to write data Buffer to copy new data from Status of operation (true = success)
References TwoWire::beginTransmission, TwoWire::endTransmission, Wire, TwoWire::write.
Referenced by writeByte, MPU6050_Base::writeMemoryBlock.
bool I2Cdev::writeWords(uint8_t devAddr, uint8_t regAddr, uint8_t length, uint16_t *data, void *wireObj=0)
Write multiple words to a 16-bit device register. devAddr I2C slave device address regAddr First register address to write to length Number of words to write data Buffer to copy new data from Status of operation (true = success)
References TwoWire::beginTransmission, TwoWire::endTransmission, Wire, TwoWire::write.
Referenced by MPU6050_Base::PID, writeWord.